### ISSUE TITLE
Can't create a new note in the demo version

### ISSUE THREAD

**Issue by lherich** [twostairs/paperwork#100]
After sign into the demo version, I tried to create a new note via "file -> new note", but it failed due to the following reason:

Request URL:http://demo.paperwork.rocks/api/v1/notebooks/1545/notes
Request Method:POST
Status Code:500 Internal Server Error

```javascript
{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null (SQL: insert into `versions` (`title`, `content`, `updated_at`, `created_at`) values (, , 2015-01-26 01:21:53, 2015-01-26 01:21:53))","file":"\/srv\/paperwork\/frontend\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":625}}
```

**Comment by johb** [comment]
Hi,
the reason for this bug is, that in paperworkSidebarNotesController.js in line 37 the default name (untitled) for a new note is taken from the language files:

    var data = {
      'title': $rootScope.i18n.keywords.untitled,
      'content': ''
    };

For the german version, there exists no such entry, so title is undefined and this causes the error.

**Comment by devilx** [comment]
@johb great, thank you! :+1:
