### ISSUE TITLE
UI missing saved successfully dialog

### ISSUE THREAD

**Issue by OmgImAlexis** [twostairs/paperwork#102]
There's currently no indication that the save button worked apart from seeing the XHR request in the console.

**Comment by devilx** [comment]
True. Although I think a "saved successfully"-dialog might be too obtrusive here. Maybe perform some UI magic with the save button, as in:

1) Save button clicked
2) Save icon transforms to rotating circle while it performs the XHR request
3) Rotating icon transforms to "check"-icon and stays for a couple of seconds
4) "check"-icon switches back to save icon.

Does anyone know, if there's some ng-extension that already implements this is a nice way?

**Comment by lutze** [comment]
@devilx - If I can offer a refinement to that, it would be helpful if the save button (and the "saved" state) was aware of changes in the document. 

As in, for step 3, the "saved" state remains until the user makes a new change to the document that would require saving again, then stepping to step 4.

**Comment by devilx** [comment]
@lutze that's aleady implemented. You should notice it when you watch your XHR requests. You won't be able to perform another save until you haven't changed anything. But yes, we could visualise this more explicitly, for example by disabling the save button, until a change was made.

**Comment by lutze** [comment]
@devilx that's great. 

Is the request here open for forking and a pull request? I think it'd be interesting to dig into what y'all have put together.

**Comment by devilx** [comment]
@lutze sure, if you'd like to work on this just go ahead. :+1:

**Comment by lutze** [comment]
Great, I'll give it a look when I get home from work tonight.

**Comment by awchauhdry** [comment]
i think we should maybe disable the save button, visually to show until it can be saved again, at the moment, it just doesn't seem like anything happened

**Comment by lutze** [comment]
@awchauhdry that's exactly the idea, definitely.

**Comment by devilx** [comment]
@lutze anything new on this?

**Comment by lutze** [comment]
Lost this in a heavy sprint at work -- thanks for the reminder. Let me check back in a day.

**Comment by Liongold** [comment]
As part of my work on #146, I have added a notification for this until a consensus is reached on this issue. More info will be posted soon.

**Comment by Baldrs** [comment]
So here we may add some interaction to the save button and we're done

**Comment by Liongold** [comment]
Since there haven't been any complain lately about this issue, this issue will be closed. Thanks for your feedback. If you re-encounter this issue or have any new comments, please reopen the issue.
