### ISSUE TITLE
Can't connect to mysql on demo.paperwork.rocks

### ISSUE THREAD

**Issue by Baldrs** [twostairs/paperwork#106]
PDOException (2003) 
    SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)

When submitting the register form: http://demo.paperwork.rocks/register

**Comment by devilx** [comment]
I've explained the reason for this here: https://github.com/twostairs/paperwork/issues/107

Sorry for that, but unfortunately I can't do anything about it right now.
