### ISSUE TITLE
New hosting for demo.paperwork.rocks

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#107]
Currently, demo.paperwork.rocks is a $5 DigitalOcean Droplet that's being paid by me/twostairs. This worked out pretty well, until Paperwork got featured on HackerNews recently. Since then, the MySQL database permanently runs out of RAM (as mentioned here: https://github.com/twostairs/paperwork/issues/101#issuecomment-71436211).

Maybe we could find some generous people running some sort of infrastructure, willing to donate a larger demo-machine for Paperwork?

**Comment by OmgImAlexis** [comment]
Try contacting DO, they seem to be really behind open source projects like this. They may be able to help you out with a 4GB machine or something, worst thing they can do is say no.

**Comment by devilx** [comment]
@OmgImAlexis :+1: https://twitter.com/paperworkrocks/status/559655528637689856 let's see what they say. :-)

**Comment by erayaydin** [comment]
Any news about new machine ? Is DO confirm? I'm using DO and I am interested about this.

> Now, I love DigitalOcean too more :smile:

**Comment by devilx** [comment]
Status update: DO said that they're interested in general and I should write them an e-mail with all the details. So I did. Now let's wait and see what they're answering. :-)

In addition, "RunAbove" tweeted us: https://twitter.com/runabove/status/559656500172701696

Has anyone experience with them?

**Comment by wagonza** [comment]
and as a friend pointed out maybe a SSL cert for the demo site

**Comment by maced0n** [comment]
You can also switch to Nginx and FPM + Opcache

**Comment by Baldrs** [comment]
@maced0n their main problem is mysql side, they need a couple of instances of mysql to deal with increasing load and better caching of everything that can be cached to reduce mysql load, too. Nginx + PHP-FPM will not fix mysql outages, but will improve overall response time.

**Comment by maced0n** [comment]
@Baldrs Under heavier load Apache consume far more RAM than Nginx.

**Comment by devilx** [comment]
Jfyi: We went from 12 Users a day to over 24k/day, from one day to another. Of course, there are a lot of optimisations that could be performed on the demo system, even though I wouldn't consider the whole thing something "mission critical", as it is just a demo system. I believe, we're good to go with a machine that has a couple of more GBs of RAM in order for the MySQL to work properly. Especially since the 24k/day probably won't remain this high for the next few months (even though it would be nice, heh).

The main reason I picked a default LAMP stack was simplicity. Locally, I use a MAMP for development purposes, and was far easier for me to debug things when the demo-machine runs the "same" stack. But of course, this could be reconsidered as the project gets larger and receive more support by all of you people. :+1:

**Comment by devilx** [comment]
Here are some news on the DO topic:

Juliann from DigitalOcean replied to my request with the following:

> We would be proud to contribute to Paperwork by offering you 3 months of hosting credit, valued at $60.

With this credit, a $20 instance (2GB RAM, 2 Cores, 40 GB SSD, 3TB transfer) could be used for no more than 3 months. No words about a follow-up sponsoring so far. The thing is: If I would upgrade the DO instance to the $20 version, I'm not sure whether I can downgrade it again to $5 as soon as the credit was consumed, if DO should decide to not prolong the sponsoring.

Right now the traffic "normalised", as the hype flattened, but as soon as Paperwork should receive media coverage again, the demo-server will break. Not to mention the (preferably WordPress) site I'm planning to set up in order for Paperwork to have a great landing-page (see #31).

Any thoughts?

**Comment by OmgImAlexis** [comment]
You can downgrade quite easily, just save a snapshot and then delete the droplet and create a new one on the $5 plan with the snapshot. I do this quite often and only leaves about a minute of down time. 

Also like people in #31 have said WordPress provably isn't the best option.

**Comment by devilx** [comment]
@OmgImAlexis this would require changing the DNS, since the IP would change, wouldn't it?

As I commented on #31, WordPress surely isn't the best option from a tech point of view – but makes life a lot easier from a marketing standpoint. And at a certain point, we will need to market to users. :-)

**Comment by OmgImAlexis** [comment]
Not necessarily, if you rebuild from a current droplet you almost always keep the IP.

Yeah I read what you said but what did you mean by "social channels, providing blog-functionality and permit better user interaction". The "user interaction" and "social channels" doesn't really sound like it'd be needed all that much with a project like this, I could be wrong though. Have you looked at something like Ghost with Disqus?

**Comment by devilx** [comment]
Okay, status update: Since communication with DigitalOcean was way too slow and tiring, the great guys from RunAbove jumped on the Paperwork-train, offering us a pretty sweet infrastructure for the future paperwork.rocks site and the demo.paperwork.rocks. Currently, I'm building up the new server – this time using a more lightweight setup with Nginx. I guess, this issue can be closed now. :-)

**Comment by Baldrs** [comment]
Can't we completely get rid of apache? I'm running nginx+php5-fpm+mariadb setup of paperwork and it feels better than apache setup.

**Comment by devilx** [comment]
@Baldrs that's what I just said. :-) For the new instance, I'll be using exactly the setup you described.

**Comment by amenk** [comment]
Hmm .. but the demo is not running ... reopen?

**Comment by BenoitDuffez** [comment]
How has it been going? Demo is still dead :(

**Comment by Multipass2** [comment]
@BenoitDuffez they have a Cloudron and Sandstorm demo available if you check the bottom of their main github page

**Comment by BenoitDuffez** [comment]
Yup, my comment is obsolete. Sorry 😀
