### ISSUE TITLE
Tabbing out of the tag editor in chrome doesn't add a tag

### ISSUE THREAD

**Issue by djave-co** [twostairs/paperwork#108]
![image](https://cloud.githubusercontent.com/assets/1035284/5898751/7d61c7ba-a54a-11e4-9337-fa637d46330f.png)

You need to always write a comma, even if you are finished and want to tab to the next section.

**Comment by devilx** [comment]
This should have been fixed in #92. Are you running the latest Git version of Paperwork?

**Comment by Baldrs** [comment]
Closing as abandoned and outdated.
