### ISSUE TITLE
Tidy up all angular code according code style

### ISSUE THREAD

**Issue by Baldrs** [twostairs/paperwork#112]
Having all scripts lying around as junk without any particular structure is a bad practice, especially in angular applications. And all javascript should be organized as well.

https://github.com/johnpapa/angularjs-styleguide
https://github.com/johnpapa/angularjs-styleguide#application-structure

**Comment by devilx** [comment]
Basically there is *some* structure, even though it might not be perfect. I'm thankful for anyone better with AngularJS than I am taking a look at it and refactoring everything that's implemented improperly. :+1:

**Comment by devilx** [comment]
PS: Duplicate of #17. Sorry. :-)

**Comment by Baldrs** [comment]
Am I welcome to submit a pull requests on some issues?

**Comment by devilx** [comment]
@Baldrs you are welcome! :-)
