### ISSUE TITLE
Translate on transifex

### ISSUE THREAD

**Issue by brunobatista** [twostairs/paperwork#114]
I propose use transifex to help translate this project for another languages. I wish translate for portuguese.

**Comment by Baldrs** [comment]
I could help with russian/ukrainian

**Comment by devilx** [comment]
@brunobatista open for any kind of suggestions in that area. The way translating currently works can definitely be enhanced!

I personally don't know "transifex" -> you mean this here, right? https://www.transifex.com

Do you know if they have some "opensource" plan, which is free of charge?

@Baldrs that would be cool!

**Comment by sunyoureyes** [comment]
I also can help translate to russian/ukrainian. I will contact Baldrs to discuss.

**Comment by AlexanderS** [comment]
@devilx Yes there is a free plan for open source projects. Look at: https://www.transifex.com/pricing/ just in the middle under the "Try it for free" button.

**Comment by devilx** [comment]
Okay, so I've set up a Paperwork project there: https://www.transifex.com/projects/p/paperwork/

Could anyone check it out and see, whether that's the best way to do it? Right now, I need to upload every translation manually from the .php files we have in Paperwork. Could I somehow make this service sync translations with GitHub?

**Comment by brunobatista** [comment]
Thanks @devilx, I submitted request for Brazilian Portuguese. Transifex is a nice place to start translate for another languages. I not know how import it for github, but I think is possible.

**Comment by brunobatista** [comment]
I'll close this because I believe that was resolved. Thanks @devilx, @AlexanderS, @Baldrs and @sunyoureyes :+1:

**Comment by brunobatista** [comment]
Portuguese done! https://www.transifex.com/projects/p/paperwork/language/pt_BR/

**Comment by devilx** [comment]
@brunobatista very cool, thank you! So, how do we export this in order for it to land into Paperwork?

**Comment by Baldrs** [comment]
We have done Ukrainian and Russian localisations. By now they are quite crude and should attend real usage testing to be corrected and improved, but seem to cover all the strings in the files.

**Comment by AlexanderS** [comment]
@devilx You want to install the transifex-client (on linux you could either install it from your package management or [using pip](using pip)) and execute ``tx pull`` in the repo (you can limit the languages with options see ``tx pull --help``, maybe you have to use ``-a`` for new languages). You also want to have a look at ``messages.php``, it seems that transifex does not support nested arrays.

Btw. if the translation source files change (the files for english), _you_ could use ``tx push`` to update the files on the transifex server.

**Comment by devilx** [comment]
@AlexanderS danke! I will check out the client and see how messages.php can be fixed. Maybe by using the other array-type transifex provides.

**Comment by brunobatista** [comment]
@devilx I waiting for portuguese approval. Thanks.
