### ISSUE TITLE
Adding Tag

### ISSUE THREAD

**Issue by erayaydin** [twostairs/paperwork#115]
Hello,

This issue about "Adding tags to note". When I set tags with ",", my last tag duplicate (when I click to textbox)

![Screenshoot](http://i.imgur.com/rbj0MN7.png)

> There is no Javascript error (on console)

**Comment by erayaydin** [comment]
So sorry I forget search issues... sorry :(

#101

**Comment by devilx** [comment]
Np, thanks for reporting/closing! :+1:
