### ISSUE TITLE
Installation problem using fig

### ISSUE THREAD

**Issue by jamesscottbrown** [twostairs/paperwork#116]
I cloned the repository and started a server using fig, but then got an error message when I tried to create the first user:

    Illuminate \ Database \ QueryException (HY000)

    SQLSTATE[HY000]: General error: 1364 Field 'remember_token' doesn't have a default value (SQL: insert into `users` (`username`, `firstname`, `lastname`, `password`, `updated_at`, `created_at`) values (a@example.com, a, a, y$zinC/WtCDrJzvepGiuamluPWi5NxICqhZxuFMXRumRTMJ1rxKtsqe, 2015-01-26 17:22:17, 2015-01-26 17:22:17))

This may be because MySQL in the image has strict mode enabled by the line in /etc/mysql/my.cnf :

    sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES

I haven't used fig or docker before and don't know how to change this.

**Comment by devilx** [comment]
This is something maybe @bsingr could help with, as he was the one submitting the docker stuff. :-)

**Comment by Baldrs** [comment]
Seems to be long fixed
