### ISSUE TITLE
Running Paperworks on MAMP

### ISSUE THREAD

**Issue by KamesCG** [twostairs/paperwork#117]
I installed Paperwork on MAMP with PHP version 5.5.10.

Changed the database.php settings to match the MAMP environment.

When I login and try to add a Notebook, I'm met with nothing...Is this because the port and host was changed?
 
I added the following to my .bash_profile to run successfully run "composer install"
export PATH="/Applications/MAMP/bin/php/php5.5.10/bin:$PATH"

'mysql' => array(
			'driver'    => 'mysql',
			'host'      => 'localhost',
			'port'		  => '8888',
			'database'  => 'paper',
			'username'  => 'root',
			'password'  => 'MYPASSWORD',
			'charset'   => 'utf8',
			'collation' => 'utf8_general_ci',
			'prefix'    => '',
		),

**Comment by devilx** [comment]
Could you show us some more info? Like ```tail -n 20 /Applications/MAMP/logs/php_error.log```?

**Comment by KamesCG** [comment]
I would love to, but there is nothing in my php_error.log...

**Comment by KamesCG** [comment]
It was a root directory problem... sorry for the confusion.

Remember to create a new server for Paperwork and navigate to it by using paper:8888 everyone :)

![screen shot 2015-01-26 at 1 42 35 pm](https://cloud.githubusercontent.com/assets/3408362/5908999/3efc834a-a561-11e4-9d91-e9be17e5b5dd.png)

**Comment by devilx** [comment]
@KamesCG so everything is running smoothly now? Then I'll just close this. :-)
