### ISSUE TITLE
MindMap feature in Paperwork.

### ISSUE THREAD

**Issue by sunyoureyes** [twostairs/paperwork#118]
I think that is will be good to create a mind map in my notes. 
For the first time in some basic level mind maps.
I always missed this function in other notebooks.

Have ideas how to realize this? 
![map_3](https://cloud.githubusercontent.com/assets/7645796/5907734/204a5ae6-a5aa-11e4-971b-5887bec74d4e.gif)

**Comment by devilx** [comment]
I think, this would reach too much into another area/market. There are plenty of tools for creating great MindMaps already. What's the purpose of implementing this feature *into* Paperwork? Basically, you could export your MindMaps as PDFs and upload them into Paperwork.

I might be wrong here, but I believe that Paperwork shouldn't become a jack of all trades device.

**Comment by jacobbridges** [comment]
What if you allowed snippets of HTML to be included into a note? Such as a Gist embed or (gasp!)  an iframe. This way if I create a mindmap through an external product then I could embed that mindmap into a note.

**Comment by devilx** [comment]
I thought this through. Including external references always is a bad idea when *archiving* something. The external reference could be gone someday, leaving you with one (or many) note(s) containing just an empty iframe. I think, building the mindmap using some tool and simply uploading it using Paperwork's uploader is generally the best approach for this.
