### ISSUE TITLE
Export function

### ISSUE THREAD

**Issue by volkerpfosten** [twostairs/paperwork#12]
Hey!

are there any plans for implementing an export function in nearer future? Since I see me updating quite frequently, I want to backup my notes outside of the server environment.

best regards!

**Comment by Liongold** [comment]
Can you show me an export of multiple notebooks please?

**Comment by devilx** [comment]
It turned out Evernote can't export multiple notebooks at selectively. You can either export the notes from one notebook or *all* the notes available.

I can't demonstrate the latter since I'm - unfortunately - having sensitive data in Evernote. Please create a test account on evernote.com and try it out.

**Comment by Liongold** [comment]
I've opened a pull request for this feature. It's at pull request #41. Could you please check it out and comment since it's my first Laravel code?

**Comment by devilx** [comment]
#41 was implemented by @Liongold and just merged into master. @volkerpfosten if you'd like, feel free to update & test.

**Comment by devilx** [comment]
@Liongold could you check your code? I just tested it and found an issue:

Undefined variable: attachments (View: /Users/devilx/Projects/paperwork/frontend/app/views/user/settings/export_file.blade.php)

I took a look into the file and found something weird:

``
    @if(isset($tags))
    @foreach ($attachments as $attachment)
        <en-media type="[[ $attachment['mimetype'] ]]" hash="[[ $attachment['hash'] ]]" /><br />
    @endforeach
    @endif
``

Is this supposed to check for $tags but then still use $attachments?

**Comment by Liongold** [comment]
Apologies for that issue. It should check for $attachments. I'll do it as
soon as possible.

-- 
Sincerely,
Jean Spiteri.

**Comment by Liongold** [comment]
Can you check it now, please?

**Comment by devilx** [comment]
Looks good now! Thank you!
