### ISSUE TITLE
New Note not possible in German

### ISSUE THREAD

**Issue by sango0711** [twostairs/paperwork#124]
When i change the language to german i can't add a new note. In the english setting it is possible. Tried Chrome, Firefox and IE on Win7, with Apache+PHP and nginx+php-fpm

**Comment by Liongold** [comment]
Do you have the latest version of the repo?

On Tuesday, January 27, 2015, sango0711 <notifications@github.com> wrote:

> When i change the language to german i can't add a new note. In the
> english setting it is possible. Tried Chrome, Firefox and IE on Win7, with
> Apache+PHP and nginx+php-fpm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twostairs/paperwork/issues/124>.
>


-- 
Sincerely,
Jean Spiteri.

**Comment by devilx** [comment]
@sango0711 please update to the latest version of the repo, this was fixed yesterday.
