### ISSUE TITLE
Sign up form error message does not match form fields.

### ISSUE THREAD

**Issue by paulcuth** [twostairs/paperwork#125]
When attempting to sign up on the demo page, I get the error message:
>  The username has already been taken.

However, this message does not relate to any of the form fields; there are only: Email address, First name, Last name, Password, Confirm, UI Language. The is no Username field.

Presumably, this refers to Email address? Should be more explicit though.

Steps to recreate:
1. Go to http://demo.paperwork.rocks/register
2. Enter "test@test.com" into email address and anything in other fields.
3. Click "Sign up"

**Comment by devilx** [comment]
Good point!

**Comment by Liongold** [comment]
I've fixed this with the mentioned commit.
