### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by weems** [twostairs/paperwork#128]
when running php composer.phar diagnose: 

Checking composer.json: FAIL
require.jenssegers/agent : unbound version constraints (*) should be avoided
require.erusev/parsedown : unbound version constraints (dev-master) should be avoided
require.thiagoalessio/tesseract_ocr : unbound version constraints (>= 0.2.0) should be avoided
Checking platform settings: OK
Checking git settings: OK

**Comment by jamesrascal** [comment]
What OS are you attempting to install this to?

**Comment by weems** [comment]
OSX 10.10.1

**Comment by devilx** [comment]
That's basically no issue... diagnose only tells you things you *shouldn't* do. You should still be able to run composer install (or update) in order to get all dependencies and run your own Paperwork installation. :-) Please report back if not.
