### ISSUE TITLE
Noting happens while creating new Notes

### ISSUE THREAD

**Issue by sunel** [twostairs/paperwork#129]
when i create a new note and hit the save button no response, the page sites as it is

**Comment by jamesrascal** [comment]
This sounds similar to #102

**Comment by Baldrs** [comment]
The same on save, you must watch the requests in web inspector to ensure it is saved.

**Comment by devilx** [comment]
It's probably the same as #102, just as @jamesrascal mentioned. Closing, please follow the other issue.
