### ISSUE TITLE
when i type some words in the tags input then i focus out the tags input,my words typed cant change to be tag

### ISSUE THREAD

**Issue by billyct** [twostairs/paperwork#130]

**Comment by jamesrascal** [comment]
Hi Billct,

Are you adding a comma at the end of each tag?

**Comment by billyct** [comment]
no, i think if i focus out it can change to be a tag , may be more firendly

**Comment by devilx** [comment]
@billyct are you running the latest GIT version of Paperwork? @ponychicken seems to have fixed this in #50.

**Comment by ponychicken** [comment]
Looks like the demo hasn’t been updated yet, so they might be using that..

**Comment by ponychicken** [comment]
That seems to have been it. Issue can be closed
