### ISSUE TITLE
AngularJS Bootstrapping visible with {{ }} Tags

### ISSUE THREAD

**Issue by mappmechanic** [twostairs/paperwork#131]
{{ }} Tags are getting displayed in the view template till the time AngularJS is bootstrapped, you should find a way to delay loading initial view till the time AngularJS is not bootstrapped.
![screen shot 2015-01-28 at 11 50 06 am](https://cloud.githubusercontent.com/assets/4088925/5933261/faf360c2-a6e3-11e4-91d4-156e95366d66.png)

**Comment by Baldrs** [comment]
It just should be wrapped in ng-cloak with appropriate class inside stylesheets

https://docs.angularjs.org/api/ng/directive/ngCloak

**Comment by devilx** [comment]
This was fixed in #51 by @joshlemer. I'll check the demo-instance to see, why it's not available there yet.

**Comment by devilx** [comment]
Indeed, they're still showing up. Closing this issue, continuing in #51.
