### ISSUE TITLE
Feature request: calendar

### ISSUE THREAD

**Issue by firstrow** [twostairs/paperwork#132]
It would be nice to have calendar feature to make easier to switch between years.
For example, its good for personal journal.

**Comment by devilx** [comment]
A calendar for filtering notes sounds like a good idea. It should be only a filter, though, and not a full featured calendar component. A good example for this is the Day One App (http://dayoneapp.com/), which also uses a calendar view to filter entries.

**Comment by firstrow** [comment]
+1 dayone is good example.

**Comment by ChrisLahaye** [comment]
I am working on this, can anyone post some examples of textual date filters?

Had something in mind like:
date:2014y
date:03m2014y
date:06d

**Comment by devilx** [comment]
@ChrisLahaye maybe we should use some ISO/standardised format here? Not sure, though, as (if this could be used in the search input box later on) users might want to have different ways to enter the date, maybe in a more "humane" way. :+1: for working on it!

**Comment by pwmvx1289** [comment]
Is it about a whole new page with a calendar-based layout which lets user interact with it?
Or it's just something like a date-picker?

**Comment by devilx** [comment]
I think this should only be a widget inside the sidebar, which could be displayed or hidden, using a "View"-menue entry.

It could look like for example Sunrise calendar's picker:
![screen shot 2015-02-08 at 14 25 58](https://cloud.githubusercontent.com/assets/151967/6096660/afff742a-af9e-11e4-8816-236566a026d9.png)

**Comment by ChrisLahaye** [comment]
Will continue with this next week, any preferences for calendar libraries?

**Comment by devilx** [comment]
@ChrisLahaye cool. I'd stick with anything that work's great with AngularJS and appears to be supported for the next few years. It would be cool if it was built on top of bootstrap as well.

**Comment by Baldrs** [comment]
Okay, we now have calendar. Please file any new issues into new threads.
