### ISSUE TITLE
unable to enter equations in a note

### ISSUE THREAD

**Issue by informationmissing** [twostairs/paperwork#135]
Trying to enter math into the note, I was unable to do so. the "enter equation" box opened  but did not accept any input.

**Comment by devilx** [comment]
Looks like a bug in the CKEdtior Plugin. What browser are you using, @informationmissing?

**Comment by devilx** [comment]
@informationmissing ping?

**Comment by cale250** [comment]
I also have this issue.

I am using Google Chrome on a Chromebook.

Version 41.0.2272.76 (64-bit)
Platform 6680.58.0 (Official Build) stable-channel quawks
Firmware Google_Quawks.5216.204.6

**Comment by Liongold** [comment]
Do you get any errors in your browser's console?

On Thursday, March 5, 2015, Cale Cunningham <notifications@github.com>
wrote:

> I also have this issue.
>
> I am using Google Chrome on a Chromebook.
>
> Version 41.0.2272.76 (64-bit)
> Platform 6680.58.0 (Official Build) stable-channel quawks
> Firmware Google_Quawks.5216.204.6
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twostairs/paperwork/issues/135#issuecomment-77294667>.
>


-- 
Sincerely,
Jean Spiteri.

**Comment by cale250** [comment]
Yes, I do. Here's the error and call stack:


    Uncaught TypeError: undefined is not a function      ckeditor.js:911
    CKEDITOR.plugins.add.init.CKEDITOR.dialog.add.contents.elements.setup       ckeditor.js:537
    (anonymous function)    ckeditor.js:536 
    CKEDITOR.dialog.foreach    ckeditor.js:537 
    CKEDITOR.dialog.setupContent    ckeditor.js:912
    CKEDITOR.plugins.add.init.CKEDITOR.dialog.add.onShow    ckeditor.js:10
    i    ckeditor.js:12 
    CKEDITOR.event.CKEDITOR.event.fire    ckeditor.js:535 
    (anonymous function)     ckeditor.js:25

**Comment by Liongold** [comment]
I'll take a look at this.

**Comment by Liongold** [comment]
This issue should now be fixed. If you encounter this bug again, please open a new issue. Thanks for reporting.
