### ISSUE TITLE
Error while saving a note won't be displayed

### ISSUE THREAD

**Issue by Silberling** [twostairs/paperwork#145]
I am using mod_security. I accidentally forgot to disable it for paperwork.

Saving a note failed but I did not get any response. If I would have closed the tab in my browser the changes would have been lost and I would not have recognized it.

It might be me being blind but if there are any errors not caught, this should be an issue.

A note got created without a title and it was empty.

**Comment by FromBabylon** [comment]
Is this same as #102 ? 
I also noticed that sometimes save fails without any message. 
But I can know if a note was saved by always closing with the button just aside saving one which pop up a message with "Close without saving ? " when note wasn't saved.

**Comment by Silberling** [comment]
I'm kinda not interested if anything worked but I'd like to know if anything did NOT work. But I would just drop my own opinion and have a good usability. Getting feedback anyway would be necessary. Maybe if the save button flashes green indicates success and a error message dialog on error would be a good solution.

**Comment by devilx** [comment]
Yupp, that's a good point - but let's stick to #102, as it's basically the same idea behind. We definitely need to show the user when something completed/failed.

Setting as duplicate of #102.
