### ISSUE TITLE
Missing notifications on deleting a Notebook / Note

### ISSUE THREAD

**Issue by nikhilben** [twostairs/paperwork#146]
There is no notification after deleting a notebook or note. It would be nice to show a notification "The notebook have been deleted successfully"  or something similar after deletion.

**Comment by Liongold** [comment]
I might check this out so assigning this to me for now.

**Comment by devilx** [comment]
This is similar to #102.

**Comment by Liongold** [comment]
This should be fixed. If you encounter any other issues, please open a new issue.
