### ISSUE TITLE
Open gitter room

### ISSUE THREAD

**Issue by Baldrs** [twostairs/paperwork#148]
There is a [service][1] that serves as a chat for developers that using github. I propose to open a room for this repo, to have a nice place for the intense conversations here. It is free of charge for most of it.

[1]: https://gitter.im/

**Comment by ntnn** [comment]
Additionally it provides an [irc bridge](https://irc.gitter.im/) which is really nice.

**Comment by Liongold** [comment]
Paperwork already has an IRC channel. It's on freenode.net channel #paperwork

**Comment by Baldrs** [comment]
It is not mentioned in readme.

**Comment by joshlemer** [comment]
It is done!
https://gitter.im/twostairs/paperwork
