### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#15]
Technically, collections are possible. The thing is, that there is no way to create/edit these collections. Right now, it's impossible to move notebooks into others and by that form a new collection - because that's what collections actually are: Empty notebooks containing more notebooks.

The thing is, that collections can not contain any notes - only notebooks. So if someone would create two notebooks, fill one with notes and then "move" the second one into the former, all notes would become inaccessible. Therefor we need a clear way to create/edit collection and only allow a user to move notebooks into such.

**Comment by ntnn** [comment]
How about redefining that and saying that notebooks can contain notebooks and notes? Practically like a folder structure. That would eliminate the problems of 'collections' and also make the concept easier to grasp for users (plus that there definitely will be requests to add notes to collections).

**Comment by devilx** [comment]
@ntnn technically it's already implemented like that. A collection is nothing more than a row within the "notebooks" table, which has other rows in that very same table, that contain the row's id as "parent_id".

The thing is, that we still need to make a visual differentiation between these two types of notebooks. If we treat them like folders, users would expect to be able to stack a dozen folders underneath another, resulting in super-complex structures. Right now, I don't know of any service that allows creating a folder, inside a folder, inside a folder, inside a folder. Evernote for example only allows users to create a "Notebook Stack" which contains a bunch of notebooks - but no deeper than that.

**Comment by maxalbert** [comment]
@devilx Out of curiosity, why would you want to disallow users to stack folders if that's what they want to do? Is this for technical reasons? Disclaimer: I have not used Paperwork (or Evernote) yet, so I may be missing something obvious. But I'd think that if a user wants to use a feature in a certain way, why not allow it there are no technical limitations which make this difficult?

**Comment by Baldrs** [comment]
@maxalbert no one is disallowing it, it just currently a flat structure. It will require additional work to convert it into tree structure, additional interfaces, coding. Someday we'll do that.

**Comment by maxalbert** [comment]
I see, thanks for the clarification!

**Comment by Liongold** [comment]
Collections have now been implemented in Paperwork! This issue will now be closed. If you encounter any issues and/or have any other feedback, please open a new issue.
