### ISSUE TITLE
Refine readme

### ISSUE THREAD

**Issue by Baldrs** [twostairs/paperwork#152]
I propose to refine readme into shorter version, which states clear, what is the project, its goals and how to contact the developers. Any extended info is better to be placed in wiki(ie screenshots). 

For example, I have added [screenshots][1] page to wiki 

[1]: https://github.com/twostairs/paperwork/wiki/Screenshots

**Comment by joshlemer** [comment]
Also to be considered in any readme changes

* Exact, step-by-step instructions for how to get this project running. I have a rough draft document for this.
* mention running gulp in the setup instructions
* mention running "php artisan serve" in the setup instructions
* mention the "issue-123-name" convention in a contributing section

**Comment by devilx** [comment]
:+1: good points!

**Comment by Baldrs** [comment]
Done in #326
