### ISSUE TITLE
Unable to create New Note

### ISSUE THREAD

**Issue by swengmatt** [twostairs/paperwork#159]
I traced this down to the versions table having a field 'content_preview' which is not set, and doesn't have a default value/cannot be nullable when a new note is created.
I will create a migration and make sure it solves the unable to create a note problem.

I also wonder how many more database fields need to be nullable/given default values...

**Comment by Liongold** [comment]
I think there's a bigger problem somewhere because normally that field should be set. Can you send a screenshot of what you were posting?

**Comment by swengmatt** [comment]
The error I am getting from the response to the post is:

{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[HY000]: General error: 1364 Field 'content_preview' doesn't have a default value (SQL: insert into `versions` (`title`, `content`, `updated_at`, `created_at`) values (Untitled, , 2015-01-30 17:13:23, 2015-01-30 17:13:23))","file":"C:\\Users\\majacobs\\GitSource\\paperwork\\frontend\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php","line":625}}

**Comment by Liongold** [comment]
Can't test it right now but I think this could be a bug.

**Comment by swengmatt** [comment]
Okay, instead of changing the database schema, I went ahead and passed content_preview along with  the existing title and content parameters, and the next error I get is:

{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[HY000]: General error: 1364 Field 'umask' doesn't have a default value (SQL: insert into `note_user` (`note_id`, `user_id`) values (1, 1))","file":"C:\\Users\\majacobs\\GitSource\\paperwork\\frontend\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php","line":625}}

I will just keep trying to solve each error, and make sure that strict sql databases won't keep causing issues.

**Comment by Liongold** [comment]
@swengmatt I think there's some underlying bug which is causing this.

**Comment by swengmatt** [comment]
@Liongold It's because my mysql server is running in strict mode (which I could turn off, i suppose), which basically throws errors instead of warnings when you are trying to store a null value into a field without a default or nullable type.
The question would then become, do you want to support strict mysql databases.. this isn't the first occurrence of this type of error. See #154 and #116

**Comment by Liongold** [comment]
Oh did not think of that difference to be honest. Setting as enhancement. Thanks for your pull request as well.
