### ISSUE TITLE
Can't create new notes

### ISSUE THREAD

**Issue by OmgImAlexis** [twostairs/paperwork#164]
When I try making a new note nothing happens on screen but I get a 500 error in the console.

![500](https://cloud.githubusercontent.com/assets/6525926/5986764/5f9bec6c-a958-11e4-812c-2b2e6cfd1716.PNG)

**Comment by ntnn** [comment]
The same happens to me:
```
>update
INFO:paperworkcli:update
INFO:models:Updating notebooks and notes
INFO:pwwrapper:GET request to http://demo.paperwork.rocks/api/v1/notebooks/18 with None
INFO:pwwrapper:PUT request to http://demo.paperwork.rocks/api/v1/notebooks/18 with {"type": 0, "id": "18", "title": "dasdasdasd"}
INFO:pwwrapper:GET request to http://demo.paperwork.rocks/api/v1/notebooks/15 with None
INFO:pwwrapper:PUT request to http://demo.paperwork.rocks/api/v1/notebooks/15 with {"type": 0, "id": "15", "title": "gomorrha"}
INFO:pwwrapper:POST request to http://demo.paperwork.rocks/api/v1/notebooks/15/notes with {"content": "", "title": "something"}
ERROR:pwwrapper:HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/home/ntnn/.local/bin/paperworks", line 9, in <module>
    load_entry_point('paperworks==0.13', 'console_scripts', 'paperworks')()
  File "/home/ntnn/.local/lib/python2.7/site-packages/paperworks/paperwork.py", line 233, in main
    cmd_dict[cmd]()
  File "/home/ntnn/.local/lib/python2.7/site-packages/paperworks/paperwork.py", line 48, in update
    pw.update()
  File "/home/ntnn/.local/lib/python2.7/site-packages/paperworks/models.py", line 326, in update
    note.update()
  File "/home/ntnn/.local/lib/python2.7/site-packages/paperworks/models.py", line 173, in update
    self.id = resp[u'id']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Looks like the demo is broken currently.

**Comment by swengmatt** [comment]
This is similar to #159, which should have been fixed with merge #160. If you update your repo, it should work. Your POST to notebooks/:id/notes should contain a content_preview field. Another idea would be to start your database with strict sql set to off.

**Comment by ntnn** [comment]
@swengmatt We are both accessing demo.paperwork.rocks - @OmgImAlexis through the webpage and I through my wrapper.

That POST should include content_preview is interesting - thats not mentioned in the api, but works fine normally.

**Comment by ntnn** [comment]
```
>update
INFO:paperworkcli:update
INFO:models:Updating notebooks and notes
INFO:pwwrapper:GET request to http://demo.paperwork.rocks/api/v1/notebooks/18 with None
INFO:pwwrapper:PUT request to http://demo.paperwork.rocks/api/v1/notebooks/18 with b'{"title": "dasdasdasd", "type": 0, "id": "18"}'
INFO:pwwrapper:GET request to http://demo.paperwork.rocks/api/v1/notebooks/22 with None
INFO:pwwrapper:PUT request to http://demo.paperwork.rocks/api/v1/notebooks/22 with b'{"title": "abd", "type": 0, "id": "22"}'
INFO:pwwrapper:GET request to http://demo.paperwork.rocks/api/v1/notebooks/15 with None
INFO:pwwrapper:PUT request to http://demo.paperwork.rocks/api/v1/notebooks/15 with b'{"title": "dasddd", "type": 0, "id": "15"}'
INFO:pwwrapper:POST request to http://demo.paperwork.rocks/api/v1/notebooks/15/notes with b'{"content": "", "title": "test", "content_preview": ""}'
>
```

That indeed fixes it. Either #160 hasn't solved it or the demo isn't up to date.

**Comment by swengmatt** [comment]
The demo gets recreated every night at 3am (not sure what time zone), so any fix done today will not fix the demo until tomorrow.

**Comment by ntnn** [comment]
Ah, I didn't see that the commit was from today. Thanks for the quick response.

**Comment by devilx** [comment]
@ntnn cool, a Paperwork CLI client! Keep it up! :+1:

**Comment by ntnn** [comment]
@devilx I wrote that actually just to test the interaction with the host. I'm more inclined to have [a vim plugin](/ntnn/vim-paperwork).

**Comment by devilx** [comment]
@ntnn saw it as well, starred! Cool work. Is that working already? Maybe you could screenrecord how it looks/works? Would love to share that with the Paperwork community.

**Comment by ntnn** [comment]
It works for the most part. Creating/deleting and editing notebooks and notes already works - the bigger problem is time, because it currently syncs instantly to the remote host - and I wrote the wrapping classes a bit too heavy and sluggish. Some conditions also still have undefined behaviour.

I'm currently refactoring paperwork.py to get a better performance (maybe even adding optional threading for put, post and delete requests) and then I'll adjust vim-paperwork to the changes.

I'd guess I'll have a 'presentable' version of vim-paperwork sometime tonight (midnight GMT approx.).

**Comment by ntnn** [comment]
@devilx Took a bit longer, but it works fine now and I added a screenshot/link to asciinema.org. Also this ticket can be closed, nor?

**Comment by OmgImAlexis** [comment]
@ntnn I'm guessing this should have been fixed in an earlier commit. I'm still using the demo site and it's still broken on there. I can't create any notes at all.

**Comment by ntnn** [comment]
@OmgImAlexis Oh, you're right! Sorry, I thought I created a note through the demo site earlier.

**Comment by devilx** [comment]
This issue should have been fixed by now.
