### ISSUE TITLE
Fix notebooks tree to not allow super long names to break the UI

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#166]
@joshlemer posted a screenshot that made me think we could use some checks or CSS magic in order to avoid super long notebook names to break the UI:

![screenshot from 2015-01-30 18 22 23](https://cloud.githubusercontent.com/assets/5122903/5985822/d7a0fa0a-a8ad-11e4-8625-55b8597dd678.png)

**Comment by lixonic** [comment]
`word-break: break-all`  

`.tree li.tree-notebook span{ word-break: break-all;}`

**Comment by lixonic** [comment]
and control the overflow by giving a 200px width for span
`.tree li.tree-notebook span{ 
text-overflow: ellipsis;
white-space: nowrap;
overflow: hidden;
width: 200px;
}`

**Comment by devilx** [comment]
@lixonic thank you. :-) Why not sending a pull-request, so the credit for this goes to you?

**Comment by lixonic** [comment]
I never knew that there were several tweaks for compiling :trollface:  

https://github.com/lixonic/paperwork/compare/twostairs:master...master

**Comment by joshlemer** [comment]
Oh hey guys, I actually fixed that yesterday and the pull request was merged after the screenshot was taken, try running gulp on master branch and you'll see that the notebook titles truncate.

**Comment by joshlemer** [comment]
See #161

**Comment by lixonic** [comment]
:sweat_smile:

**Comment by joshlemer** [comment]
Can we close this issue?

**Comment by devilx** [comment]
I think we can.
