### ISSUE TITLE
Scroller not functional for the index

### ISSUE THREAD

**Issue by rishabhranawat** [twostairs/paperwork#176]
Respected Developer, 

The scroller is not working for the second vertical devision of the first user page. It is the index division of the website.

**Comment by Baldrs** [comment]
Can you clarify? What is the second division of the first user page? Can you take a screenshot?

**Comment by devilx** [comment]
I think he means the notes list, maybe. Not sure though, as this text looks like it was send through google's translate. (no offence!)

**Comment by Baldrs** [comment]
There is scroll, chrome 40 linux
![2015-02-03-080800_1680x1050_scrot](https://cloud.githubusercontent.com/assets/814651/6015302/f1d24ca0-ab7b-11e4-91fa-27cbf53215df.png)
There is scroll in firefox 35
![2015-02-03-081933_1680x1050_scrot](https://cloud.githubusercontent.com/assets/814651/6015475/7ccfd416-ab7d-11e4-91ae-4b5832474d30.png)

**Comment by devilx** [comment]
As @rishabhranawat didn't comment on this for the last six days, I'm going to close it. Feel free to re-open if the issue persist.
