### ISSUE TITLE
No redirect on session timeout

### ISSUE THREAD

**Issue by saibot2013** [twostairs/paperwork#180]
Currently there is happing nothing when session was timedout. Only the console displays a failed request to api - maybe we should add an redirect to login-page here.

**Comment by Liongold** [comment]
Screenshot please?

**Comment by saibot2013** [comment]
![Screenshot after session-timeout and clicking "new note"](https://cloud.githubusercontent.com/assets/8065624/6003799/c3ea36ae-aafe-11e4-9acd-b01763198223.png)

**Comment by Liongold** [comment]
If you redirect, are you be taken to the login form?

**Comment by saibot2013** [comment]
![sessiontimeout](https://cloud.githubusercontent.com/assets/8065624/6004735/2fe810a0-ab05-11e4-8f8b-cde4554f3133.gif)
Every link which is handled by javascript seems to do nothing. A real redirect on /settings for example or a page reload will show the login page. It's also on demo site, not only on my personal instance. I am using the current Firefox on a linux machine.

**Comment by Liongold** [comment]
Thanks for the bug report.

**Comment by devilx** [comment]
Weird. I remember, that I tried to implement this feature before (https://github.com/twostairs/paperwork/blob/master/frontend/app/js/paperwork/net/net.service.js#L11) but it looks like it still doesn't work properly.

**Comment by saibot2013** [comment]
It looks like you cannot handle status 302 by javascript/angular because the browser has to do it. There seems to be actually no possibility to handle this. I think there are two options how to manage the problem:
* on ui-side: parsing the response (on every api-call) and check if the given data is a valid json-string. That would be nice, because the api currently returns json only. But on the other hand there would be problems, when you (maybe in future) use some other string formats.
* on server-side: do not redirect but throw a 401 Unauthorized. This could be the more useful method because in my opinion the api should not redirect - even if you think about some future-apps it would be easier to handle a 401 response instead of parsing the given result data

I think this are the two options which make sense. What do you think?

**Comment by saibot2013** [comment]
Is it still open? For me it is working in chrome, firefox and safari.
