### ISSUE TITLE
paperwork.min.js syntax error

### ISSUE THREAD

**Issue by joshlemer** [twostairs/paperwork#191]
Load the master branch and run gulp to produce the minified JS.

Get this error:

https://docs.angularjs.org/error/$injector/modulerr?p0=paperworkNotes&p1=Error:%20%5B$injector:nomod%5D%20Module%20%27paperworkNotes%27%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp:%2F%2Ferrors.angularjs.org%2F1.2.21%2F$injector%2Fnomod%3Fp0%3DpaperworkNotes%0A%20%20%20%20at%20http:%2F%2Flocalhost:8000%2Fjs%2Fangular.min.js:79:12%0A%20%20%20%20at%20http:%2F%2Flocalhost:8000%2Fjs%2Fangular.min.js:1669:17%0A%20%20%20%20at%20ensure%20(http:%2F%2Flocalhost:8000%2Fjs%2Fangular.min.js:1593:38)%0A%20%20%20%20at%20module%20(http:%2F%2Flocalhost:8000%2Fjs%2Fangular.min.js:1667:14)%0A%20%20%20%20at%20http:%2F%2Flocalhost:8000%2Fjs%2Fangular.min.js:3853:22%0A%20%20%20%20at%20forEach%20(http:%2F%2Flocalhost:8000%2Fjs%2Fangular.min.js:326:18)%0A%20%20%20%20at%20loadModules%20(http:%2F%2Flocalhost:8000%2Fjs%2Fangular.min.js:3847:5)%0A%20%20%20%20at%20createInjector%20(http:%2F%2Flocalhost:8000%2Fjs%2Fangular.min.js:3787:11)%0A%20%20%20%20at%20doBootstrap%20(http:%2F%2Flocalhost:8000%2Fjs%2Fangular.min.js:1436:20)%0A%20%20%20%20at%20bootstrap%20(http:%2F%2Flocalhost:8000%2Fjs%2Fangular.min.js:1451:12

 from Angular, which is caused by a syntax error somehow in paperwork.min.js at line 556:

Uncaught SyntaxError: Unexpected token function

These are the lines in question

angular.module('paperworkNotes').controller('NotesEditController',
  ['$scope', '$rootScope', '$location', '$routeParams', 'NotesService', 'paperworkApi'
    function($scope, $rootScope, $location, $routeParams, notesService, paperworkApi) {
      window.onCkeditChangeFunction = function() {
        // FIXME jQuery un angular is anti-pattern
        // Let's access our $rootScope from within jQuery (this)

As you can see, just before "function" on the third line, there should be a comma.

**Comment by devilx** [comment]
Just one additional comment to this: We should consider adding some linting for the JS code to Travis (if that's supported), in order to catch such errors before deploying.

**Comment by Baldrs** [comment]
`jslint`/`jshint` are simply `npm` packages and `php_codesniffer` is a composer package. In travis logs I saw both `composer` and `npm` present, so I think it is not very hard to add some script running the checks against the code.

**Comment by pwmvx1289** [comment]
@Baldrs @devilx This is a nice js lint npm package https://www.npmjs.com/package/jscs

**Comment by devilx** [comment]
@pwmvx1289 thanks! Looks like it's even getting along with Gulp: http://isimmons.github.io/

What do you guys think, @Baldrs @joshlemer @Liongold? Should we integrate JSCS into our Gulp or rather use a composer package?

**Comment by Baldrs** [comment]
Never heard of jslint composer package :) I think we should, and also add php codesniffer hook to check for coding standards. And use this checking in our IDE's of choice. And don't accept PRs violating them.

**Comment by Liongold** [comment]
Don't have any opinion on this. Just want to make sure that with this sudden increase in contributors and commits, we still not build barriers for committing by new developers.
