### ISSUE TITLE
JS Linting within Travis build

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#198]
As mentioned by @Baldrs within https://github.com/twostairs/paperwork/issues/191#issuecomment-72751224 we should add some linting functionality to our Travis builds.

**Comment by Liongold** [comment]
Is this open?

**Comment by devilx** [comment]
@Liongold I haven't seen anyone adding JSLint so far, nor did I. So I guess it is. :-)

**Comment by Liongold** [comment]
@devilx @joshlemer What did the mentioned above commit do then? From what I've read JSLint and JSHint do the same purpose.

**Comment by joshlemer** [comment]
@Liongold I had a PR up a few weeks back that added JSHinting to the gulp builds but it never got accepted so I took it down. I could definitely add it again.

**Comment by Liongold** [comment]
@joshlemer Is this issue totally fixed now?

**Comment by joshlemer** [comment]
Yep

**Comment by Liongold** [comment]
Ok, I'm closing it then.
