### ISSUE TITLE
Toggle visibility of the Note List

### ISSUE THREAD

**Issue by jasondavis** [twostairs/paperwork#207]
Has it been mentioned yet to possibly allow the visibility of the Notes List to be toggled in and out of view?  When hidden it would make the Note view wider for a wider view of a note?

In Evernote you can go to View menu and check/uncheck "Note List" to make it visible or not,  When hidden you can view a wider view of the note.

Ideally if such a feature was added, I think it would be good to have some sort of quick access button but also a keyboard shortcut to show/hide the list view which would simply be hiding it on the frontend using CSS.

A simple button to toggle it in and out would be good idea maybe?  Thoughts?

**Comment by pwmvx1289** [comment]
I've also been thinking about it to add a small arrow on the list that serves as a show/hide button.
Current interface may have a viewing space for notes that have large amount of content.

**Comment by devilx** [comment]
I'm fine with the idea. Right now, it could be hidden by calling SidebarNotesController.isVisible(). This is the function being used for expanding the note editing to full-width.

**Comment by Liongold** [comment]
@pwmvx1289 Interested in doing this?

**Comment by pwmvx1289** [comment]
@Liongold I'm very interested in it but I'm not very sure whether I could handle it.

**Comment by Liongold** [comment]
If you want to, I'll try to give you some pointers about this.

On Thursday, February 12, 2015, pwmvx1289 <notifications@github.com> wrote:

> @Liongold <https://github.com/Liongold> I'm very interested in it but I'm
> not very sure whether I could handle it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twostairs/paperwork/issues/207#issuecomment-74070871>.
>


-- 
Sincerely,
Jean Spiteri.

**Comment by pwmvx1289** [comment]
Is this function already implemented by others?

**Comment by Liongold** [comment]
No, I don't think so. If it was, this bug would be closed I guess.

**Comment by devilx** [comment]
Not yet, nope. So it's free to do, althought I'm not sure whether @7brend7 might have started revamping the whole web-ui or not. At least he suggested some nice dribbble-mockup recently.

**Comment by pwmvx1289** [comment]
@devilx Where may I find the new mockups?

**Comment by Liongold** [comment]
This is the code used for the theme:
https://github.com/7brend7/paperwork-theme and a non-working prototype:
http://7brend7.github.io/paperwork-theme/.

-- 
Sincerely,
Jean Spiteri.

**Comment by devilx** [comment]
Maybe you @pwmvx1289 and @7brend7 would want to team-up on this topic?

**Comment by 7brend7** [comment]
I've added button near the logo which toggle first column (notebooks and tags block). It's ok for me that column with notes list is always visible especially if main content will take full browser width.

**Comment by pwmvx1289** [comment]
Perhaps we could have a new board to discuss new UI ideas?

**Comment by devilx** [comment]
@pwmvx1289 there is paperwork-dev@googlegroups.com and also Gitter. Wouldn't want to spread information across yet another platform.

**Comment by pwmvx1289** [comment]
Ok I'll put put things on Google Group when necessary. (Didn't know there has been one)
