### ISSUE TITLE
Upload of file through API works, but returns 500

### ISSUE THREAD

**Issue by ntnn** [twostairs/paperwork#214]
When uploading a file through the API the file goes through, but the response is [this page](https://gist.github.com/ntnn/40d1f70561c48f1c1044) (viewable [here](https://ntnn.github.io/paperwork_file_upload_error.html)) and a 500 error code.

Below is the output of the terminal client showing the process, a double dash signals an attachment, a single dash a note:
```shell
>ls
INFO:__main__:ls
notebook
- note title2
-- test
>upload /home/ntnn/temp/pips to note title2
INFO:__main__:upload /home/ntnn/temp/pips to note title2
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): demo.paperwork.rocks
INFO:paperworks.wrapper:<Response [500]> http://demo.paperwork.rocks/api/v1/notebooks/2/notes/2/versions/0/attachments
>update
[Verbose ouput about updating]
>ls
INFO:__main__:ls
notebook
- note title2
-- test
-- pips
>exit
```

**Comment by devilx** [comment]
@ntnn do you upload as regular form-submission or JSON?

**Comment by ntnn** [comment]
Regular form-submission with the [requests library](http://docs.python-requests.org/en/latest/user/quickstart/#post-a-multipart-encoded-file), implemented [here](https://github.com/ntnn/paperwork.py/blob/master/paperworks/wrapper.py#L422-437).

**Comment by devilx** [comment]
@ntnn okay, if it was pure JSON there was a big chance for it to not work, as nobody ever tested it. But form-submissions should work, as the web-ui uses the same. Does uploading through the web-ui work? Could you get the request body of the 500 error being display?

**Comment by ntnn** [comment]
Uploading through the webui works fine.

Also I'm checking if requests is actually using multipart/form-data to upload files or if it is using json - I just noticed that it doesn't work at all (with the same response) if I add 'multipart/form-data` as  a header to the request.

**Comment by ntnn** [comment]
[It is definitely using multipart/form-data.](https://github.com/kennethreitz/requests/blob/master/requests/models.py#L102-L109)

**Comment by devilx** [comment]
@ntnn as I requested before: It would be great to see the response body.

**Comment by ntnn** [comment]
The response body is actually the page I linked in the first comment.

**Comment by devilx** [comment]
@ntnn sorry, overseen that. Please pull latest develop and try with that.

**Comment by ntnn** [comment]
@devilx No worries.

I set paperwork up on my local machine to test it - it works.

```shell
>upload /home/ntnn/temp/pips to note
INFO:__main__:upload /home/ntnn/temp/pips to note
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:paperworks.wrapper:<Response [200]> http://127.0.0.1/api/v1/notebooks/2/notes/2/versions/0/attachments
```
Thanks for the fast response.

But I've directly got something else - uploading an image gets [this error](https://ntnn.github.io/paperwork_file_upload_error2.html) - maybe there is a step in the wiki missing?

**Comment by devilx** [comment]
@ntnn indeed, the Wiki does not contain every detail yet. For Paperwork to be able to scale uploaded images (generating thumbnails) imagemagick is needed. Also, for Paperwork's OCR capabilities (e.g. when you upload a photo of a written document, Paperwork tries to parse the text out of it) to work, you will need tesseract (+ language files) installed on your system.

I've created a new issue for fixing the missing documentation (#217).

**Comment by ntnn** [comment]
@devilx Ah, that makes sense - thanks for the quick fix!
