### ISSUE TITLE
Fix Docker deployment (or remove it)

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#215]
Due to the recent changes in LESS transformation and JS minification, the current Docker deployment doesn't work any more. Someone who's into this topic is needed to fix this issue. Either this, or we'll need to remove it completely.

**Comment by Baldrs** [comment]
Seems we just need to extend Dockerfile with what I have written in readme - gulp build part. For this I will add nodejs to container and then build step for gulp.

**Comment by Baldrs** [comment]
I think we must consider to reconfigure it into a persistent setup at least for database part.
