### ISSUE TITLE
Install Paperwork in subpath

### ISSUE THREAD

**Issue by oompf** [twostairs/paperwork#218]
I think it would be nice if you could configure Paperwork to be installed in a subpath of a webserver.
I expierienced problems with loading ressources.

**Comment by devilx** [comment]
Please search the closed issues here for a more in-depth information about this. Also see https://github.com/twostairs/paperwork#can-i-run-paperwork-on-a-shared-host-environment-where-im-not-able-to-set-frontendpublic-as-document-root
