### ISSUE TITLE
Fix Lato fonts

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#225]
The webfont files currently available in Paperwork seem to be completely broken in Firefox (and IE?) while Chrome renders them without any issue. I've downloaded them from the official Lato website.

Maybe someone could point me to another source, where I could receive the Lato webfonts from, in order to re-include them into Paperwork?

**Comment by Baldrs** [comment]
On linux they look well, what do you mean by broken? Are they broken on [google fonts][https://www.google.com/fonts#UsePlace:use/Collection:Lato] for you?

**Comment by devilx** [comment]
@Baldrs how did you test? Because right now, Lato is not being used because of these issues. Google Fonts looked great on every computer I tested them on. But the font files that (still are) included in Paperwork simply did not work on Windows + Firefox. I believe that Google uses other font files than we do / are downloadable from http://www.latofonts.com/lato-free-fonts/

The website says:

> The older ver­sion (1.0) of the Lato font fam­ily is avail­able on Google Fonts. Using this ser­vice, you can eas­ily incor­po­rate the Lato fonts into your web­site. (In fact, this very web­site uses the Lato fonts served by Google Fonts). Soon, the new 2.0 ver­sion will be avail­able on Google Fonts as well.

Back then I downloaded the 2.0 version, which I included into Paperwork. Now, I'm not sure whether Google Fonts already switched to 2.0 and even whether they use own built webfonts from the TTFs – I used the webfonts archive provided on the Lato website.

**Comment by devilx** [comment]
@joshlemer @Baldrs @Liongold could anyone of you guys, who does **not** have the Lato font installed on their local system check out the commit above and test, whether the webfont works in a number of browsers please?

**Comment by joshlemer** [comment]
Well I'm on Linux Mint and I don't see anything out of the ordinary in Firefox of Chromium. I don't think I have lato font installed unless it gets installed at some point in the build process of Paperwork..

**Comment by devilx** [comment]
@joshlemer it won't. Could you please check /usr/share/fonts, /usr/local/share/fonts and ~/.fonts in order to make sure that Lato is definitely not installed on your Linux machine?

**Comment by Baldrs** [comment]
@devilx my gentoo install do not possess any lato fonts at all, even no package for it. The default fonts look somewhat ugly. Font-size is somewhat small, I'd prefer it to be 0.1-0.2 em larger

**Comment by Baldrs** [comment]
@devilx regarding the testing, I just have opened paperwork with lato embedded in both firefox/chrome and saw that all was ok. Then I opened the google fonts page and everything was ok too. I suspect that it is somehow related to windows.

**Comment by devilx** [comment]
Okay, well then let's close this issue for now, if for both of you the Lato font that's being delivered as webfont now works.
