### ISSUE TITLE
content of index.php shown instead of application

### ISSUE THREAD

**Issue by JamborJan** [twostairs/paperwork#226]
After having followed your setup instructions I get this when I want to open the instance:

![bildschirmfoto 2015-02-08 um 17 25 08](https://cloud.githubusercontent.com/assets/7508960/6097268/bdd94512-afb7-11e4-9ddb-1f7edea0b3f2.png)

Seems that there is something missing, a component not installed or configured of Apacha / PHP or something like this. Any ideas where this comes from?

JJ

**Comment by Baldrs** [comment]
You definitely need to double-check **Apache** config because it does not have php installed or enabled. Try `a2enmod php5` as root and then restart apache web server.

**Comment by JamborJan** [comment]
okay that was weird, I don't know why it happened but ```libapache2-mod-php5``` was missing. Having this installed of course helped with the issue.

Sorry for bothering. 

JJ
