### ISSUE TITLE
Running paperwork with sqlite

### ISSUE THREAD

**Issue by JamborJan** [twostairs/paperwork#244]
I have seen in this file https://github.com/twostairs/paperwork/blob/0b5f72581ca6ff394d3288a044a281bea7a3f588/frontend/app/config/database.php

That sqlite is a supported / soon to be supported database.

I have played a bit around. And the init process to setup the database ```php artisan migrate```seems to start but then runs in an error:

```
[Illuminate\Database\QueryException]
SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: languages.created_at (SQL: insert into "languages" ("language_code") values (afr))
```
and
```
[PDOException]
SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: languages.created_at
```
I assume the init script here here: https://github.com/twostairs/paperwork/blob/master/frontend/app/database/migrations/2014_07_22_194050_initialize.php
is not 100% compatible or tested. Now I tried to check the database myself and wanted to open the database file in ```paperwork/frontend/app/database/production.sqlite``` but it seems to be encrypted:

```
sqlite production.sqlite 
Unable to open database "production.sqlite": file is encrypted or is not a database
```

I was not able to find anything about encrypting the database besides this here: https://github.com/twostairs/paperwork/blob/faa4f281558267489888079bf4f86cfb715786dc/frontend/app/config/queue.php

Changing the flag to "false" doesn't help. 

Any ides / help?

**Comment by Baldrs** [comment]
These lines are from default laravel configuration file and the compatibility have never been tested or migrations considered sqlite-compatible.

**Comment by JamborJan** [comment]
Thats fine, my question now would be how can I disable the database encryption to do the sqlite compatibility check and testing? Is this something you can answer or rather the guys from laravel?

JJ

**Comment by devilx** [comment]
@JamborJan I think it's rather broken than encrypted. You probably shouldn't take that error too literally. I believe, that due to the errors your SQLite database wasn't created successfully and therefor you receive this error.

Honestly, nobody tested SQLite compatibility so far. Since Laravel's QueryBuilder/Eloquent doesn't yet provide all the abstraction needed by Paperwork, I doubt that the database will run on anything but a MariaDB/MySQL.
