### ISSUE TITLE
Prebuilt Package, anyone? Please.

### ISSUE THREAD

**Issue by sheafferusa** [twostairs/paperwork#245]
Hello! Amazing Work! :)
I was just looking for a prebuilt package of the application. Could someone here, please provide me a prebuilt package so as to enable me to test-drive it quickly on my own servers? 

Thanks!

**Comment by Baldrs** [comment]
[Grab it](https://github.com/twostairs/paperwork/releases/download/snapshot-9f0655b/paperwork-snapshot-9f0655b.zip)

**Comment by sheafferusa** [comment]
Thank you so much!

**Comment by Berndinox** [comment]
+1 Thanks!
