### ISSUE TITLE
Can't upload attachments

### ISSUE THREAD

**Issue by doc-jay** [twostairs/paperwork#252]
Just did a clean install with mysql community server.  I can log into the site, create an account, create notes, tags.  I cannot though, upload an attachment.  I tries very briefly, but then turns into a 'red yeild sign' and then goes away.  There is no sign of an attachment left, except to start over again with the attachment.  

Both of the attachment and attachment_version tables are currently empty.

If I can post anything for this issue to help troubleshoot, please let me know.

**Comment by ChrisLahaye** [comment]
Does the user that is running the webserver (usually www-data) has write permissions in the frontend/app/storage/attachments folder?

**Comment by doc-jay** [comment]
the user is 'nginx' and the permissions were '755' for the whole '/var/www/html/paperwork' folder.  I changed it to '777' for '/var/www/html/paperwork/frontend/app/storage/', but it had no effect.  One thing I noticed is that while I am on the 'edit note' area, if I hit 'F5' to refresh myscreen, I end up with three boxes to the right side under the attachment area.  They read 'UPLOAD' 'CANCEL' 'REMOVE'

**Comment by doc-jay** [comment]
just saw this in the 'laravel.log'....
Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[HY000]: General error: 1364 Field 'content' doesn't have a default value (SQL: insert into `attachments` (`filename`, `fileextension`, `mimetype`, `filesize`, `updated_at`, `created_at`) values (cfindrq.xsl, xsl, text/plain, 2270, 2015-02-19 22:21:20, 2015-02-19 22:21:20))' in /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625

**Comment by doc-jay** [comment]
I got attachments to work in mysql community release.  Here is what I did.

Edit sql mode and remove 'STRICT_TRANS_TABLES' Save it.

**Comment by Liongold** [comment]
@doc-jay You're using SQL Strict then?

**Comment by Liongold** [comment]
Try uploading an attachment without changing any SQL configuration, now please? I made a commit which should fix the error.

**Comment by doc-jay** [comment]
thanks, I'll try it out.  Yes, I was using SQL Strict.  Didn't know it was default with mysql community as apparently its not with mariadb.  Is there an easy way to update paperwork?  I'll do some reading.

thanks

**Comment by Liongold** [comment]
Try with git pull. There should be some info in the README.
>
>

-- 
Sincerely,
Jean Spiteri.

**Comment by devilx** [comment]
Yeah, as @Liongold mentioned, a simple git pull should work for updating the code-base. Make sure you run the artisan database migrations and rebuild the gulp-stuff as well after upgrading.

However, the actual issue here was found right? I'm going to close now. If there's anything else regarding this issue, feel free to re-open.
