### ISSUE TITLE
Option for a Right-Click menu

### ISSUE THREAD

**Issue by jamesrascal** [twostairs/paperwork#258]
I am currently using paperwork as a chrome "application", it would be handy if paperwork had an option to enable a right-click context menu to edit, delete, share, etc.

**Comment by Liongold** [comment]
Duplicate of #24?

On Tuesday, February 24, 2015, jamesrascal <notifications@github.com> wrote:

> I am currently using paperwork as a chrome "application", it would be
> handy if paperwork had an option to enable a right-click context menu to
> edit, delete, share, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twostairs/paperwork/issues/258>.
>


-- 
Sincerely,
Jean Spiteri.

**Comment by jamesrascal** [comment]
Opps duplicate of #24 in deed.
