### ISSUE TITLE
API for sharing notebooks to other Paperwork-users

### ISSUE THREAD

**Issue by mrusme** [twostairs/paperwork#26]
Build APIs that allow sharing of notebooks with other Paperwork-users. The database layout is prepared for this feature and allows multiple many-to-many relations from notebooks to users, containing an "umask" column as well, which defines the users permissions on the related notebook. The values are identical to unix' chmod-values, with read adding 4, write adding 2 and ownership ("execute" in unix) adding 1 - resulting in the highest value of 7. For this purpose a tinyInt variable is being used, although a binary one (unsupported by Laravel) would have fit better.

However, the person creating and sharing a notebook would always have the umask set to 7, while invited people would be getting either 6 (read & write) or 4 (read only). I don't think it'll make sense to allow multiple notebook owners (7).

**Comment by anlutro** [comment]
Your [welcome note seems to imply that this is currently possible](https://github.com/twostairs/paperwork/blob/59bcad74f39249eb3ffb40a44e2193c29f9415e1/frontend/app/lang/en/notebooks.php#L30-L32), when it's not.

**Comment by Liongold** [comment]
@anlutro Not everything mentioned in the Welcome note has been implemented yet since the note has been written with a set of features in mind. Once we are closer to an official release, we'll take care of updating it to fit the feature-set available.

**Comment by clemlaf** [comment]
This issue can be closed since #386

**Comment by Liongold** [comment]
As per the previous comment, this issue will be closed. If anyone has any problems with this feature, please open a new issue.
