### ISSUE TITLE
Filtering by date (selecting a calendar day) disables filtering by other dates.

### ISSUE THREAD

**Issue by joshlemer** [twostairs/paperwork#260]
If you select a day in the calendar on the left menu, the other dates that were previously bold to show there are notes from those days become disabled.

**Comment by Baldrs** [comment]
@joshlemer author of original calendar promised to fix this this weekend

**Comment by ChrisLahaye** [comment]
"But I don't think he will", I feel so appreciated :smiley:. Will fix this tomorrow (Saturday).

@Baldrs: Would be nice if you could be active at Gitter tomorrow for in case I need any help ;)

**Comment by Baldrs** [comment]
@ChrisLahaye I'll try, but it will be near 20:00 GMT and no earlier.

**Comment by Baldrs** [comment]
That's been fixed
