### ISSUE TITLE
translations for note_history and share

### ISSUE THREAD

**Issue by joshlemer** [twostairs/paperwork#267]
Due to #263 we will need translations for:

'note_history' => 'Note History'
and
'share' => 'Share'

**Comment by joshlemer** [comment]
I thought I'd go ahead and notify some of the must recent translation helpers in case they wanted to help out again :) (just tell me if you don't want to be bothered again) 

@enedil (Polish)
@baldrs (Russian/Ukrainian)
@haroenv (dutch)
@janisz (Polish)
@dexafree (Spanish)
@mzch (Japanese)
@cfj (Swedish)

**Comment by Haroenv** [comment]
I'm on it

**Comment by dexafree** [comment]
Will do soon (tonight/tomorrow) :+1:

**Comment by mzch** [comment]
Hi,

Count on it. :)

**Comment by janisz** [comment]
Done #270

**Comment by Baldrs** [comment]
I think @devilx may update the origin files on transifex, #269 is incomplete before they are added. I have no access to push updated english files.

**Comment by dexafree** [comment]
Updated spanish translations
https://github.com/twostairs/paperwork/pull/271

**Comment by cfj** [comment]
Done 277

**Comment by Baldrs** [comment]
Seems like this is done, closing.
