### ISSUE TITLE
Waiting cursor

### ISSUE THREAD

**Issue by AlexIs72** [twostairs/paperwork#288]
Need to set waiting cursor (hourglass) and blocking page actions on long-time operations (create notebooks/notes, save changes, etc)

**Comment by wongalvis** [comment]
An alternative method would be adding an overlay with a loading logo. Which one do you guys think is better?

**Comment by Baldrs** [comment]
I think it is better to block control that fires an action and display some loader image. Splashing black thing on any action is easier to implement, but it is dreadfully annoying.

**Comment by Liongold** [comment]
I have added a branch for this if anyone wants to test it out. It display a slim top progress bar. It currently uses an external library but am undecided on whether to keep the library. Any feedback is welcome. The branch is issue-288-feature.

**Comment by Liongold** [comment]
This issues has been fixed. If you encounter any new issues, please open a new issue report.
