### ISSUE TITLE
Can't register new users then log in on develop

### ISSUE THREAD

**Issue by narcolepticsnowman** [twostairs/paperwork#294]
merged upstream/develop and refreshed the database with php artisan migrate:refresh
![paperwork_reset](https://cloud.githubusercontent.com/assets/5445491/6722534/2b544ca2-cda1-11e4-8f7b-3d00b66ece4d.JPG)

Login page loads fine, registration page loads fine.

Filled out the registration and clicked sign up, got this error:
![registration_error](https://cloud.githubusercontent.com/assets/5445491/6722542/6ac45ce2-cda1-11e4-948c-71dab1d479f2.JPG)

went back to the login page, tried to log in with the user I signed up with, and got: 
![login_after_register_error](https://cloud.githubusercontent.com/assets/5445491/6722552/8598fcb2-cda1-11e4-8635-151bb4fe7542.JPG)

Went back to root context "/" and page loads, but no welcome note, and no ability to create/edit notes:

![no_edit](https://cloud.githubusercontent.com/assets/5445491/6722578/ddbf754c-cda1-11e4-9512-ce9568e13a32.JPG)
![no_new_notes](https://cloud.githubusercontent.com/assets/5445491/6722579/df60de0e-cda1-11e4-80af-fe6b6b44ff44.JPG)

**Comment by Liongold** [comment]
This issue should now be fixed. If you encounter this issue again, please open a new bug report. Thanks for your contribution.
