### ISSUE TITLE
Improvement capturing notes process: add and save notes

### ISSUE THREAD

**Issue by JamborJan** [twostairs/paperwork#298]
It would be great to have a "new note" button directly on the UI which creates a new note in the current selected notebook or a default notebook. I find it quite odd to have to go to the file menu to create a new note which is not possible if no notebook is selected. From my perspective capturing must be super quick and easy to get important quick ideas out of my mind in the note app.

Saving a note could also be improved by e.g. putting a save & close button on the bottom or top of the screen where they are fixed. In the current layout you have always to scroll back on top, first need to hit save and than close. Too many steps to be quick from my point of view.

If you like I can try to implement / mockup my ideas here. Let me know.

**Comment by kentonv** [comment]
FWIW, I also stumbled over this when trying out Paperwork. I agree having a prominent "new note" button would be a great change.

**Comment by Liongold** [comment]
A pull request has been opened with a New note button added to the notes list.

**Comment by Liongold** [comment]
This pull request has now been merged. There already exists an issue about Save & Close button. Thus, I'll close this issue. If you encounter any new issues, please open a new issue. Thanks for your feedback.
