### ISSUE TITLE
i18n / Translations

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#30]
It would be cool to have Paperwork translated in different languages. i18n functionalities are already available, we only need people who could translate the files contained in app/lang/<language-code>/*.php into other languages.

**Comment by brunobatista** [comment]
:+1:

**Comment by devilx** [comment]
As suggested, we are now using https://www.transifex.com/projects/p/paperwork for managing translations.

**Comment by devilx** [comment]
As this became a continuous process, I will close the issue now. As soon as translations are faulty/missing, people will open up new issues.
