### ISSUE TITLE
Left indented form

### ISSUE THREAD

**Issue by Liongold** [twostairs/paperwork#300]
The Edit form is intended to the left because there's a left margin. It could be related to the new sidebar collapse switch.

**Comment by narcolepticsnowman** [comment]
Confirmed on my machine. 
![edit_indented](https://cloud.githubusercontent.com/assets/5445491/6771495/2012ed2e-d0a5-11e4-9da4-a63c3484d9bc.JPG)

I'll publish a fix in just a minute.

**Comment by Liongold** [comment]
Is this fixed?
