### ISSUE TITLE
PHP fatal error upon upgrading

### ISSUE THREAD

**Issue by wongalvis** [twostairs/paperwork#301]
After running git pull, I switched to frontend and ran php artisan migrate.
Here's what I get:
PHP Fatal error:  Class 'Paperwork\EloquentLdapConnectorServiceProvider' not found in /home/username/Web/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php
 on line 157
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Paperwork\\EloquentLdapConnectorServiceProvider' not found","file":"\/home\/username\/Web\/paperwork\/
frontend\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/ProviderRepository.php","line":157}}

When I try to visit the index page it doesn't load and shows the same message too. How could I fix that?

**Comment by Liongold** [comment]
It has to do with a pull request recently merged to include support for LDAP authentication. I'm very sorry for any disruption this may cause and promise that a solution will be found soon.

**Comment by Liongold** [comment]
You can fix this issue by running `composer dump-autoload`. Run it and everything should work well again.

**Comment by Liongold** [comment]
I think this issue should be left open at least for now so that people can see it before submitting a new issue.

**Comment by wongalvis** [comment]
Running composer dump-autoload solved the issue. Thx.

**Comment by wongalvis** [comment]
Is this issue associated with the current related to the above error mentioned?
![2015-03-22 21_15_48-paperwork](https://cloud.githubusercontent.com/assets/6073063/6769493/be361bd8-d0d8-11e4-94c2-78d636a03246.png)

**Comment by Liongold** [comment]
I'm not sure but I don't think so. However, you can click on the sidebar links right?

**Comment by wongalvis** [comment]
They're clickable. The "Welcome" note isn't appearing upon log in as before, when I clicked "Welcome" notebook, then a tag, then click the tag again to uncheck it, this issue appears.

**Comment by wongalvis** [comment]
Sorry the issue is actually appearing whenever a tag is selected.

**Comment by Liongold** [comment]
OK, that's better. Could you open a new issue? I don't think it has to do with this one. Also, could you include a screenshot of your browser console and/or network tab, please?

**Comment by Baldrs** [comment]
`composer dump-autoload` is a must after any pull into a repo already containing installed composer files

**Comment by wongalvis** [comment]
@Baldrs I've added the text but not 100% sure whether it's accurate and informative enough. https://github.com/twostairs/paperwork/pull/307

**Comment by Baldrs** [comment]
@wongalvis as of composer update autoloading, it is, but we must add some additional steps too, because npm and bower packages may be installed. I've been thinking of writing an artisan command to    reduce amount of steps required as well.
