### ISSUE TITLE
Find a beautiful, responsive WordPress theme for http://paperwork.rocks

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#31]
~~Actually it doesn't necessarily need to be a GitHub page - I could set up a WordPress or whatever, so we could build the new http://paperwork.rocks page on there. We just need some nice-looking theme (maybe similar to Paperwork's, even though it's not a final theme).~~

**Comment by devilx** [comment]
I've set up a WordPress and currently [looking for a theme donor](https://twitter.com/paperworkrocks/status/552206265418776576), who'd like to provide Paperwork with a cool WordPress Theme for free, in return for logo/sponsoring placement on paperwork.rocks. If anyone is into WordPress theming, I'd love to hear from you!

**Comment by cweagans** [comment]
I would suggest not using Wordpress for the simple reason that Github pages only needs to be maintained insofar as you have to update content periodically. Wordpress has security patches and the like. It's not a good use of time to deal with that kind of stuff, IMO.

We took this approach with neovim.org and we're very happy with the workflow.

**Comment by devilx** [comment]
@cweagans thank you for your feedback! You are totally right with what you said regarding WordPress' security flaws compared to GitHub pages and also regarding the time it takes to build a full project side on top of a WP.

On the other hand, WordPress allows to do things you can hardly do with GitHub pages out of the box: Integrating with social channels, providing blog-functionality and permit better user interaction through its various plug-ins.

In my opinion, if a more-or-less static page is everything you need, GitHub pages do the job quite well. If you don't need great SEO, don't interact with any other channels and if you're okay with something that's pretty much a one-way-communication (project -> users), GitHub pages are the most bang for the buck. As soon as a project would like to have some of these things though, I think there's no way around a software that eases content management as much as possible without compromising on SEO, distribution or two-way-communication.

**Comment by cweagans** [comment]
You can blog with Github Pages, and you can have users interact via Disqus or similar if necessary, and you can generate an RSS feed with Github Pages for IFTTT to consume, which can then push your content to Facebook/Twitter/pretty much anywhere else. Anyways, this is just my $0.02. We considered Wordpress for Neovim.org and it was just too much of a headache, and we eventually got to the point where we viewed that effort as a waste of time.

**Comment by devilx** [comment]
We found a theme. The kind people from http://ninzio.com sponsored us their Kapital theme.
