### ISSUE TITLE
Feature: Links to other notes and quotes

### ISSUE THREAD

**Issue by wongalvis** [twostairs/paperwork#312]
Within a note, there could be a way to add links to other notes, maybe even with a preview when the link is hovered on.
I would also suggest adding a quote function where certain text from another note could be quoted with reference details.

**Comment by kscheel** [comment]
+1
Internal links are an essential feature in a note taking system. At least for me ;)

I don't think quotes or previews are important though. But being able to link to a specific paragraph from another note or within the same note would be nice.

**Comment by mrusme** [comment]
Closing this issue in favour of the more detailed https://github.com/twostairs/paperwork/issues/241
