### ISSUE TITLE
Create update.php script that will completely update the project

### ISSUE THREAD

**Issue by narcolepticsnowman** [twostairs/paperwork#313]
as @Baldrs  said:

It will pull, composer update, npm update, bower install and then gulp
And transifex pull too, optionally

Doing this will simplify the update process for people, and prevent issues being opened related to missing part of this process.

**Comment by Baldrs** [comment]
I propose to implement this as [artisan command](http://laravel.com/docs/4.2/commands) to not overcomplicate.

**Comment by jamesrascal** [comment]
I think that this is related to #234 having a setup wizard would do the hard lifting. Once that exists having it run updates would not be to difficult.

**Comment by jamesrascal** [comment]
Also #242

**Comment by Liongold** [comment]
@jamesrascal These issues are to have something temporary until the issues you mentioned are fixed completely.

**Comment by narcolepticsnowman** [comment]
@Liongold This script could actually be implemented in such a way as to facilitate exactly what #242  is referring to. Thus, #242 would actually just involve creating some sort of front end to look up the versions in git, let you choose it, then execute this script.

**Comment by Baldrs** [comment]
Done in #371
