### ISSUE TITLE
New collection and share?

### ISSUE THREAD

**Issue by zebrastribe** [twostairs/paperwork#318]
Hi

Maybe my mistake but nothing happen clicking on "New collection" or "Share" in the demo.(demo.paperwork.rocks/)

**Comment by Baldrs** [comment]
I'm afraid until @devilx will see that, we could not provide any help with the demo site.

**Comment by zebrastribe** [comment]
ok, Baldrs. So I hope he will see it. Paperwork looks promising...

**Comment by devilx** [comment]
Simple: Collections aren't implemented yet. :-) Technically, they are. But the UI isn't ready to display them yet.

**Comment by Liongold** [comment]
The Share is also not implemented so technically there isn't any issue here. Should this be closed?

**Comment by Liongold** [comment]
It seems like both Collections and sharing are implemented now. Also, the demo has been closed. I'll close this issue. If you encounter any issues with these features or any other part of Paperwork, please open a new issue.
