### ISSUE TITLE
Actually delete notes

### ISSUE THREAD

**Issue by alphapapa** [twostairs/paperwork#319]
It's nice to see a nice-looking open-source Evernote/etc. alternative, so thanks for working on this.

However, I saw mentioned in another issue that you don't actually delete notes, you just mark them deleted in the database.  For me, this is a deal-breaker.  Trash bins are good to avoid accidental data loss and provide a way to get recent stuff back, but once the trash is emptied, the data should be actually deleted.  This is a privacy and security issue.

Of course, nothing is guaranteed--there could be backups, etc--but when the application says that something is deleted, it should actually do its part to delete it.

My 2 cents.  :)

**Comment by Baldrs** [comment]
This is protecting the notes from accidental deletion or whatever you done that lead to the deletion of a note. That can be fairly easily changed to full deletion, but I don't think it is 100% needed by all of the users. Anyway, you host it, so you can wipe something you want out from the database manually.

**Comment by alphapapa** [comment]
Isn't that what the trash bin is for, to protect against accidental deletion?

Well, opening up another tab, going to the phpMyAdmin URL for the database in question, digging through its cluttered UI to find the right table, running a search to find the right row, and then deleting it...is not something most users would want to do, and certainly not something I'd want to have to do, just to delete a note.

I mean, can you imagine telling a user who wants to delete a file from their filesystem to lookup the inode number and manually unlink all of its hard links?  That's basically the equivalent operation.  No one would use a filesystem like that.

Well, I guess Paperwork isn't what I'm looking for.

**Comment by zidarko** [comment]
I echo alphapapa's opinion. Deleting a note *must* delete this note. It is the expected behaviour in every piece of code I have come across so far.

**Comment by Baldrs** [comment]
There is #264 and it is not yet implemented. When it is, you will have what you desire. As you may have noticed, paperwork hasn't even reached 1.0 release. And while this is _beta_ software, you have to do this as I said, in database, until the feature is implemented. So instead of saying about inodes and wrong software, you may actually help us with designing how it will look like.

**Comment by Baldrs** [comment]
Duplicates #264
