### ISSUE TITLE
Paperwork & MAMP

### ISSUE THREAD

**Issue by thejadefarrar** [twostairs/paperwork#321]
Hi everyone,

This is actually my first time attempting to build and run an open source project.
I'm getting a lot of errors in the terminal trying to put together all the components.
I'm using mamp 3.0.7.3 on a Mac OS 10.10 machine, I don't have a lot of experience with programming so I'm hoping someone out there will be keen to guide me through this (I'm sure others will appreciate it too).
If you could start from step one that would be awesome
Thanks in advance

**Comment by Baldrs** [comment]
And what have you tried? Your question is like "I did something I don't understand, oh they will guess what I need for free, so I'll just ask for help without details.". Nobody will do this for you, nobody will guess what do you need. Welcome to the open source.

**Comment by vitor-faiante** [comment]
@thejadefarrar Can you give us information on what errors you got so that we could better help you.

**Comment by devilx** [comment]
First things first: You'll need MAMP PRO, since the free version doesn't provide all PHP extensions that are needed.

**Comment by thejadefarrar** [comment]
Thank you @devilx I will look into that.

The other thing I noticed is in the provided installation instructions it refers to:
`fig up`

I understand `fig` is somewhat depreciated does anyone have any advice on this?

**Comment by Baldrs** [comment]
fig is replaced by [docker compose](http://docs.docker.com/compose/), but in fact they are the same thing.
