### ISSUE TITLE
apache configuration

### ISSUE THREAD

**Issue by jasonbillebault** [twostairs/paperwork#324]
Hi,

I'm having troubles with apache configuration for displaying correctly Paperwork. If I type on the address bar my ip, I see the default webpage of apache showing 'it works !'.
I can access to Paperwork if I type index.php on the address bar of the navigator. Unfortunatly I don't have all the items like 'edit' or 'file' buttons.

For information, i tried to add the .htaccess quoted on the quick & dirty documentation in the frontend folder but it doesn't work anymore and when I type index.php on the URL bar, i get this error : The requested URL /paperwork/frontend/public/public/index.php was not found on this server.

Here is my actual apache configuration
    
    <VirtualHost *:80>
        ServerAdmin webmaster@localhost

        DocumentRoot /mnt/naslab/www/paperwork/frontend/public/
        <Directory />
                Options FollowSymLinks
                AllowOverride All
        </Directory>

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
                AllowOverride None
                Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
                Order allow,deny
                Allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn

        CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>

Thanks in advance for your help.

**Comment by Liongold** [comment]
Do you have mod_rewrite installed?

**Comment by jasonbillebault** [comment]
Hi,

Yes, the mod_rewrite is installed.

I did before a
sudo a2enmod rewrite and reloaded the server

If i put the .htaccess in paperwork/frontend. I have this 404 message on my web browser.

> Not Found
> The requested URL /paperwork/frontend/public/public/ was not found on this server.

**Comment by Baldrs** [comment]
Can you provide some error.log? And access.log too(please use pastebin)

**Comment by jasonbillebault** [comment]
Hi Baldrs,

Here the pastebin from error.log w/o .htaccess

http://pastebin.com/b6L0qUXC

here the pastebin from access.log w/o .htaccess

http://pastebin.com/9QjfWJpK

**Comment by jasonbillebault** [comment]
from error.log w/ .htaccess in frontend folder :
http://pastebin.com/3QfrY9Nz

from access.log w/ .htaccess in frontend folder :
http://pastebin.com/T9zwUeuU

**Comment by Baldrs** [comment]
Try updating config to this(replace yourdomain.here with your domain):

    <VirtualHost *:80>
        ServerAdmin webmaster@localhost
        ServerName yourdomain.here

        DocumentRoot /mnt/naslab/www/paperwork/frontend/public/
        <Directory /mnt/naslab/www/paperwork/frontend/public/>
            Options FollowSymLinks
            AllowOverride All
        </Directory>

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
            AllowOverride None
            Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
            Order allow,deny
            Allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn
    
        CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>

Also put this `.htaccess` into `frontend/public` folder

    RewriteEngine On
    
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

**Comment by jasonbillebault** [comment]
Everythings seems to work remarkably. Thanks !
I can begin to enjoy your solution now. :)

**Comment by daeavelwyn** [comment]
just to mention another config that works for me while the one previously posted doesn't :+1: 

```
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName yourdomain.here

    DocumentRoot /mnt/naslab/www/paperwork/frontend/public/
    <Directory **/mnt/naslab/www/paperwork/frontend/**>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
    <Directory "/usr/lib/cgi-bin">
        AllowOverride None
        Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
        Order allow,deny
        Allow from all
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log

    # Possible values include: debug, info, notice, warn, error, crit,
    # alert, emerg.
    LogLevel warn

    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
