### ISSUE TITLE
Move content from the readme.md file into the Wiki

### ISSUE THREAD

**Issue by jamesrascal** [twostairs/paperwork#326]
Content in the readme.md file should be migrated to the wiki. This would allow the content of the readme file to be updated by more people without having to make pull requests each time. I also feel like there is a value added to directing new users to a full install guide instead of the quick and dirty guide. 

The read me file should be short and to the point and direct everything else to the Wiki for example:
----------
[![Join the chat at https://gitter.im/twostairs/paperwork](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/twostairs/paperwork?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
[![Build Status](https://travis-ci.org/twostairs/paperwork.svg?branch=master)](https://travis-ci.org/twostairs/paperwork)

![paperwork-logo](https://raw.githubusercontent.com/twostairs/paperwork/master/paperwork-logo.png)

Paperwork aims to be an open-source, self-hosted alternative to services like Evernote (R), Microsoft OneNote (R) or Google Keep (R).

Paperwork is written in PHP, utilising the beautiful Laravel 4 framework. It provides a modern web UI, built on top of AngularJS & Bootstrap 3, as well as an open API for third party integration.

For the back-end part a MySQL database stores everything. With such common requirements (Linux, Apache, MySQL, PHP), Paperwork will be able to run not only on dedicated servers, but also on small to mid-size NAS devices (Synology (R), QNAP (R), etc.).

## Demo (yes, there is one!)

At [demo.paperwork.rocks](http://demo.paperwork.rocks) you can actually see the current development status of Paperwork. Every night at 3am (CET) the database is being dropped and newly created, and the latest sources from GitHub are being deployed on the machine.

Feel free to create/modify/delete accounts, notebooks and notes. This demo can be used for heavy playing without regrets. Just try not to take down that thing. :)

## Getting Started

Ready to install? See the [Wiki](https://github.com/twostairs/paperwork/wiki) for a full list of instructions, FAQ and more!

**Comment by Baldrs** [comment]
Wow, that looks good. I certainly vote for this. But we still need to move the articles into wiki. There is more generic issue #152 , but I won't mark this as duplicate because this is actually a solution. I think when we will finish merging #306(adds bower to readme), we can merge this change and write the articles in wiki.

**Comment by Baldrs** [comment]
#327 introduces this change

**Comment by Liongold** [comment]
Can this be set as fixed now?

**Comment by Baldrs** [comment]
@Liongold seems like, if anything is missing in the wiki we can dig it out from history and put it in the wiki.

**Comment by Liongold** [comment]
Ok, closing then.
