### ISSUE TITLE
Error text

### ISSUE THREAD

**Issue by wongalvis** [twostairs/paperwork#330]
When the latest commit in the local copy is not equal to the one in paperwork GitHub repo, this message appears in error-reporting box "Found a bug? It seems like you are not running the latest version of Paperwork. Please consider updating before submitting an issue."

But sometimes it is because people committed to their repo that the latest commits in the two repos are different, this message may be misleading.

**Comment by Baldrs** [comment]
Yeah that code is kind of blunt, it does not check if it is your commit newer than upstream, and it's kind of temporary, but there's nothing more permanent that temporary. So I'll fix that this week, if I'll have the time.

**Comment by Liongold** [comment]
@wongalvis Can you check if it works as it should now, please?

**Comment by wongalvis** [comment]
@Liongold Yes it's working.
