### ISSUE TITLE
SQLSTATE[HY000] [2002] Permission denied 

### ISSUE THREAD

**Issue by QkiZMR** [twostairs/paperwork#332]
After installing Paperwork with guide from http://paperwork.rocks/ and attempt to run application I got error like in topic. Other messages:
Open: /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php
41.   public function createConnection($dsn, array $config, array $options)
42.	{
43.		$username = array_get($config, 'username');
44. 
45.		$password = array_get($config, 'password');
46. 
47.		return new PDO($dsn, $username, $password, $options);
48.	}
Username and password was saved in /var/www/html/paperwork/frontend/app/config/database.php as has been written in guide.

**Comment by Baldrs** [comment]
The paperwork.rocks unfortunately receives updates infrequently, so it is may be outdated.

Which branch you are currently trying? If develop, then follow [this article](https://github.com/twostairs/paperwork/wiki/Initial-installation) for installation guide, we're trying to keep it up to date.

Additionally, please post your database configuration, your steps that you have done with the initial database setup.

**Comment by QkiZMR** [comment]
How do I check branch?

**Comment by Baldrs** [comment]
What? Where did you get the source code and how?

**Comment by QkiZMR** [comment]
Did you see this website? Instructions are on this page below.
http://image.qkiz.pl/di/44QS/Zrzut_ekranu_z_2015-04-02_16:14:25.png
I got source code from that website after clicking 'Download ZIP file' 9https://github.com/twostairs/paperwork/zipball/master).
I'm using Mysql.

**Comment by Baldrs** [comment]
Well, I've not just have seen them, I have written the version you see on the site. But it does not help, I was asking what have you done, literally the commands you issued to have the initial setup, contents of `database.php`(without your password).  

If your database is on some non-local hosted server, then user creation will not work for you, as you gain no access if your host is not `localhost`.

**Comment by Baldrs** [comment]
BTW, the files on the site are quite outdated, last development version can be obtained  [here](https://github.com/twostairs/paperwork/archive/develop.zip).

**Comment by QkiZMR** [comment]
Commands are same like on website. Database and Apache is on same server. 
Database.php -> http://pastebin.com/jXQHaMSE

**Comment by Baldrs** [comment]
Try changing this:

    'host'      => (getenv('DB_1_PORT_3306_TCP_ADDR') ? getenv('DB_1_PORT_3306_TCP_ADDR') : '127.0.0.1'),

To this:

    'host' => 'localhost'

Your server may be configured to not listen to 3306 port at all, and `localhost` has special meaning, mysql extension will try to connect using unix socket when host is `localhost`.

**Comment by QkiZMR** [comment]
How to turn off basic auth? Browser asks me for login and password.

**Comment by Baldrs** [comment]
Depends, first look into `.htaccess`, then in apache config

**Comment by QkiZMR** [comment]
I don't turn on basic auth. Here is my .htaccess:
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
Apache virtual host:
/etc/httpd/conf.d/paperwork.conf                                                                                                                                                                                        665/665               100%
Alias /paperwork /var/www/html/paperwork/frontend/public

<Directory /var/www/html/paperwork/frontend/public/>
    Options -Indexes
    <IfModule mod_authz_core.c>
    # Apache 2.4
    Require all granted
    </IfModule>
    <IfModule !mod_authz_core.c>
    # Apache 2.2
    Order Allow,Deny
    Allow from all
    #Allow from 127.0.0.1
    #Allow from ::1
    </IfModule>

    ErrorDocument 404 /core/templates/404.php

    php_value upload_max_filesize 512M
    php_value post_max_size 512M
    php_value memory_limit 512M
    SetEnv htaccessWorking true

    RewriteEngine on
    RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization},last]
</Directory>
I thought it was application doing that auth.

**Comment by Baldrs** [comment]
Try removing this line:

    RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization},last]

**Comment by QkiZMR** [comment]
I'm tried this. Not working. Here is debug log from apache:

    [Fri Apr 03 12:51:07.434164 2015] [authz_core:debug] [pid 31692] mod_authz_core.c(802): [client 172.25.26.211:34332] AH01626: authorization result of Require all granted: granted
     [Fri Apr 03 12:51:07.434173 2015] [authz_core:debug] [pid 31692] mod_authz_core.c(802): [client 172.25.26.211:34332] AH01626: authorization result of <RequireAny>: granted

Ok, I will erase whole application and install it from scratch.
