### ISSUE TITLE
Error in console related to calendar

### ISSUE THREAD

**Issue by 7brend7** [twostairs/paperwork#335]
I've noticed error message in console for current 'develop' branch:
> 'Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date.'

Not sure, but I think it's related to calendar control.

**Comment by Baldrs** [comment]
Yes, saw that, needs fixing. You welcome to create PR to fix that.

**Comment by Liongold** [comment]
Is this still actual?

**Comment by Liongold** [comment]
Using Paperwork 
b169a1e8b46a257c9b8a9248e4ab4f9224cdcb37, this does not seem to be the case anymore. Thanks for your feedback. If you encounter any issues with Paperwork, please open a new issue.
