### ISSUE TITLE
Disable sign up

### ISSUE THREAD

**Issue by joeinnes** [twostairs/paperwork#338]
I think it would be useful to have the option to disable signups - I'm using it as my own personal notebook, but I don't want just anyone to be able to register. I'd like to be able to enable/disable signups or approve new account creations or something along those lines.

**Comment by jamesrascal** [comment]
Sign up can be disabled by editing the paperwork.php file.

**Comment by Liongold** [comment]
@joeinnes Sorry for the closing of the bug early. As @jamesrascal suggested, you can disable signup by editing the config. About your other suggestions, could you please post them in the issue currently open for the Admin Center please?

**Comment by Baldrs** [comment]
@Liongold that must be filed separately and that should be stated in the wiki.

**Comment by Liongold** [comment]
@Baldrs What do you mean?

**Comment by Baldrs** [comment]
I mean we need to document it. This question appears weekly.

**Comment by jamesrascal** [comment]
The documentation is in the configuration file itself /frontend/app/config/paperwork.php

`
/*
	|--------------------------------------------------------------------------
	| Enable registration
	|--------------------------------------------------------------------------
	|
	| If set to true, user registration is enabled. If set to false
	| no new users will be able to register.
	|
	*/
	'registration' => true,
`

I feel like just pointing someone to that file should be enough. The comments in it contain everything you need. I will make sure to update the WIki pages to point new users to that file.

**Comment by Baldrs** [comment]
Newcomers are usually reluctant and unaware of any documentation in source files, so it must be stated clearly where are the config files, what can be configured in them, etc. All this must be in wiki, because we are not support center here and earn nothing to sit and answer questions that already answered.
