### ISSUE TITLE
Reconsider fonts

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#34]
So far Lato was being used on the web, until I found out that for example the Mozilla Firefox had issues loading the font files. However, I'm not sure, whether it's the perfect font to be used for this topic, though. And I don't know about the native clients as well. Maybe there's a better (in the sense of overall appearance and readability) font that could be used on the web?

**Comment by devilx** [comment]
I've checked out some other fonts and wasn't really happy the way the whole UI looked. Therefor, I'd really like to move back to Lato. For this, I created an issue (#225) which describes the current problematic. Closing this for now.

**Comment by pwmvx1289** [comment]
@devilx Have you considered Open Sans, a very popular font used for web design?
http://www.google.com/fonts/specimen/Open+Sans

**Comment by devilx** [comment]
@pwmvx1289 I did, but honestly I didn't like how Paperwork's Web-UI looked like using Open Sans. Maybe it is *because* it's being so widely used in web design, that I just had enough of it.

**Comment by pwmvx1289** [comment]
I see. What about Helvetica, although it's widely used, it is still suitable for different themed layouts.

**Comment by devilx** [comment]
@pwmvx1289 thanks for suggesting. I like Noto, due to the amount of different locales that are supported. The biggest issue, that's killing Noto for Paperwork is the fact, that it doesn't provide the extensive style-set we will need. For example the sans serif font only contains of two widths (400 & 700), with italic available for both. I loved Lato because of its amount of different widths, which come in handy very well.

Using Helvetica won't allow us to serve a webfont, due to licensing terms. Of course, we could speculate on Helvetica being available on every system that's trying to browse Paperwork web-ui, but that's pretty much the same behaviour with what we're doing right now:

```
Lato, 'Helvetica Neue', Helvetica, Arial, sans-serif;
```

We're not serving Lato or Helvetica (Neue) as a webfont, but we're hoping for it to be installed. Therefor, our current web-ui looks different in terms of fonts on every device.

**Comment by Baldrs** [comment]
Hope on client machines to have fonts is bad practice. I don't have any of the fonts above, for example, as they are all non-free ones. All of the above are resolving to this: DejaVu sans, Nimbus Sans and Arial(but I have installed it via ms-corefonts package, others may not have it).

I think that good practice is to serve Lato font or similar with app, to have the consistent UX among all platforms. I'd like to have only insignificant differences among platforms I use, and different fonts are significant difference. Therefore serving fonts is a must have for good UX.
