### ISSUE TITLE
encoding problem with certain characters

### ISSUE THREAD

**Issue by clemlaf** [twostairs/paperwork#344]
Paperwork could not save a note which contains certain characters like "×" or "œ". The mysql encoding seems correct, so it seems the problem does not come from the database.

**Comment by Baldrs** [comment]
Although needs confirmation, can you try it on older paperwork from master branch or before that commit: 4e3b5ed?

**Comment by clemlaf** [comment]
I tried with the current master version, and there is also the problem.
The put query gives a 500 error with the following message:
Error type : "Illuminate\Database\QueryException"
message : SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine (SQL: insert into `versions` (`title`, `content`, `content_preview`, `id`, `updated_at`, `created_at`) values (config apache, <p>caractères œ × et − et œ ààà</p>, caractères œ × et − et œ ààà, XXXXXXXXXXXXXXXxx, 2015-04-18 12:02:37, 2015-04-18 12:02:37))
file : paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php
line : 625

**Comment by clemlaf** [comment]
I refreshed the database using php artisan migrate:refresh, and until then the issue did not reappeared, so I guess the issue came from my configuration. Sorry for the disturbance.
