### ISSUE TITLE
Decouple backend from frontend

### ISSUE THREAD

**Issue by Baldrs** [twostairs/paperwork#345]
We have now strong ties between our angular frontend and our backend. That needs to be changed - then we will have clear client-server api, with our frontend as default client. 

To achieve this, we need to remove blades with angular-only html to frontend part. As we are going to have more clients for any platform, we don't need to have one of clients implementation inside backend, it must be api-only.

**Comment by Baldrs** [comment]
That is also related to performance optimizations which we can have using template cache - currently app is very slow on poor connections or when the server is slow for some reasons.

**Comment by 876974** [comment]
Need Linux desktop app

**Comment by mrusme** [comment]
Will be done with https://github.com/twostairs/paperwork/tree/2
