### ISSUE TITLE
Subfolder installation

### ISSUE THREAD

**Issue by Baldrs** [twostairs/paperwork#349]
1. [x] Fix frontend network service to recognize subfolder
2. [x] Fix backend to use url helper for aIl of the links

**Comment by Baldrs** [comment]
As suggested in gitter, creating an issue

**Comment by jamesrascal** [comment]
Should #256 be closed and linked to this issue then?

**Comment by Baldrs** [comment]
I think information on how to install in subfolder should be added to wiki first, and only when it is solved, it then must be closed.

This issue is a kind of task tracking.

**Comment by Baldrs** [comment]
Fixed in #360
