### ISSUE TITLE
Adding prefix to the database

### ISSUE THREAD

**Issue by AdiuvoDotFr** [twostairs/paperwork#353]
Hello,

I have tried to add a prefix to the database in the database config. 
Then, when I use "php artisan migrate", it throw me an error saying that it do not find the tables.
For now I didn't have enough time to take a look at it to find the error. Maybe I will try later.

Is it a bug known by the community?

PS: It's a fresh install of paperwork.

**Comment by Liongold** [comment]
I couldn't replicate this issue. Can you explain what did you do to install Paperwork exactly, please?

**Comment by Baldrs** [comment]
Is this still actual?

**Comment by AdiuvoDotFr** [comment]
Sorry I didn't come here for a long time. I haven't retried since, and use it without prefix now.
