### ISSUE TITLE
404 (not found)

### ISSUE THREAD

**Issue by kibwashere** [twostairs/paperwork#362]
Hi,

Everything was good until I get this when I'm reach this link http://127.0.0.1/paperwork/frontend/public/ :
![fail1](https://cloud.githubusercontent.com/assets/3426213/7401459/8aaa6dbe-eec4-11e4-8fc2-1ceeffcb9c73.png)
![fail2](https://cloud.githubusercontent.com/assets/3426213/7401460/8aacb380-eec4-11e4-957c-8ef225566794.png)

Here my .htaccess at "\www\paperwork\frontend\public" :
`<IfModule mod_rewrite.c>

    RewriteRule ^ index.php [L]
    
    RewriteEngine on
    RewriteCond %{REQUEST_URI} !paperwork/frontend/public/
    RewriteRule (.*) /paperwork/frontend/public/$1 [L]

</IfModule>`

And in the Apache conf there is rewrite_module activated :
`LoadModule rewrite_module modules/mod_rewrite.so`

I'm using wamp, and I have download the ZIP File.

Thanks in advance,

**Comment by jamesrascal** [comment]
Hello @kibwashere 

It looks like you are missing the last steps in the install process:

    install npm
    
     wget https://www.npmjs.org/install.sh
     bash ./install.sh
    install gulp and bower
    
     npm install -g gulp bower
    And then npm dependencies inside project
    
     npm install
    Then you install bower dependencies and just run the default task
    
     bower install
     gulp

This is what compiles the JS and CSS files. Unfortunately I am not familiar with WAMP enough to configure NPM and Gulp on Windows.

**Comment by cybernet** [comment]
as far as i know, tou cant execute sh files on windows ...

**Comment by kibwashere** [comment]
Yay, there was a problem in my gulp install, I didn't notice but gulp-less was not build correctly.
To resolve this, I replaced "gulp-less": "^2.0.1" by "gulp-less": "2.0.1" in package.json before to run npm install.
Since it works perfectly !

On windows, I have install npm with node.js, indeed, sh files doesn't work but I think it was just an example :) !

Thanks to you,

**Comment by jamesrascal** [comment]
@kibwashere then would it appear that something is incorrect in the package.json file that needs to be adjusted or just something you need to change in order to have Windows work with it correctly?

**Comment by Baldrs** [comment]
Well the recommended stack is still LEMP(Linux Nginx MariaDB PHP-fpm), and none of us has windows, so we barely can provide you with support.

Aside of the support message, it seems like resolved, so I will close.

**Comment by Baldrs** [comment]
Well the recommended stack is still LEMP(Linux Nginx MariaDB PHP-fpm), and none of us has windows, so we barely can provide you with support.

Aside of the support message, it seems like resolved, so I will close.

**Comment by Baldrs** [comment]
Well the recommended stack is still LEMP(Linux Nginx MariaDB PHP-fpm), and none of us has windows, so we barely can provide you with support.

Aside of the support message, it seems like resolved, so I will close.

**Comment by Baldrs** [comment]
Well the recommended stack is still LEMP(Linux Nginx MariaDB PHP-fpm), and none of us has windows, so we barely can provide you with support.

Aside of the support message, it seems like resolved, so I will close.
