### ISSUE TITLE
angular.js error after update

### ISSUE THREAD

**Issue by rzippert** [twostairs/paperwork#363]
Hello! Good afternoon.

I've been using paperwork for a little while and decided to update my files. The process were as described on the **README**. `git pull`and then `php artisan migrate` from the `frontend` directory. Seems I had to run an *admin to user* or something update on that process, and I believe it's all fine with my database, however when I sign in and get the main *paperwork* page no notes or notebooks are loaded. I seem to be able to enter settings or other pages but there's no content and I can't create anything.

I've found this error on my console from angular.js:

    "Error: [ng:areq] Argument 'ConstructorController' is not a function, got undefined
    http://errors.angularjs.org/1.2.21/ng/areq?p0=ConstructorController&p1=not%20a%20function%2C%20got%20undefined
    minErr/<@https://paperwork.site/js/angular.min.js:79:5
    assertArg@https://paperwork.site/js/angular.min.js:1501:5
    assertArgFn@https://paperwork.site/js/angular.min.js:1512:76
    $ControllerProvider/this.$get</<@https://paperwork.site/js/angular.min.js:7242:9
    nodeLinkFn/<@https://paperwork.site/js/angular.min.js:6636:13
    forEach@https://paperwork.site/js/angular.min.js:333:11
    nodeLinkFn@https://paperwork.site/js/angular.min.js:6623:11
    compositeLinkFn@https://paperwork.site/js/angular.min.js:6071:13
    compositeLinkFn@https://paperwork.site/js/angular.min.js:6074:13
    publicLinkFn@https://paperwork.site/js/angular.min.js:5967:30
    bootstrap/doBootstrap/</<@https://paperwork.site/js/angular.min.js:1441:11
    $RootScopeProvider/this.$get</Scope.prototype.$eval@https://paperwork.site/js/angular.min.js:12633:9
    $RootScopeProvider/this.$get</Scope.prototype.$apply@https://paperwork.site/js/angular.min.js:12731:11
    bootstrap/doBootstrap/<@https://paperwork.site/js/angular.min.js:1439:9
    invoke@https://paperwork.site/js/angular.min.js:3941:7
    bootstrap/doBootstrap@https://paperwork.site/js/angular.min.js:1438:8
    bootstrap@https://paperwork.site/js/angular.min.js:1451:5
    angularInit@https://paperwork.site/js/angular.min.js:1364:37
    @https://paperwork.site/js/angular.min.js:21879:5
    jQuery.Callbacks/fire@https://paperwork.site/js/jquery.min.js:3120:1
    jQuery.Callbacks/self.fireWith@https://paperwork.site/js/jquery.min.js:3232:7
    .ready@https://paperwork.site/js/jquery.min.js:3444:38
    completed@https://paperwork.site/js/jquery.min.js:3475:3
    " angular.min.js:10024

Is there something I can do to solve this?

Thanks!

**Comment by Liongold** [comment]
Can you try running `gulp` in the frontend folder?, please

**Comment by rzippert** [comment]
After that the error still occurs. As an observation, in the meantime as I have failed to restore paperwork to the state prior to the update (probably I made some mistake when backing up) and ended up making a new setup from scratch, and I got the exact same error starting from the current commit...

**Comment by rzippert** [comment]
PS: I can't say I'm comfortable with javascript or php, but I might be able to debug it to a minor level at least. That log I posted doesn't seem very useful (it's not for me at least). I'd be glad if someone could point me out what to look for. Does it seem like a backend issue? Frontend? Server setup? Sorry for asking this much, but I really don't want to make you lose time...

**Comment by Baldrs** [comment]
Have you tried clean setup from scratch?

**Comment by Liongold** [comment]
What branch are you testing?

**Comment by rzippert** [comment]
I tried a setup from scratch but will try again.
I'm using the master branch.

**Comment by Baldrs** [comment]
Master branch is very old, try the latest develop branch.

**Comment by rzippert** [comment]
Development branch seems to be working here, however when I create a notebook I get an "eternal loading" and could find another js error, but not sure if it's related:

![captura de tela de 2015-05-05 17 49 58](https://cloud.githubusercontent.com/assets/2091971/7482685/af0fd33a-f34f-11e4-8fc1-34a30ee916a9.png)

**Comment by Liongold** [comment]
Network tab output?

**Comment by Baldrs** [comment]
Any news on this?

**Comment by rzippert** [comment]
Been some pretty busy weeks. Will get back to this on the weekend.
Sorry...

**Comment by Liongold** [comment]
No problem.

**Comment by rzippert** [comment]
As lucky as I am, my webserver is down and I'm unable to get it back for now. It seems I'll need set up a new one. I really appreciate your help. I'll close this issue as it's unlikely I'll get the same error again. If I'm wrong, I'll let you know. Sorry for wasting your time...
