### ISSUE TITLE
Buttons without actions

### ISSUE THREAD

**Issue by wiltim** [twostairs/paperwork#364]
Clicks on the "Share"-Button and the "Info"-Button are without any action, the same with the "New Collection"-Button. This happens in your demo as too in my fresh builded Frontend of paperwork.

Tested with Safari (8.0.5) und Chrome 42.

**Comment by Baldrs** [comment]
Achtung! Google übersetzten Text.

Hallo, ich danke Ihnen für Ihren Beitrag. Wie Sie vielleicht wissen viele Betreuer sind nicht Deutsch sprechen und Google Translate übersetzt deutsche Sprache sehr schlecht. Können Sie die Nachricht in englischer Sprache zu wiederholen?

**Comment by wiltim** [comment]
Of course, sorry my mistake. I updated the issue.

**Comment by Baldrs** [comment]
Yes they will be implemented

**Comment by Liongold** [comment]
These functions have now been implemented. Thus, this issue will be closed. Thanks for your feedback. If you re-encounter any new issues with Paperwork, please open a new issue.
