### ISSUE TITLE
Insert font awesome function not working

### ISSUE THREAD

**Issue by oralion** [twostairs/paperwork#368]
Insert font awesome function not working when creating a not

**Comment by oralion** [comment]
Add math function not working (text field appears compressed)

**Comment by Baldrs** [comment]
Confirmed

**Comment by clemlaf** [comment]
This error seems to be due to the fact that some dependancies of ckeditor's fontawesome plugin are not met:
The missing dependancies are the colordialog plugin and the lineutils plugin. It seems that CkEditor has to be build again with these plugins in order to fix the problem.

**Comment by clemlaf** [comment]
Actually, what I wrote before was not correct. The problem does not come from the dependancies but from the configuration of ckeditor. The following lines (copied/paste from the ckeditor fontawesome plugin homepage) have to be added to frontend/public/ckeditor/config.js
```js
config.contentsCss = 'ckeditor/plugins/fontawesome/font-awesome/css/font-awesome.min.css';
config.allowedContent = true;
```
I'll send a pull request about that.

Concerning the math, mathquill.css in missing from the frontend/public/css, as well as Symbola font that is required by this css, but I don't know if adding these will fix the problem mentioned here.

**Comment by clemlaf** [comment]
The last commit corrected an error when inserting fontawesome but brought to light a new error when trying to save a note that contains fontawesome content.
Once again the solution was to be found on ckeditor fontawesome plugin's homepage: 
```javascript
CKEDITOR.dtd.$removeEmpty['span'] = false;
```
Pull Request coming.

**Comment by Baldrs** [comment]
Fixed.
