### ISSUE TITLE
Problems with install following CentOS guide.

### ISSUE THREAD

**Issue by boboysdadda** [twostairs/paperwork#375]
First off this can be closed as I resolved everything. but I wanted to share my findings so that others could benefit or maybe the wiki could be updated. I am running a clean install of CentOS 7.1* minimal on a vps. 

First issue i had was “Fatal error: Class ‘SimpleXMLElement’ not found”. To correct this issue I had to install a different version of php.
- install the repositories
rpm -Uvh https://mirror.webtatic.com/yum/el7/epel-release.rpm
rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm

- Replace php with php54
yum install yum-plugin-replace
yum replace php-common --replace-with=php54w-common

This created another issue when attempting to login "To fix iconv_strelen() Wrong charset, converstion from8bit//IGNORE'to UCS-$LE is not allowed" as php54w-mbstring was not installed during the previous command. 
-To  correct
yum install php54w-mbstring

Next thing I wanted to do was to be able to access everything while having SElinux and firewalld running.
- Allow access to mysql database by executing:
setsebool -P httpd_can_network_connect_db 1

- Allow access to http port 80 by executing:
setsebool -P httpd_unified 1

- If you have issues with SElinux configuration you can view your current attempts to connect through it that are failing by installing policycoreutils-python and then using the command auditallow -w -a
yum install policycoreutils-python
auditallow -w -a

Firewalld
- Enable http service access through the firewall
firewall-cmd --permanent --zone=public --add-service=http
firewall-cmd --reload

Again, Sorry if this isn't where this belongs. Just wanted to share.

**Comment by Baldrs** [comment]
You actually can update the wiki on the point, if you mind to fix your formatting.

**Comment by Baldrs** [comment]
@boboysdadda you can use backtick character ` to highlight the commands, also [see this](https://guides.github.com/features/mastering-markdown/)

**Comment by boboysdadda** [comment]
I believe i corrected the formatting a bit. But as I am not very good with the whole wiki etiquette. I Don't want to mess up everyone else's work. This could also all just be specific to my setup, even though it was on a fresh install of Cent, fully "yum upgraded"

**Comment by Baldrs** [comment]
@boboysdadda I'd recommend to use ubuntu instead, never had that much problems with it.

**Comment by boboysdadda** [comment]
@Baldrs I actually had all sorts of problems with Ubuntu but that was more than likely related to the fact that I installed owncloud and wordpress before paperwork.

**Comment by Baldrs** [comment]
@boboysdadda what was the default php version on 7.1?

**Comment by boboysdadda** [comment]
I'm not able to ssh into my vps from work but according to distrowatch it is 5.6.8

**Comment by Baldrs** [comment]
Well can you please workaround it using stock version? It's kind of preferred.

**Comment by boboysdadda** [comment]
I thought thats what I was getting out of the php54 packages
