### ISSUE TITLE
bower ENOENT No bower.json present

### ISSUE THREAD

**Issue by xmyfree** [twostairs/paperwork#376]
I'm following Debian installation guide to install paperwork. 
Everything woks well until this step: bower install
It says : bower ENOENT No bower.json present
Could you please help me? The folder I execute this command is /var/www/frontend

And find bower.json in side following folders: 
./node_modules/gulp-livereload/node_modules/debug/bower.json
./node_modules/gulp-less/node_modules/less/bower.json
./node_modules/gulp-less/node_modules/less/node_modules/request/node_modules/node-uuid/bower.json
./node_modules/gulp-less/node_modules/less/node_modules/request/node_modules/hawk/bower.json

Do you know how to solve it? Appreciate your help. :)

**Comment by Baldrs** [comment]
Use develop branch

**Comment by xmyfree** [comment]
Thank you. :)
