### ISSUE TITLE
Wayback machine does not work

### ISSUE THREAD

**Issue by Baldrs** [twostairs/paperwork#378]
I discovered this problem when I tried to get more space for mobile layout, so I've found a piece of markup there which had no height but margin. It turned out that it was a markup for the version widget, a "Wayback machine". The plugin itself is here: https://github.com/twostairs/freqselector
You can check out to see how does it work.

However in paperwork, it ceased to work sometime ago. The main problems are:

1. It does not invoked. At all. Someone removed the invocation from the code. I suspect accident when we were merging something or so. So it must be added back.
2. The second is the thing that the widget gets displayed, but in a wrong way:
    - Current version does not get selected.
    - Widget does not respond to clicks and user interaction.

Additional problems may be present.

The right way of invoking it is `$('#wayback-machine').freqselector('show');`, as @devilx have told me.

@devilx  have mentioned about some integration problems with angular, which are obviously caused by the way jQuery messes the angular-controlled DOM parts. 
To fix it I suggest adapting the existing widget into some angular way, so it will be a directive consuming versions as argument and broadcasting an event to which our note controller will listen and then will request version if necessary or just display it if it is already somewhere around.

**Comment by Liongold** [comment]
Is this bug still actual?

**Comment by Liongold** [comment]
I've tested this and it seems to be working as it should in Paperwork 
b169a1e8b46a257c9b8a9248e4ab4f9224cdcb37. Please reopen if you notice this issue.
