### ISSUE TITLE
Android app?

### ISSUE THREAD

**Issue by nklmilojevic** [twostairs/paperwork#379]
Hi,

I really like paperworks, but (for now) it's lacking Android application. Do you plan to develop it in the near future? I would gladly pay for it. 

Best regards,

Nikola

**Comment by Baldrs** [comment]
Sure we going to do it, if you want to help or donate you can contact me or
@devilx

**Comment by AnderRasoVazquez** [comment]
Having an open source note taking app like this, self hosted, with also an Android native app would be epic.

Keep up the good work! =)

**Comment by Baldrs** [comment]
While there are no app, this PR will somewhat improve usability on the phones: #377

**Comment by Liongold** [comment]
On Android, one can use Add to homescreen in Chrome for Android which makes it possible to have the app fullscreen and even have a place in the recently accessed menu (sorry if I'm not using the correct term).

**Comment by Baldrs** [comment]
@Liongold unfortunately paperwork is still unusable on android(some bug with versions I think), note cannot be edited.

**Comment by Liongold** [comment]
I didn't say it's perfect. If you know of any issues, please open a new issue for them (apart from the versions one of course).

**Comment by theSoenke** [comment]
I think native apps are usally still a lot better. They are faster, more responsive and internet speed is not so important. At least no webapp i ever used worked really great on a phone.

Had a little bit of time and build a small prototype for android

![Screenshot1](https://i.imgur.com/qvFlN6X.png)

**Comment by jamesrascal** [comment]
That looks so simple and perfect.

**Comment by Liongold** [comment]
I meant temporarily of course. It isn't something stopping from the development of Android app. Just a workaround for now.

**Comment by theSoenke** [comment]
Here is a first version of the Android App https://github.com/theSoenke/Paperwork-Android
Currently it's only possible to view and create notes. There is still a lot more to be done.

**Comment by Baldrs** [comment]
That's Android Studio project, right? So it can be built with Android Studio?

**Comment by jamesrascal** [comment]
Is there an APK for this or can you provide instructions on how to compile it?

**Comment by theSoenke** [comment]
@Baldrs Yes it can be build with Android Studio
@jamesrascal Currently there is no APK. I can add instructions on how to compile it, but basically you just have to import it into Android Studio and install the Android Support library and then you can run it

**Comment by jamesrascal** [comment]
I just complied and installed the App I see a lot of work that needs to be done but so far I have to say good work. I look forward to seeing how it progresses.

**Comment by bebehei** [comment]
:+1: For an android app!

**Comment by theSoenke** [comment]
It's now possible to edit, delete notes and view notes in notebooks with the app

**Comment by daeavelwyn** [comment]
Still no apk to test ??

**Comment by theSoenke** [comment]
@daeavelwyn I've now generated an APK to test: https://github.com/theSoenke/Paperwork-Android/releases/tag/v0.1

**Comment by daeavelwyn** [comment]
@theSoenke that's a really good news :-D thanks !

**Comment by stevenroose** [comment]
Is there a BountySource for Paperwork? Then we could donate to the Android app specifically :)

**Comment by stevenroose** [comment]
Or you could contribute to existing notebook apps and ask them if they want to implement the Paperwork API. Like [OmniNotes](https://github.com/federicoiosue/Omni-Notes) f.e.

**Comment by x-tk** [comment]
Is this still being worked?  Any plans to have an APK soon?

**Comment by mrusme** [comment]
Paperwork v1 won't receive an official Android (or iOS or whatever) app. There are a few projects out there that try to implement the Paperwork v1 API on a mobile client, though.

However, I'm closing this issue here and will update it as soon as there will be news to share. :-)
