### ISSUE TITLE
Downloading attachments of a note saves a file named "raw"

### ISSUE THREAD

**Issue by JamborJan** [twostairs/paperwork#382]
When you have attached a file to a note you can download it by clicking on it's name in the list of attachments or on the link shown in the note if you have inserted it there.

Unfortunately the download wants to save a file named "raw". The user has to re-name the file manually before it can be used.

It would be better to save the file as it was named before. The list of attachments shows this name so I assume it is known by the system.

**Comment by Liongold** [comment]
What browser is this? Mine opens the content of the file in a browser tab.

**Comment by jamesrascal** [comment]
This is browser independent. If your attachments is something that the browser can render it will do so but it will show as raw.pdf or raw.jpg.

If the file type is unknown it will output it with the original name. The issue occurs when you want to save the file it wants to save it as raw.

**Comment by Liongold** [comment]
Can you give me an example of a procedure and a filetype please?

**Comment by Liongold** [comment]
I have a txt file attached to the note. When opening the link, I get sent to paperwork_url/..../attachments/{id}/raw and the file is displayed. When trying to save page, I got a Save as dialog with the correct filename written there. Am I doing something wrong or what?

Also, just as a test, can someone go to ApiAttachmentsController.php file (frontend/app/controllers/api/v1), go to line 234 ('Content-Disposition....') and change inline to attachment? What is the name included in the Save As dialog then?

**Comment by jamesrascal** [comment]
I have 3 file types: JPG, PDF, TXT
![3types](http://i.imgur.com/sUyfyBq.png)

All 3 will open in the browser and display the content perfectly. However when you attempt to save the files either on the preview page or right click save link as:
![saving](http://i.imgur.com/OKTy8ec.png)

You only get a raw.filetype.

The only time it keeps the file name is when it is a file type that the browser can not display.

**Comment by JamborJan** [comment]
I have MS Word documents attached to some notes which have the *.docx extension and I am using Firefox 39 on a Mac. As you can see no extension is displayed at all and the file is only called ```raw```.

![raw](https://cloud.githubusercontent.com/assets/7508960/8042834/25a13344-0e22-11e5-8520-c96eb88d1e7f.png)

**Comment by clemlaf** [comment]
I've looked into the ApiAttachmentController.php, and it is a known issue: the $headers array is not passed when using the Response::make to send the file. However, there is currently a workaround that sets the header for the Content-Type only, and not Content-Disposition (where the filename is specified). That is why the content type is known and that the filename is set to "raw". It can easily be fixed to add the content of the $headers array to the workaround. That would add to the response header the filename.
I'll submit a pull request that fix this issue that way.

**Comment by Baldrs** [comment]
This has been fixed in #413. For any other issues regarding this, file a new request.
