### ISSUE TITLE
Notes with File Attachment

### ISSUE THREAD

**Issue by ghost** [twostairs/paperwork#384]
Killer app. 

For the life of me I can't see any option to attach a pdf file (i.e. a receipt, or document) to a note. I must be stupid. Someone please tell me this is  not a omitted feature and a mistake on my part?

**Comment by Baldrs** [comment]
There's actually upload file at the right(bottom in mobile layout)

**Comment by dbrgn** [comment]
I guess this can be closed. File upload is definitely there :)
