### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by theSoenke** [twostairs/paperwork#385]
On https://demo.paperwork.rocks i get a FatalErrorException 

> Class 'Paperwork\EloquentLdapConnectorServiceProvider' not found

**Comment by Baldrs** [comment]
Fixed

**Comment by theSoenke** [comment]
Thanks. But after login i get now a QueryException 

>SQLSTATE[42S02]: Base table or view not found: 1146 Table 'paperwork.users' doesn't exist (SQL: select count(*) as aggregate from `users` where `username` = myemail)

**Comment by Liongold** [comment]
Screenshot?

**Comment by theSoenke** [comment]
Error is gone now

**Comment by Liongold** [comment]
Good to know. Thanks for your interest in Paperwork and for contributing with your bug report. :)
