### ISSUE TITLE
Problem installing Paperwork with PostgreSQL and Apache2

### ISSUE THREAD

**Issue by andre-faria** [twostairs/paperwork#388]
I've placed a Virtual Ubuntu 14.04 and installed Paperwork following the tutorial with MySQL and nginx, It worked like a charm, but I've changed a little the tutorial to try to install in my computer who have apache and postgresql.

First install:
`sudo apt-get install -y -f php5-fpm curl wget git php5-cli php5-gd php5-mcrypt nodejs nodejs-legacy postgresql postgresql-contrib php5-pgsql apache2`

I've enabled `extension=mcrypt.so` in both fpm and cli php.ini

Installed composer and moved it to` /usr/local/bin/composer`

I've changed /var/www/frontend/app/config/database.php With
`'default'=> 'pgsql',`

and 
`'pgsql' => array(`
                `        'driver'   => 'pgsql',`
                `        'host'     => 'localhost',`
                `        'database' => 'paperwork',`
               `         'username' => 'paperwork',`
               `         'password' => 'myPassword',`
              `          'charset'  => 'utf8',`
             `           'prefix'   => '',`
            `            'schema'   => 'public',`
         `      ),`

To create user and database in psql I've used:
`sudo -u postgres psql`
`DROP DATABASE IF EXISTS paperwork;`
`CREATE USER paperwork WITH PASSWORD 'myPassword';`
`CREATE DATABASE paperwork OWNER paperwork TEMPLATE template0 ENCODING 'UTF8'`
`LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8';`
`GRANT ALL PRIVILEGES ON DATABASE paperwork to paperwork;`
`\q`

Activated rewrite
`sudo a2enmod rewrite`
and edited `/etc/apache2/sites-enabled/000-default.conf`
`<VirtualHost *:80>`
`ServerAdmin webmaster@localhost`
`ServerName yourdomain.here`

`DocumentRoot /mnt/naslab/www/paperwork/frontend/public/`
`<Directory /mnt/naslab/www/paperwork/frontend/public/>`
`Options Indexes FollowSymLinks`
`AllowOverride All`
`</Directory>`

`ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/`
`<Directory "/usr/lib/cgi-bin">`
`AllowOverride None`
`Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch`
`Order allow,deny`
`Allow from all`
`</Directory>`

`ErrorLog ${APACHE_LOG_DIR}/error.log`

`# Possible values include: debug, info, notice, warn, error, crit,`
`# alert, emerg.`
`LogLevel warn`

`CustomLog ${APACHE_LOG_DIR}/access.log combined`
`</VirtualHost>`

And `/var/www/paperwork/fronted/.htaccess with:`
`<IfModule mod_rewrite.c>`
`    <IfModule mod_negotiation.c>`
`        Options -MultiViews`
`    </IfModule>`

`    RewriteEngine On`

`    # Redirect Trailing Slashes...`
`    RewriteRule ^(.*)/$ /$1 [L,R=301]`

   ` # Handle Front Controller...`
 `   RewriteCond %{REQUEST_FILENAME} !-d`
`    RewriteCond %{REQUEST_FILENAME} !-f`
`    RewriteRule ^ index.php [L]`
`</IfModule>`

When I run : 
`sudo php artisan migrate`

The problem is:
![paperwork_2](https://cloud.githubusercontent.com/assets/12632275/7845992/10df6254-0491-11e5-9242-a70fa4c02f63.jpg)

The rest of guide was followed entirely, and this is the result when I try to load the page:
![paperwork_1](https://cloud.githubusercontent.com/assets/12632275/7846007/2deb9868-0491-11e5-94d0-477934c53a3e.jpg)

I did a LAMP, and the last error occur too, but the error of sudo php artisan migrate dont occur with MySQL.

**Comment by Baldrs** [comment]
We don't officially support postgresql and there could be incompatible
outcomes with current migration. Also your screenshot looks like if you
forgot to enable PHP handler in apache.

**Comment by andre-faria** [comment]
Ok, no problem!

>

**Comment by andre-faria** [comment]
About apache I was forgetting to install libapache2-mod-php5
