### ISSUE TITLE
Some issues after update

### ISSUE THREAD

**Issue by AlexIs72** [twostairs/paperwork#389]
* Classes not found: 
   * Class 'Paperwork\EloquentLdapConnectorServiceProvider' not found
   * Class 'Paperwork\UserRegistrationProvider' not found
   * Class 'Paperwork\Db\PaperworkDbServiceProvider' not found
   * Class 'Paperwork\Helpers\PaperworkHelpersServiceProvider' not found
   * Class 'Paperwork\Helpers\PaperworkHelpers' not found
   * Class 'Paperwork\Helpers\PaperworkHelpersFacade' not found

Local fix: added to frontend/vendor/composer/autoload_classmap.php

  `  'Paperwork\\Helpers\\PaperworkHelpers' => $baseDir . '/app/lib/Paperwork/Helpers/PaperworkHelpers.php',
    'Paperwork\\Helpers\\PaperworkHelpersFacade' => $baseDir . '/app/lib/Paperwork/Helpers/PaperworkHelpersFacade.php',
    'Paperwork\\EloquentLdapConnectorServiceProvider' => $baseDir . '/app/lib/Paperwork/auth/EloquentLdapConnectorServiceProvider.php',
    'Paperwork\\UserRegistrationProvider' => $baseDir . '/app/lib/Paperwork/UserRegistrationProvider.php',
    'Paperwork\\Db\\PaperworkDbServiceProvider' => $baseDir . '/app/lib/Paperwork/Db/PaperworkDbServiceProvider.php',
    'Paperwork\\Helpers\\PaperworkHelpersServiceProvider' => $baseDir . '/app/lib/Paperwork/Helpers/PaperworkHelpersServiceProvider.php', `

* 
` Undefined variable: gitOutput (View: /home/srv/paperwork/frontend/app/views/partials/error-reporting-footer.blade.php) (View: /home/srv/paperwork/frontend/app/views/partials/error-reporting-footer.blade.php) (View: /home/srv/paperwork/frontend/app/views/partials/error-reporting-footer.blade.php) `

/home/srv/paperwork/frontend/app/lib/Paperwork/Helpers/PaperworkHelpers.php:
`public function getHashes(){
        $cachedInfo = !\Cache::get('paperwork.commitInfo', [null, false]);
 
        if (!$cachedInfo[0] && !$cachedInfo[1]) {
            $resolver = strtolower(substr(PHP_OS, 0, 3)) == 'win' ? 'where.exe' : 'command -v';
 
            exec("$resolver git", $gitOutput);
...
`
Local fix: added $gitOutput ='';

* exec() has been disabled for security reasons
It's real issue for shared hosting. 

* `php artisan migrate
PHP Fatal error:  Class 'Paperwork\App\Commands\PaperworkUpdate' not found in /home/srv/paperwork/frontend/app/start/artisan.php on line 17
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Paperwork\\App\\Commands\\PaperworkUpdate' not found","file":"\/home\/srv\/paperwork\/frontend\/app\/start\/artisan.php","line":17}}`
`php artisan migrate:refresh
PHP Fatal error:  Class 'Paperwork\App\Commands\PaperworkUpdate' not found in /home/srv/paperwork/frontend/app/start/artisan.php on line 17
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Paperwork\\App\\Commands\\PaperworkUpdate' not found","file":"\/home\/srv\/paperwork\/frontend\/app\/start\/artisan.php","line":17}}`

Local fix: added to frontend/vendor/composer/autoload_classmap.php

* 
`php artisan migrate
Nothing to migrate.`

* I see only tags, no notebooks, no records.

* Click on "Settings" 
`Class Paperwork\UserRegistrator does not exist`

Local fix: added to frontend/vendor/composer/autoload_classmap.php

Still no records, no notebooks. 

Browser redirected to  "http://domain/#/n/00000000-0000-0000-0000-000000000000"

**Comment by Baldrs** [comment]
Instead of doing all that monkey patching, you had to run `composer
dump-autoload` after update. Also always run `composer update` after you
pull anything.

**Comment by AlexIs72** [comment]
No 
`composer`,
but
`php composer.phar dump-autoload`

All works. Thank you!

Sorry for misunderstanding.

**Comment by Baldrs** [comment]
I prefer installing composer globally(for daily usage), thus wrote it that
way.
