### ISSUE TITLE
Remove message "Found a bug?"

### ISSUE THREAD

**Issue by andre-faria** [twostairs/paperwork#391]
There is any way to remove the message below?

Found a bug? Paperwork cannot check whether your version is the latest. Please make sure you are running the latest version before

**Comment by Baldrs** [comment]
Currently only by deleting it from code. We may add environment check that will hide it when app is in production.

**Comment by Baldrs** [comment]
Stupid me, we have an option to remove it already in config/paperwork.php:

`'showIssueReportingLink' => false,`
