### ISSUE TITLE
Translation to pt-BR

### ISSUE THREAD

**Issue by andre-faria** [twostairs/paperwork#392]
I want to help, I can translate interface to pt-BR, as I never used github what is the best way I can do that?

Ty.

**Comment by ntnn** [comment]
Paperwork has a project on [transiflex]( https://www.transifex.com/projects/p/paperwork/) where translations should be made.

**Comment by andre-faria** [comment]
Thanks!

**Comment by Baldrs** [comment]
If you have questions you better ask them in our gitter room(follow gitter badge in readme)
