### ISSUE TITLE
Auto Save & Back option.

### ISSUE THREAD

**Issue by jamesrascal** [twostairs/paperwork#40]
Autosave feature would be wonderful! That is one of the features of the evernote that I really like.

Having the option to create a nightly backup would also be very nice to have.

**Comment by devilx** [comment]
@jamesrascal A thought on the auto-save feature:

You open your note and unintentionally delete half of it. That is a change you wouldn't want to be auto-saved. How would Paperwork "recognize" unintentional things and not auto-save them?

**Comment by jamesrascal** [comment]
That wouldn't be a problem as version control is already built into paperwork.

**Comment by devilx** [comment]
@jamesrascal the current "version control" only allows users to view but not recover to previous versions. Besides, depending on how often the auto-saving would occur, the user might end up with a dozen version for each note. I'm not sure yet, how this auto-saving feature should be implemented best, but I'm open to any good ideas!

**Comment by jamesrascal** [comment]
@devilx I think the best way would to save to a temp file (sort of the way MS office does it). Then the data being inputted would be saved to a temp file of sorts. When the user saves the file it would delete the temp file in favor of the newly saved version. But if the browser is closed without save the note and re-opened at a later time a message should be presented to the user something like. 

"This note has been recovered from an auto-saved version please save the note or discard these changes".

This would prevent dozen or so changes being saved to the version history while still auto saving the notes to prevent data loss.

**Comment by devilx** [comment]
@jamesrascal sounds like a good way to go. This "temp file" could be implemented easily in the browser's LocalStorage, to reduce roundtrip times and network data usage. In fact, the CKEditor Paperwork is using already provides such a plug-in: http://ckeditor.com/addon/autosave

I will check out how to include this into Paperwork.

**Comment by devilx** [comment]
Auto-saving should work now. However, there's an issue with the auto-saving plugin, which I already reported [here](https://github.com/w8tcha/CKEditor-AutoSave-Plugin/issues/38).
