### ISSUE TITLE
Server deployment

### ISSUE THREAD

**Issue by rosoft2001** [twostairs/paperwork#410]
The second time today I'm checking a project that require me to install things to server (composer, gulp, bower, npm) and I don't understand why.

If this would be a development machine I may understand (not really) but on the server should be only the files required at runtime. I just want to get the project and run it, like wordpress works. I can be bother with other stuff if I want to make a change to source. I don't, at least not in the production server.

It's anyway I can do this?

If not why?

**Comment by Baldrs** [comment]
Just do it on your machine and upload files to the server.
