### ISSUE TITLE
tagid filter issue

### ISSUE THREAD

**Issue by AlexIs72** [twostairs/paperwork#411]
Hello

I have problem with filter by tags. 
When I click on tag I have search string like a 'tagid:33' and no any results.

ApiNotesController.php have code:
`preg_match_all("/\s*(tagid|note(?:book)?id)\:([a-f\d]{8}(-[a-f\d]{4}){3}-[a-f\d]{12}?)/",`
This mean id like a '00000000-0000-0000-0000-000000000000'.

Is this error or upgrade issue?

**Comment by Baldrs** [comment]
It was changed in #66 to use UUID's

**Comment by Baldrs** [comment]
So I'm afraid you need to upgrade your database manually or reinstall paperwork to fix that: change was breaking.

**Comment by AlexIs72** [comment]
Do you have upgrade instruction?
Why new tags created without UUID?

**Comment by AlexIs72** [comment]
Latest upgrade failed:
+ php artisan migrate
**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? y

  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1005 Can't create table 'db_pprwork.#sql-5af_8373575' (errno: 150) (SQL: alter table `tags` add constraint tags_user_id_foreign foreign key (`user_id`) references `u
  sers` (`id`))

  [PDOException]
  SQLSTATE[HY000]: General error: 1005 Can't create table 'db_pprwork.#sql-5af_8373575' (errno: 150)

migrate [--bench[="..."]] [--database[="..."]] [--force] [--path[="..."]] [--package[="..."]] [--pretend] [--seed]

--->tag_id has type 'char(36)' - fixed
-----------------------------------------------
  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'tag_user' (SQL: drop table `tag_user`)

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'tag_user'

----->Please, add 'if exists'
-------------------------------------------------------
**************************************
*     Application In Production!     *
**************************************
Do you really wish to run this command? y
  [Illuminate\Database\QueryException]
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'user_id' (SQL: alter table `tags` add `user_id` char(36) not null)
  [PDOException]
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'user_id'

???????  and again return to first error
