### ISSUE TITLE
Undefined Offset: 3

### ISSUE THREAD

**Issue by leyonivipe** [twostairs/paperwork#420]
Installed paperwork on a clean Debian 7 following: https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Debian-7

Problem (opening any page): 
> Undefined offset: 3 (View: /var/www/paperwork/frontend/app/views/partials/error-reporting-footer.blade.php) (View: /var/www/paperwork/frontend/app/views/partials/error-reporting-footer.blade.php) (View: /var/www/paperwork/frontend/app/views/partials/error-reporting-footer.blade.php) 

Cause:
> list($lastCommitOnInstall, $upstreamLatest, $lastCommitTimestamp, $upstreamTimestamp) = PaperworkHelpers::getHashes();

Commenting out this line solved the problem temporary.

**Comment by Baldrs** [comment]
Seems like fixed in e75375c
