### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by sasir90** [twostairs/paperwork#421]
Question1:

 1. If I add a new image in a new note ,there is  no confirmation messsgae whether imgae added or  not.

2.Shall i add a Video and Audio upload by using notebook?

3.If add the data to a new notebook,how much amount of data MB  add? 
maximum amount of data?

**Comment by Baldrs** [comment]
1. There will be
2. Sure, you just need to configure your web server and paperwork accordingly.
3. Depends on how you have configured the web server.
