### ISSUE TITLE
PaperWork_customization

### ISSUE THREAD

**Issue by Mahentpl** [twostairs/paperwork#422]
Is it possible to customize the paperwork feature ?

**Comment by Baldrs** [comment]
Yes.

**Comment by Mahentpl** [comment]
can i save audio and video file in paperwork ?

**Comment by Baldrs** [comment]
If you wanna ask a lot of questions, please join our gitter chat(using badge in our README).

**Comment by Mahentpl** [comment]
Shall i know the  Step for Customize the Paperwork Features?

**Comment by Baldrs** [comment]
Maybe you will, I don't know what are you talking about.

**Comment by Mahentpl** [comment]
I mean, i need to add new features in paperwork.

**Comment by Mahentpl** [comment]
I need to work with developer mode in paperwork.
