### ISSUE TITLE
Max size per Note

### ISSUE THREAD

**Issue by Mahentpl** [twostairs/paperwork#425]
maximum storage size per note?

**Comment by Baldrs** [comment]
64k

**Comment by Mahentpl** [comment]
only 64 kb ah..

**Comment by Baldrs** [comment]
If you're talking about uploaded files, they're limited by the server config. 64kb is note text.

**Comment by Mahentpl** [comment]
maximum size for uploaded files ?

**Comment by Baldrs** [comment]
> If you're talking about uploaded files, they're limited by the server config

**Comment by Mahentpl** [comment]
ok thank you
