### ISSUE TITLE
Can't install because of composer failing dependency  adldap/adldap

### ISSUE THREAD

**Issue by nmaas87** [twostairs/paperwork#427]
I tried to update my installation using the information available on the main page http://paperwork.rocks/, however, this did kill my installation next to the database.
So I tried to reinstall it and try to recover my database dump.
However, an composer install only brought this output:

Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package adldap/adldap could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

So, I cannot install paperwork. Any ideas?

**Comment by serialdoom** [comment]
Same issue exists with docker install/test method in tip.
@nmaas87 do you know what version you had before you tried to upgrade ?

```
docker@boot2docker:~/paperwork$ docker-compose up
Recreating paperwork_db_1...
Building web...
Step 0 : FROM centurylink/apache-php:latest
Pulling repository centurylink/apache-php
0914a8ed3640: Download complete
511136ea3c5a: Download complete
c7b7c6419568: Download complete
70c8faa62a44: Download complete
d735006ad9c1: Download complete
04c5d3b7b065: Download complete
499d12a586e3: Download complete
0a591500d23b: Download complete
a4adcf7d13f1: Download complete
208726508d11: Download complete
a35c4329a0f1: Download complete
318d14bcb5f0: Download complete
9d5a770694fb: Download complete
88bee8cc4cf9: Download complete
9765133d2406: Download complete
d9e656a04de9: Download complete
Status: Image is up to date for centurylink/apache-php:latest
 ---> 0914a8ed3640
Step 1 : MAINTAINER Derek Myers <arcticpro@gmail.com>
 ---> Using cache
 ---> 51caf03118c1
Step 2 : RUN apt-get update &&  DEBIAN_FRONTEND=noninteractive apt-get -y upgrade &&  DEBIAN_FRONTEND=noninteractive apt-get -y install supervisor pwgen &&  apt-get -y install mysql-client libmcrypt4 php5-mcrypt php5-json php5-curl  php5-ldap php5-cli nodejs nodejs-legacy npm git git-core
 ---> Using cache
 ---> 6836ebd67d7c
Step 3 : ADD ./deploy/apache.conf /etc/apache2/sites-enabled/000-default.conf
 ---> Using cache
 ---> de340f44ba82
Step 4 : RUN a2enmod rewrite && php5enmod mcrypt &&     mkdir -p /app && rm -rf /var/www/html && ln -s /app/public /var/www/html
 ---> Running in 3979cd1c299c
Module rewrite already enabled
 ---> 5366bdb25304
Removing intermediate container 3979cd1c299c
Step 5 : ADD . /app
 ---> 29ccf45dca76
Removing intermediate container ab087f1e1686
Step 6 : WORKDIR /app
 ---> Running in cd7d35b1daac
 ---> f7b5e706d286
Removing intermediate container cd7d35b1daac
Step 7 : RUN find ./app/storage -type d -print0 | xargs -0 chmod 0755 &&     find ./app/storage -type f -print0 | xargs -0 chmod 0644 &&     composer install && npm update && npm install &&     npm install -g gulp bower && bower --allow-root install && gulp &&     chown -R www-data:www-data /app && chmod +x /app/docker-runner.sh
 ---> Running in 3b995181acec
Warning: This development build of composer is over 30 days old. It is recommended to update it by running "/usr/local/bin/composer self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package adldap/adldap could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Service 'web' failed to build: The command '/bin/sh -c find ./app/storage -type d -print0 | xargs -0 chmod 0755 &&     find ./app/storage -type f -print0 | xargs -0 chmod 0644 &&     composer install && npm update && npm install &&     npm install -g gulp bower && bower --allow-root install && gulp &&     chown -R www-data:www-data /app && chmod +x /app/docker-runner.sh' returned a non-zero code: 2
docker@boot2docker:~/paperwork$
```

**Comment by nmaas87** [comment]
@serialdoom 
I got this in the composer.lock file of the "dead-upgraded" folder.
However, I think it could already be overriden by the wrong version:

   "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file",
        "This file is @generated automatically"
    ],
    "hash": "6394bf63c87fc09019688dfe95d3dd08",
    "packages": [
        {
            "name": "adldap/adldap",
            "version": "v4.0-stable",
            "source": {
                "type": "git",
                "url": "https://github.com/ztec/adLDAP.git",
                "reference": "43bca164cde8f5a98e054e1aea53406aa3b805cc"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/ztec/adLDAP/zipball/43bca164cde8f5a98e054e1aea53406aa3b805cc",
                "reference": "43bca164cde8f5a98e054e1aea53406aa3b805cc",
                "shasum": ""
            },
            "require": {
                "php": ">=5.2.4"
            },
            "suggest": {
                "ext-ldap": "*"
            },
            "type": "library",
            "autoload": {
                "psr-0": {
                    "adLDAP": "lib/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",

**Comment by Baldrs** [comment]
It is related to adldap package. We'll update composer.json soon.

**Comment by Baldrs** [comment]
Fixed by replacing adldap/adldap with strebl/adldap

**Comment by narmadashanmugam** [comment]
how to get the latest fix ??

**Comment by Baldrs** [comment]
No just issue that in root of your paperwork install:

    git checkout develop
    git pull origin develop
