### ISSUE TITLE
No content after paperwork:update

### ISSUE THREAD

**Issue by slayit** [twostairs/paperwork#428]
The problem comes after using `php artisan paperwork:update`. (dev branch) 

This is how it looks now: ![image](https://cloud.githubusercontent.com/assets/657768/8261474/3677a21e-16cb-11e5-9058-e132a99edf60.png)

There is no content.

Can't seem to find anything suspicious in the update log: http://pastebin.com/Hzttnyx1

Console output of the site: ![image](https://cloud.githubusercontent.com/assets/657768/8261489/5454a17e-16cb-11e5-826e-db848a391dd6.png)

**Comment by nmaas87** [comment]
Could be same thing as my issue: https://github.com/twostairs/paperwork/issues/427
During the upgrade it had some dependency problems and damaged the database.
And you can't reinstall at the moment as these dependency problems keep you from installing as well as updating.

**Comment by slayit** [comment]
Possible, but my database is completely intact. Just made a diff between my backup and a current dump. Except for the session key in the user table there is no difference at all.

**Comment by Liongold** [comment]
My sincerest apologies for this. I've now fixed this issue. I'll push the changes to the develop branch in a couple of minutes.
