### ISSUE TITLE
Enhance "Move Note" dialog

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#43]
The current "Move Note" dialog looks weird to someone who doesn't know what it does:

![screen shot 2015-01-03 at 23 32 12](https://cloud.githubusercontent.com/assets/151967/5603990/dd955d92-93a0-11e4-8b36-5df9a70b4332.png)

At least one info text should be added above the list of notebooks, so the user understands what he could do with this.

**Comment by Liongold** [comment]
Taking this myself

**Comment by Liongold** [comment]
@devilx Do you think changing the dialog header to Move note to... would fix this?

**Comment by devilx** [comment]
@Liongold I guess some description above the list would be best. The thing is, I built that dialog pretty generic, so that you'd probably need to extend this generic methods in order to support some sort of "description" field.

**Comment by Liongold** [comment]
@devilx Is the dialog currently being used for something else other than Move Note? I'm working on the fix and am thinking about adding two parameters to 'modalData': header and description. I think I'll push some code next time.

**Comment by Liongold** [comment]
I've uploaded the code at branch issue-43-feature. @devilx, feel free to check it out.

**Comment by devilx** [comment]
@Liongold yes, from what I remember I implemented that one to be quite generic, so text shouldn't be included directly on the template. Will check out issue-43-feature asap.

**Comment by Liongold** [comment]
@devilx Did you check this, please?

**Comment by Liongold** [comment]
This has been fixed in #405. If you encounter any issues, please open a new issue report.
