### ISSUE TITLE
Installation of Paperwork on ubuntu

### ISSUE THREAD

**Issue by narmadashanmugam** [twostairs/paperwork#432]
During installation of Paperworks in ubuntu , I am try to install npm. After executing bash./install.sh the installation fails stating that 

curl : (56) Recv failure: Connection reset by peer
gzip: stdin: unexpected end of file
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable : exiting now It failed.

**Comment by Baldrs** [comment]
Try `sudo apt-get install nodejs npm` instead of messing packages with such
installs.

**Comment by Baldrs** [comment]
And that's actually not related to paperwork, so you can go file issue in https://github.com/npm/npm
