### ISSUE TITLE
Installing Paperwork on Ubuntu 14.10 issue

### ISSUE THREAD

**Issue by narmadashanmugam** [twostairs/paperwork#434]
On installing Paperwork on Ubuntu 14.10 was carried out as shown in the link https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Ubuntu-14.10
There was no error.
But on accessing the localhost i get the following error shown in attachment.
I am not able to identify it.
![30](https://cloud.githubusercontent.com/assets/13046322/8374044/a1052194-1c0f-11e5-9b6e-46f6b4df31ec.png)

**Comment by Baldrs** [comment]
Try lateste develop branch

**Comment by Baldrs** [comment]
Duplicate of #420

**Comment by narmadashanmugam** [comment]
on replacing the latest branch source should I issue any commands for build or restart. Because I am not getting any response from http://localhost/login

**Comment by Baldrs** [comment]
You need to rebuild everything again when you switch branches.

**Comment by narmadashanmugam** [comment]
Rebuild commands please

**Comment by Baldrs** [comment]
RTFM https://github.com/twostairs/paperwork/wiki/Initial-installation
