### ISSUE TITLE
PaperWork Setup File

### ISSUE THREAD

**Issue by sasisweert** [twostairs/paperwork#437]
1) Is it possible to change the paperwork configuration setup?

2) If possible mean how to proceed? how to change?

3)  which file is related to config set up under Config folder?

**Comment by Baldrs** [comment]
1. Yes
2. By hands, God's help and text editor
3. frontend/app/config/paperwork.php and the other in the same folder.

**Comment by sasisweert** [comment]
we could not upload the audio and video file in Paperwork tool(Unix implementation OS).

image file is uploaded in new note but 
Even 1 MB file also not accepted(uploaded) in new note.

 how to upload?

**Comment by narmadashanmugam** [comment]
I can upload only 1 MB audio and video file only. As per your point (Baldrs) i have changed the  setting in  etc/..php.ini   file ,after chaging the upload size value i can not upload the Higher than 1MB file.please help...how to upload Large size Mp3 and Mp4 file?
