### ISSUE TITLE
How to to increase the upload file size limitation in Paperwork ?

### ISSUE THREAD

**Issue by narmadashanmugam** [twostairs/paperwork#438]
How to to increase the upload file size limitation in Paperwork ? I heard that by changing settings in configuration file it is possible. Please let me know the configuration file details

**Comment by Baldrs** [comment]
Depends on your web server. See [here](http://lmgtfy.com/?q=nginx+php+upload+max+size) and [there](http://lmgtfy.com/?q=apache+php+upload+max+size). If any limitation is implied by our config, examine frontend/app/config/ folder and let us know.
