### ISSUE TITLE
Video and Audio file not accepted  paperwork application in Ubuntu

### ISSUE THREAD

**Issue by narmadashanmugam** [twostairs/paperwork#440]
I can upload only with in 1MB file .i could not abl to upload the above the 1MB file.
I have changed the upload size 100Mb in php.ini file even i could not able to upload.

So please can anyonle tell me what is the problem?how to solve it? please

**Comment by Baldrs** [comment]
You will drive me crazy some day. Provide:
1. Ubuntu version.
2. Your web server name and version.
3. Your PHP and MySQL versions.

**Comment by narmadashanmugam** [comment]
1.14.04
2.nginx and nginx/1.4.6(ubuntu)
3.php 5.5.9-1ubuntu4.9(cli) and 14.14 distrib 5.5.43

**Comment by Baldrs** [comment]
In /etc/nginx/nginx.conf:

Add or modify following line inside `http {`:

    client_max_body_size 4096M; // OR whatever you want to upload

In php.ini:

    upload_max_filesize = 4096M
    post_max_size = 4096M

After that in command line: 

    service nginx restart
    service php5-fpm restart
  
And please remember, if you want FREE tech support, you google for BASIC questions yourself.

**Comment by narmadashanmugam** [comment]
thank you very much....I can uploaded the large amout of file...

I have one doubt ,Now uploaded some video(5MB) file in  https://demo.paperwork.rocks/  ,but it is not playing but some Video file is playing well.

anydiffernce?

the same thing happening in our new Paperwork application (Ubuntu ) also...
could i know what is the problem?is this issue or not?
