### ISSUE TITLE
Unclear what to do after creating a new Notebook

### ISSUE THREAD

**Issue by jimlei** [twostairs/paperwork#442]
Users are presented with a pretty blank screen after creating a new notebook

![screenshot from 2015-07-01 20 36 16](https://cloud.githubusercontent.com/assets/4523053/8462024/1ca8d2ee-2031-11e5-99fd-ad30db36e83e.png)

I was first thinking it would be nice with just some "fun text" which is becoming increasingly normal (with a link to create a new note)

But if #259 (inline editing) is implemented then it'd be neat to just present a new note

![screenshot from 2015-07-01 20 35 20](https://cloud.githubusercontent.com/assets/4523053/8462028/21a6b5ae-2031-11e5-889e-a19a25bc1cb5.png)

**Comment by xadium** [comment]
Agree

**Comment by Liongold** [comment]
Even though inline editing has not been implemented, a message has been included in Paperwork that gives an indication of what to do when a notebook is empty. Thus, this can now be closed. If you, for any reason, don't agree just reopen the issue. If you have any other feedback, please open a new issue. Thanks for your contribution.
