### ISSUE TITLE
API node /api/v1/notebooks/{id}/notes does not provide title of notes anymore

### ISSUE THREAD

**Issue by ntnn** [twostairs/paperwork#446]
The note-listing in `/notebooks/{id}/notes` used to provide [the title of notes](http://docs.paperwork.apiary.io/#get-%2Fapi%2Fv1%2Fnotebooks%2F%7BnotebookId%7D%2Fnotes)   - on the develop branch a GET request for all notes in a notebook yielded [this](https://gist.github.com/ntnn/1195ef9712c7a87d375f) for a single note. 

Imho providing the title in this context is extremely useful so it should be added again.

**Comment by Liongold** [comment]
@ntnn It actually is provided in the version "child". Is that enough? Or would you like it to be on the first-level?

**Comment by Liongold** [comment]
This issue will be closed since there has been no reply for sometime. If you re-encounter thisa issue, please open a new issue. Thanks for your feedback.
