### ISSUE TITLE
Blank page apart from top bar

### ISSUE THREAD

**Issue by markfrancis905** [twostairs/paperwork#447]
Hello,

Just installed paperwork locally on my ubuntu 14.04 machine following https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Ubuntu-14.10.

It all worked as described apart from this error which I hacked into the fix from the develop branch https://github.com/twostairs/paperwork/issues/420

Now after logging in all I'm seeing is the top bar with the expected options (as per screenshots) and a dividing bar 1/3rd the way across the screen. The rest is blank.

Any help would be appreciated, this looks to be a promising project.

**Comment by Baldrs** [comment]
What do you mean by 'hacked into the fix'? Fetch the latest develop branch and rebuild all assets, no hacking. We currently have no stable version at all, but develop has more fixes.

**Comment by Lausii** [comment]
I have the same issue. I had to follow your instructions on #427 to compile paperworks. When I run it, I get a blank screen aside from the header.
![screenclip](https://cloud.githubusercontent.com/assets/13384681/8753540/6f1476c2-2c71-11e5-9416-cac0d2798a46.png)

**Comment by nadres** [comment]
Hello there,

This project made me sign up for Git Hub!

I have installed paperworks today on Ubuntu Server 14.04. The same issue as described here is happening to me: blank screen except menu header.

The only item I get blank page is "Library". All the others, "Profile", "Settings", "Admin Area" and "Help" appear to be working fine. Also tested in Firefox & Chrome.

Kind regards.

**Comment by Baldrs** [comment]
Have you built paperwork completely? `npm install`, `bower install`, `gulp`? Any errors in browser console? Have you tried pre-built version from releases?

**Comment by nadres** [comment]
bower install?

I followed instructions from http://paperwork.rocks

I don't recall that command. There was no error in the console during installation, other than issues with my Apache configuration regarding .htaccess.

I'll try it and report back... Now I see the Ubuntu link above.

Thanks.

**Comment by Baldrs** [comment]
Unfortunately @devilx and I are in lack of time recently, so to save everybody's time, use this: https://github.com/twostairs/paperwork/releases/tag/snapshot-3751d936

Unpack the zip file, point web server to frontend/public folder, have fun.

**Comment by Baldrs** [comment]
I will provide newer build soon.

**Comment by thirdeyetux** [comment]
I used the most recent commit and experienced the same issue. All the commands ('npm install', 'bower install', 'gulp') worked without a flaw.

I can see the following error in the browser console:
```
Error: [$injector:modulerr] Failed to instantiate module paperworkNotes due to:
[$injector:modulerr] Failed to instantiate module angularFileUpload due to:
[$injector:nomod] Module 'angularFileUpload' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.28/$injector/nomod?p0=angularFileUpload
minErr/<@https://paperwork.technick.org/js/angular.min.js:78:5
module/<@https://paperwork.technick.org/js/angular.min.js:1679:1
ensure@https://paperwork.technick.org/js/angular.min.js:1601:5
module@https://paperwork.technick.org/js/angular.min.js:1675:7
loadModules/<@https://paperwork.technick.org/js/angular.min.js:3877:11
forEach@https://paperwork.technick.org/js/angular.min.js:325:9
loadModules@https://paperwork.technick.org/js/angular.min.js:3871:5
loadModules/<@https://paperwork.technick.org/js/angular.min.js:3878:11
forEach@https://paperwork.technic angular.min.js:78
```

Maybe that helps?

**Comment by Lausii** [comment]
Using the link (https://github.com/twostairs/paperwork/releases/tag/snapshot-3751d936) provided works great. Don't download the source, but 3751d936.zip, which is a pre-compiled version. The only thing to do after moving it to the web sever is to create the database, run "php artisan migrate" and then adjust the necessary permissions.

**Comment by nadres** [comment]
Hello again,

I followed @Lausii comment and it appears to be all right. I got the following message covering bottom half of the calendar...

`Found a bug? Paperwork cannot check whether your version is the latest. Please make sure you are running the latest version before reporting any issues.`

...which I removed it by following [Issue 391](https://github.com/twostairs/paperwork/issues/391).

I noticed "New Collection" is not doing anything. I'll open another issue on this after some digging.
Let's see if paperwork can replace my local wiki!

Thanks for the help!

**Comment by thirdeyetux** [comment]
For sure it would be possible to use the prebuilt 'release tag', but I would like to stay with the current development and be able to get a working app by running the installation commands from the manual :-) The error message I posted above looks like there is a missing dependency to 'angularFileUpload' somewhere. I did not work with angular so far, so a little hint where to search for the missing dependency would be cool. I tested as well with the 'development' branch (and executed 'php artisan paperwork:update' afterwards), but experienced the issue in the frontend after logging in.

**Comment by Baldrs** [comment]
@nadres Collections are not implemented
@Lausii, I think I'll add a sql file in next release
@thirdeyetux for end-users releases are recommended because they were at least considered working to some degree of being usable by the person who assembled them. Whereas latest develop is unstable and not even tested every time. The missing dependency may be missing in some target in gulpfile

**Comment by thirdeyetux** [comment]
@Baldrs thank you very much for the information. I guess I will switch to use the 'pre-release' version then.

**Comment by thirdeyetux** [comment]
I had a look into the gulpfile and did the following change:
```
diff --git a/frontend/gulpfile.js b/frontend/gulpfile.js
index 1aaffb4..e370b22 100644
--- a/frontend/gulpfile.js
+++ b/frontend/gulpfile.js
@@ -28,7 +28,7 @@ var paths = {
         'app/js/bower_components/angular-route/angular-route.js',
         //'app/js/bower_components/angular-sanitize/angular-sanitize.js',
         'app/js/bower_components/angular-animate/angular-animate.js',
-        'app/js/bower_components/angular-file-upload/angular-file-upload.js',
+        'app/js/bower_components/angular-file-upload/dist/angular-file-upload.min.js',
         'app/js/bower_components/angular-utf8-base64/angular-utf8-base64.js',
         'app/js/bower_components/angular-ui-bootstrap-bower/ui-bootstrap.js',
         'app/js/bower_components/angular-ui-bootstrap-bower/ui-bootstrap-tpls.js',
```
Also make sure the javascript file (angular-file-upload.min.js) exists in 'app/js/bower_components/angular-file-upload/dist'. If not, go to 'app/js/bower_components/angular-file-upload' and build it via 'gulp angular-file-upload/build'. I also ran 'npm update' in that directory, because 'webpack' was not installed.

After you got the js build go to the 'frontend' directory and execute 'php artisan paperwork:update'. For me this did the trick and the app is working now...

**Comment by Baldrs** [comment]
I think we need to introduce some stricter locking as current one breaks stuff from time to time. Former was adldap from composer.

**Comment by Liongold** [comment]
It's been sometime since any new replies have been posted on this issue. It also seems like this issue has been fixed as of Paperwork 
b169a1e8b46a257c9b8a9248e4ab4f9224cdcb37. Thus, this issue will be closed. New issue reports are welcome. Thanks for your feedback.
