### ISSUE TITLE
LDAP: improve binding/auth method

### ISSUE THREAD

**Issue by DSpeichert** [twostairs/paperwork#450]
Some LDAP servers require full path for a user to bind (authenticate). That full name is suffixed by Paperwork with base_dn from config/ldap.php but there may be more parts that are variable.

Example:
base_dn => 'DC=sub,DC=domain,DC=com'
username = testuser

Paperwork would, however, try to bind the above user as ```CN=testuser,DC=sub,DC=domain,DC=com```.
For some LDAP structures with more advanced trees, this will not work. In case of that user, it might be necessary to instead bind as: ```CN=testuser,OU=User Accounts,OU=North,DC=sub,DC=domain,DC=com```.

Clearly, the user should not be required to enter all that data every time they log in and more issues would arise while displaying that data as username.

It is possible to fix this by altering the LDAP logic slightly to do the following:
1. Search LDAP tree for CN=testuser
2. If found, take the full DN
3. Bind as the DN from previous step to authenticate

I've tested a patch that does that and it's completely backwards compatible. I'll submit a PR soon.

**Comment by Baldrs** [comment]
I'm assuming that fixed.
