### ISSUE TITLE
Install With Error PHP Warning:  require(/var/www/html/paperwork/frontend/bootstrap/../vendor/autoload.php): failed to open stream: 

### ISSUE THREAD

**Issue by xiqingongzi** [twostairs/paperwork#457]
I search this repo ,and no vendor Directory.
Can't Install 
What Should I do?

**Comment by Baldrs** [comment]
Vendor directory is created by composer. See this [link](https://getcomposer.org/doc/00-intro.md) and then this [link](https://github.com/twostairs/paperwork/wiki/Initial-installation)
