### ISSUE TITLE
First run & "request URL not found"

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#460]
Hi,

fresh openSUSE 13.2 install
apache2 + mod_rewrite on
MySQL
PHP 5.6

After "1001" test installations (e.g. on wiki dont write "bower install" & install from wiki have bug with adldap), I hope, no errors are in my install. After install in /srv/www/htdocs/paperwork (docroot is /srv/www/htdocs via IP) if I write http://IP(or localhost)/paperwork/frontend/public, system redirect to IP(or localhost)/paperwork/frontend/public/login and stop: "request URL not found, error 404". I dont write .htaccess in docroot, but I see, in frontend & public are original .htaccesses. If i go IP/paperwork/frontend/public/index.php/login, I have correct login screen, after sign in I have correct paperwork, but havent "file", "edit", "search" on top bar & havent any note.  

When I run php artisan serve & go  localhost:8000, correct redirect to localhost:8000/login, after login I have correct paperwork with all notes, file, edit etc. What's wrong ? 
I dont know: is artisan serve an independ server (www,sql etc.) for framework or only debug for OS www & mysql ? 
I think, maybe rewrite on apache work not correctly ? Or sessions problem ? Or another problem ?

**Comment by Baldrs** [comment]
First of all don't use apache - no one is supporting it here. Use nginx and php-fpm. It is a faster and much more secure/reliable/faster/resource-effecinent configuration.
Second thing is that you must point your apache to serve frontend/public as /
Third thing it's clearly that rewrite is wrong.
Fourth thing is that artisan server is utilizing built-in php webserver which is for webserver-independent debugging purposes only.

**Comment by jacek-1210** [comment]
thx
I completely dont know nginx :(  I installed nginx, php-fpm & mariadb, but "for now" I dont know how to properly configure nginx for index.php, rewrite, vhost etc. Rewrite on apache work, but not properly. Is it possible, that are differencies between apache .htaccess & nginx .htaccess ?

**Comment by Baldrs** [comment]
See [here](https://github.com/twostairs/paperwork/wiki/Running-paperwork-in-subfolder).
And please remember that .htaccess, vhosts are the inventions of Apache web server, there is no .htaccess in nginx.
Also it does not operate vhosts, but rather server configs are responding to certain host names.

**Comment by jacek-1210** [comment]
Uffff, its work on apache :) Not exactly look like me to rewrite, more like Apache does not append a links. I was adding to apache paperwork configure directory:  FollowSymLinks, but it did not work. Until it dawned on me, that properly is: +FollowSymLinks  :)
Now working clear & properly
Thx for help, anyway I have to get to know better nginx
