### ISSUE TITLE
Paperwork database upgrade: General error: 1005 Can't create table 'paperwork.#sql-3a_2' (errno: 150) 

### ISSUE THREAD

**Issue by JamborJan** [twostairs/paperwork#462]
I have the following situation:

I have paperwork instances running on a version which was available in March 2015. When I take a look at the migration table it looks like this:

```sql
mysql> select * from migrations;
+---------------------------------------------------+-------+
| migration                                         | batch |
+---------------------------------------------------+-------+
| 2014_07_22_194050_initialize                      |     1 |
| 2014_07_24_103915_create_password_reminders_table |     1 |
| 2014_10_08_203732_add_visibility_to_tags_table    |     1 |
| 2015_01_21_034728_add_admin_to_users              |     1 |
+---------------------------------------------------+-------+
4 rows in set (0.00 sec)
```
Now I try to update the instances to the latest release candidate but all ```ALTER TABLE``` statements to ```ADD CONSTRAINT``` for a ```FOREIGN KEY``` fail. For example:

```sql
ALTER TABLE `tags` ADD CONSTRAINT `tags_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
```

```sql
  [Illuminate\Database\QueryException]                                                                                                                                                                        
  SQLSTATE[HY000]: General error: 1005 Can't create table 'paperwork.#sql-3a_2' (errno: 150) (SQL: alter table `tags` add constraint tags_user_id_foreign foreign key (`user_id`) references `users` (`id`))  
                                                                                              
  [PDOException]                                                                              
  SQLSTATE[HY000]: General error: 1005 Can't create table 'paperwork.#sql-3a_2' (errno: 150)  
```
I checked a ton of things already and everything seems to be okay (users->id is primary key, has an index, same collation etc.). But I cannot get it working.

When I try to force the upgrade manually by doing it step by step via ```mysql``` I get paperwork up and running but no notebooks, notes and tags are shown as the last 3 ```FOREIGN KEY``` constraints are missing.

Any idea what the cause of this is? I also tried to find solution in old issues and the github wiki, but I found nothing so far.

**Comment by Baldrs** [comment]
Have you used the paperwork before #66? It has broken anything. Next migrations are messy, I've fixed some, but I had database above your state. Can you file some snapshot of your state? Without data everywhere except migrations as shown.

**Comment by JamborJan** [comment]
I used a copy of Paperwork from February 11th 2015 as far as I can retrace. So I guess I have a database older than issue https://github.com/twostairs/paperwork/issues/66.

Here is a backup of an empty database only with initial stuff inside: https://gist.github.com/JamborJan/163b27cadcf30ccec748

This already has run the first 2 update steps until the first failed ```ALTER TABLE```. Here are some test queries I used to manually try to run the upgrade: https://gist.github.com/JamborJan/66c3bfb425c82a646f36

I hope that helps. Let me know if I can do something to make the investigation easier.

**Comment by Baldrs** [comment]
I see, than that's going to be difficult because for some reason @devilx introduced uuids by just rewriting existing migrations. So I'm afraid there's no easy way to upgrade your database. You need to convert it to uuid-based database somehow. Basically you need to create a new database and then use some script to move the data and map relations using uuids depending on the old database.

**Comment by JamborJan** [comment]
This seems to be a not so easy way. How did other users with existing databases migrate their instances?

I will try to do the following two things in an customized update script:

- change all IDs to UUIDs and try to keep it consistent

If this diesn't work:

- rename all tables to "bak_..."
- pull in the new structure
- move data from old to new
- delete all "bak_..."

I will post my results.

**Comment by Baldrs** [comment]
@JamborJan nobody migrated. Everybody just have reinstalled, I guess. I've never had significant data before #66 so I've started from scratch too, however after the point it seems to be more or less consistent.

**Comment by JamborJan** [comment]
There are tables where UUIDs are implemented e.g. ```attachments``` and tables where still ```bigint``` is the type of the table id like for example ```attachment_version```.

When something is changed shouldn't it be consistent everywhere?

Can users and contributors now expect the database to be stable managed with migration steps from version to version?

I try to find a solution for the problem and will let you know as soon as I find one. I guess this is rather unimportant for you as you don't have old versions which need an update. I think the most important thing is that Paperwork is developed in the future having in mind that people use it in production and that automated database migration is a must have.

**Comment by JamborJan** [comment]
I guess we can close this one.

The way to go is to set up a new instance. In my case I created an updated of my packaged version which has fixed export issues so that users are able to export their data at least and import it in the new version.
