### ISSUE TITLE
git configure for paperwork

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#469]
Im newbie in git, how to properly configure git paperwork for: "git pull" ?
I have installed standard git rpm, but if in ..../paperwork/frontend  write "git pull"  I get "fatal: not a git repository....."

**Comment by Baldrs** [comment]
Have you installed from snapshot? Only way to update snapshot is install a new snapshot.

**Comment by jacek-1210** [comment]
I get from https://github.com/twostairs/paperwork/  "download.zip" -> master.zip  & install step by step composer, npm, bower, gulp, php artisan migrate. In Your update info I see:

git pull
composer update
npm update
bower update
gulp

or:

php artisan paperwork:update


allways I get "fatal: not a git repository....."

But, after "1001" install, I move finally paperwork to another subdirectory - is it this ?

**Comment by Baldrs** [comment]
Download leaves you without .git folder. Use git clone command to clone repository.

**Comment by jacek-1210** [comment]
I have paperwork in /www/paperwork
In /www/paperwork/frontend  I write "git clone https://github.com/twostairs/paperwork.git" 
after download, git pull, I get "fatal: not a git repository (or any parent up to mount point /www)..."
Mount point /www ? Maybe this is problem ? How to change it ?

**Comment by Baldrs** [comment]
No, you're doing it wrong. Run the following

    cd /www
    rm -rf paperwork
    git clone https://github.com/twostairs/paperwork.git
    cd paperwork/frontend
    composer install
    php artisan paperwork:install

Then configure the database and run migrations.

**Comment by jacek-1210** [comment]
thx, works.
not to install from the beginning (I have working pwork copy before git clone), I rm paperwork directory, git clone in /www and overvrite git clone from working copy.
Now "git pull" give me "Already up-to-date"

**Comment by Baldrs** [comment]
That's ok because you have cloned repo a moment ago, thus it's "Already up-to-date"

**Comment by jacek-1210** [comment]
Hm, 

git pull
php artisan migrate:refresh  -> crashed sql base (dont sessions table)

php artisan migrate  -> repair crashed sql



php artisan paperwork:update  -> work properly, but dont touch sql...(if change base structure in the future (?))

**Comment by Baldrs** [comment]
paperwork:update currently does not support running migrations, but may
support someday

Regards,
Arseniy Lozicki
