### ISSUE TITLE
iOS Client

### ISSUE THREAD

**Issue by laeryn** [twostairs/paperwork#476]
Are there plans to develop an iOS client for paperwork?

**Comment by arnold-maderthaner** [comment]
is there already an iOS client ?

**Comment by mrusme** [comment]
Hey guys. There are plans and no, there is no official iOS client yet. That's everything I can tell you right now.

**Comment by ScrumpyJack** [comment]
how are we with the plans for an IOS app?

**Comment by DirectorX** [comment]
update?

**Comment by mrusme** [comment]
Well, basically it goes like this: As soon as an iOS developer is willing to join the project, we'll be able to build an iOS client. 🤷🏻‍♂️
