### ISSUE TITLE
Found a bug banner continues to show up

### ISSUE THREAD

**Issue by AaronSachs** [twostairs/paperwork#485]
Hi Twostairs Team,

I keep seeing the message:

```
Found a bug? It seems like you are not running the latest version of Paperwork. Please consider updating before submitting an issue. 
```

I've updated, but it contiues to show. Is this purposeful? Can I ditch this if I've already updated?

**Comment by Baldrs** [comment]
There is a setting in app/config/paperwork.php to disable it.

**Comment by Liongold** [comment]
I think the problem @AaronSachs is mentioning is that since we're using caching, the cache does not get updated when updating and thus still continues to show as outdated. 

@AaronSachs Am I right?

**Comment by AaronSachs** [comment]
@Liongold, yep. That's it. Is there any way to clear that out?

**Comment by Liongold** [comment]
You can try running `php artisan cache:clear` after the update. Let us know if you encounter any problems with it.

**Comment by Jherring01** [comment]
Though I have gone through the  app/config/paperwork.php to disable the popup, I am still getting it. Any additional suggestions?

**Comment by Liongold** [comment]
@Jherring01 Can you show the config details? Did you clear the browser's cache?

**Comment by Jherring01** [comment]
I have used 4 different computers and cleared the browser cache yes.  Found the issue.. I false'd the wrong line. Thanks!
