### ISSUE TITLE
Sidebar expand collapse arrows do not properly re-expand

### ISSUE THREAD

**Issue by philosowaffle** [twostairs/paperwork#486]
Found while using demo.

On left hand side bar, the different categories (Shortcuts, Tags, Notebooks,....) have an expand/collapse arrow.  By default these were all expanded and I could see the "Welcome" notebook as well as the "welcome" tag.  I clicked the arrow to collapse each category, everything was hidden as expected.  I clicked the arrows again to expand each category and nothing was displayed.

Browser: Chrome
Version 44.0.2403.155 m

![capture](https://cloud.githubusercontent.com/assets/7275041/9316460/ca987cfe-44fa-11e5-99fc-873683e9fe61.PNG)

**Comment by Liongold** [comment]
@philosowaffle The demo site is a little out-of-date it seems as I couldn't reproduce this. Can you try again using an up-to-date version, please?

**Comment by philosowaffle** [comment]
Don't know about the Demo site, but I have paperwork installed now on my own server and have not seen this issue.

**Comment by Liongold** [comment]
@philosowaffle Good to know. I'll close this issue then. If you encounter any other issues, please let us know.
