### ISSUE TITLE
Update on URL to FAQ about shared hosting environments

### ISSUE THREAD

**Issue by alsternerd** [twostairs/paperwork#487]
https://github.com/twostairs/paperwork#can-i-run-paperwork-on-a-shared-host-environment-where-im-not-able-to-set-frontendpublic-as-document-root

should be updated to:

http://paperwork.rocks/#can-i-run-paperwork-on-a-shared-host-environment-where-im-not-able-to-set-frontendpublic-as-document-root

everywhere this is mentioned in the issues or on other sites.

Now people that search for this on github know. ;)

**Comment by Liongold** [comment]
The readme has been rewritten since the opening of this issue. Thanks for your feedback. This issue will now be closed. If you encounter any issues, please open a new issue.
