### ISSUE TITLE
File > New collection" does nothing #15 (closed)

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#489]
For me, collections are interrest to agregation many notes by e.g. topics. (e.g.:  collection sport -> sport.health.notes; sport.ski.notes; sport.summer.notes;  collection home -> lng.invoices.notes; energy.invoices.notes; foto.documentation.notes; collection work -> somework.notes; documentation.work.notes; biznes.plan.notes  etc.)

**Comment by jamesrascal** [comment]
Hello,

With the current master build I was able to successfully create a collection. You need to create a notebook prior to creating a collection.

**Comment by Liongold** [comment]
@jacek-1210 @jamesrascal Can this be closed then?

**Comment by jacek-1210** [comment]
thx

**Comment by Liongold** [comment]
Thanks to you.

**Comment by jacek-1210** [comment]
Fine, for first look. I can make new collection. Some comments:
 
 
1. If I touch collection name, displayed notes. It would be good, if notes names were preceded by eg. space etc.
This would distinguish notebooks of collection from ordinary notebooks
 
2. 1-th touch collection name shows collection notes. 2-nd touch collection name should hide collection notes
 
 
3. Lack edition collection (change collection name, adding another notebook, delete collection name etc.)
 
 
 
 
W dniu 2015-11-18 19:54:14 użytkownik Liongold <notifications@github.com> napisał:
@jacek-1210 @jamesrascal Can this be closed then?

**Comment by Liongold** [comment]
@jacek-1210 If by 3, you mean editing, then yes there is something like that already. Check it out from the Manage Notebooks dialog. About the others, very good suggestions, thanks a lot.
