### ISSUE TITLE
 remove external dependencies 

### ISSUE THREAD

**Issue by JamborJan** [twostairs/paperwork#491]
There are external links used for bootstrap-editable css and js. To avoid outgoing requests and dependencies I'll propose a change to include these two files in the repo.

PR follows in some minutes.

**Comment by JamborJan** [comment]
Running in a sandstorm package it is rather annoying when external resources are required. I guess the same is valid when running paperwork in an internal network without any connection to the internet. Thats why I propose this change.

**Comment by Liongold** [comment]
Since the pull request associated with this issue has been merged, I'll proceed in closing this issue.
