### ISSUE TITLE
Ghostscript in paperwork (?)

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#493]
Paperwork fine upload jpegs as images (imagemagick ?). Maybe likewise been able to load a pdfs via ghostscript ?

**Comment by Baldrs** [comment]
Upload process has nothing to do with imagemagick or ghostscript. You just
need to allow the PDF upload

**Comment by jacek-1210** [comment]
How to "allow the PDF upload" ? In paperwork settings ?

**Comment by jacek-1210** [comment]
for clarity: I can upload, but if I touch "insert", I get only link in note, without text - content.

Question 2: 

often, if I upload doc, odt document (I have same problem as with pdf), I upload this & make copy/paste from openoffice. And often, after "save" I get that "note saved successfully", but if I open this note, Its empty :(

**Comment by Baldrs** [comment]
It is not intended to insert content into note. If you want content, copy-paste it.
