### ISSUE TITLE
Handlebars Not Rendering

### ISSUE THREAD

**Issue by tylershuster** [twostairs/paperwork#494]
I installed paperwork at notes.shuster.house and the system seems to be mostly working, except the templating language. There's mustaches or handlebars everywhere, and it looks like the CSS isn't working. Any idea why?

**Comment by Baldrs** [comment]
Where did you try to use it? It is not supported or used anywhere.

**Comment by tylershuster** [comment]
Well, then it must not be handlebars. I haven’t modified the installation but the interface isn’t rendering data; it looks like this, for example:
 {{ modalMessageBox.title }}

{{ modalMessageBox.content }}

**Comment by Baldrs** [comment]
Have you ran npm install, bower install and then gulp?

**Comment by tylershuster** [comment]
Man, I don’t know how but I missed bower install and gulp. It’s working now. PEBKAC
