### ISSUE TITLE
Note editor empty when opening note from filtered list

### ISSUE THREAD

**Issue by JamborJan** [twostairs/paperwork#496]
Tested with Firefox developer edition and Safari on a mac.
Source code from development branch from August 17th 2015.

How to reproduce the issue:
- you need at least 2 notes and one tag / one additional notebook / or notes from different dates
- filter the list of notes by clicking on one tag (in the example below I click on the "b-doing" tag)
- issue can be reproduced also by filtering the list by date or notebooks or using the searchbox
- the list gets filtered and only one note is shown (in my case the one called "some development stuff...")
- click on this note, it is shown on the right side
- click on the edit button, the note editor opens but everything besides the tags the note has is empty
- close the editor 
- now the list looses it's filter and all notes are shown again (which is a bug from my point of view)
- when you click now again the edit button you can see the note in the editor and change it

![untitled](https://cloud.githubusercontent.com/assets/7508960/9468856/3b032418-4b44-11e5-807a-9869634365d1.gif)

**Comment by JamborJan** [comment]
I didn't find the cause so far. Only difference I have found is that when the note is shown in the editor this PNG gets loaded: `ckeditor/plugins/widget/images/handle.png`

When I filter the note list upfront this gets not loaded. I guess this is rather a side effect and not the cause.

URLs are right in both cases and also the network analyses shows that the right data is requested and also completely send. 

Any ideas?

**Comment by Liongold** [comment]
I've done a workaround for this for now. However, I didn't find the actual cause.

**Comment by JamborJan** [comment]
I have implemented this fix in my Sandstorm.io package of Paperwork: https://github.com/twostairs/paperwork/commit/fc6be87f2f47eb09c3a6dff5ebddab4b5e862e51

I skipped this workaround as my opinion is that there shouldn't be code which has actually no need to be there as it might cause side effects in the future and I would suggest to remove that again.
