### ISSUE TITLE
Question: Installation on webhosting provider

### ISSUE THREAD

**Issue by coldib** [twostairs/paperwork#497]
Hi all,

as I did not find an installation guide - is it possible to host this on a traditional webhoster supporting PHP5/MySQL by uploading via FTP?

Thank you in advance!
coldib

**Comment by Baldrs** [comment]
You have not even try to search. Theoretically, you can, you just somehow need run migrations using prebuilt package.

**Comment by Liongold** [comment]
@coldib Can this help you? http://laravel.io/forum/02-19-2014-laravel-database-to-webserver
