### ISSUE TITLE
Demo site: certificate mismatch

### ISSUE THREAD

**Issue by hyrmedia** [twostairs/paperwork#498]
Thought I'd mention that when I visit https://demo.paperwork.rocks my browser throws a certificate error, saying the "security certificate presented by this website was issued for a different website's address."

Looks like it's just because the subdomain "demo.paperwork.rocks" is not covered by the certificate which was issued to "www.paperwork.rocks" -- in other words, it's not a wildcard cert. But it could confuse or worry people.

**Comment by jcrben** [comment]
Agreed, I noticed the same thing. It takes away from the professional image.

**Comment by jamesrascal** [comment]
@devilx @Liongold I believe this can be closed per #551

**Comment by Liongold** [comment]
This issue is being closed, per #551, as @jamesrascal said. Thanks for the reminder. :) Thanks to all participants for contributing to Paperwork through the creation and commenting in this issue.
