### ISSUE TITLE
Tagsinput should not only create tags on keypress ("enter") but also on "blur" (focus-out)

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#50]
Currently, the [bootstrap-tagsinput](https://github.com/TimSchlechter/bootstrap-tagsinput) by @TimSchlechter only creates tags when the user actually presses the "enter"-key. If he should just click somewhere else on the UI, the tag is not being created, remains pure text and therefor isn't being saved.

Now, this isn't something that needs to be fixed within Paperwork (but could be, although it would be quite a dirty hack), but Unfortunately the bootstrap-tagsinput project kind of fell asleep. Therefor I'd like some help here from anyone who's willing to contribute to Paperwork: Fix this issue and commit it to @TimSchlechter, so he can merge it into the official bootstrap-tagsinput repo. :-)

**Comment by ponychicken** [comment]
I thought this might be a good first bug, but when visiting http://timschlechter.github.io/bootstrap-tagsinput/examples/ the demo shows exactly the same behaviour you desire.

**Comment by ponychicken** [comment]
I'll fix this
