### ISSUE TITLE
Message bar not displaying properly

### ISSUE THREAD

**Issue by wongalvis** [twostairs/paperwork#506]
As shown below, the message bar was not displayed properly, it should be displayed on the top of the screen instead.
![2015-09-05 15_20_31-paperwork](https://cloud.githubusercontent.com/assets/6073063/9698281/aeb21bb2-53e1-11e5-809d-a6e9b433d996.png)

**Comment by wongalvis** [comment]
Was trying to fix it but couldn't locate the code related to the "Select notebook" modal and/or the message bar.

**Comment by Liongold** [comment]
@wongalvis Thanks for your contribution to Paperwork. The CSS properties of the red area (or green) is defined here: https://github.com/twostairs/paperwork/blob/develop/frontend/app/less/paperwork-themes/paperwork-v1/paperwork-v1-custom.less#L1159 while the modal dialog code can be found here: https://github.com/twostairs/paperwork/blob/develop/frontend/app/views/modal/notebookSelect.blade.php. Let me know if you need anything else.

**Comment by wongalvis** [comment]
@Liongold The "All Notes" should not be shown, and after that it will be not so often to encounter an error when moving note. In my opinion, although the display is not very nice at this moment, it is still good enough to display the message in case error occurred. I couldn't think of a better design yet after some tryouts, maybe someone else would have an idea to improve the design.

**Comment by wongalvis** [comment]
@Liongold This PR https://github.com/twostairs/paperwork/pull/517 sets the message to be displayed at top of the screen, which makes a significant difference in mobile screens - the message no longer displays at somewhere between the middle and the top, leaving a gap between the message bar and the top of the screen.

**Comment by Liongold** [comment]
@wongalvis Can you adjust the issue details now to be able to know better what's the remaining problem?

**Comment by wongalvis** [comment]
@Liongold I think the issue could be closed, the design is now somehow fixed, though there is room for further improvement.

**Comment by Liongold** [comment]
@wongalvis Ok, I'll close. You can open a new issue with your suggestions if you'd like to. Thanks for your contribution.
