### ISSUE TITLE
Share notebook/Share note is not working

### ISSUE THREAD

**Issue by PrimoZvanut** [twostairs/paperwork#509]
Solution:
/var/www/html/paperwork/frontend/app/controllers/api/v1/ApiNotebooksController.php:205
change
$tmp = $this->shareNotebook($notebookId, $toUserIds[$i], $toUMASK[$i]);
to
$tmp = $this->shareNotebook($notebookId, $toUserIds[$i], $toUMASKs[$i]);

/var/www/html/paperwork/frontend/app/controllers/api/v1/ApiNotesController.php:603
change
$tmp = $this->shareNote($notebookId, $singleNoteId, $toUserIds[$i], $toUMASK[$i]);
to
$tmp = $this->shareNote($notebookId, $singleNoteId, $toUserIds[$i], $toUMASKs[$i]);

If this bas been already reported/fixed, ignore.

**Comment by Liongold** [comment]
@PrimoZvanut You are free to open a pull request and fix this yourself. Which branch were you using when noticing this problem? If it wasn't on develop, please test this on develop branch before doing anything else. Thanks.

**Comment by morbidpete** [comment]
any progress on this? when looking at the file (located in /var/www/paperwork/frontend/app/controllers/api/v1 for me) I can not find that string at all to edit

**Comment by Liongold** [comment]
It seems like this issue has been fixed. Can anyone confirm please?

**Comment by Liongold** [comment]
Since no one has replied, this issue is assumed to be fixed. If anyone re-encounters this issue, please re-open this issue report.
