### ISSUE TITLE
Hide unparsed AngularJS variables on page load

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#51]
Paperwork needs to hide the "ugly" AngularJS variables on page load, until there's real content inside of them. My quick try with adding `ng-cloak` didn't work the way I expected. Maybe some AngularJS expert knows the reason / a working way?

**Comment by devilx** [comment]
@joshlemer seems like the fix doesn't work properly yet. It has been deployed on demo.paperwork.rocks and still shows the variables upon loading. Mind re-checking?

**Comment by joshlemer** [comment]
@devilx I am pretty confidend the issue is that the demo server hasn't compiled the new Less code into CSS. I just assumed that Gulp was run on the beta server before being deployed. Or would you prefer us to include compiled CSS in our pull requests?

**Comment by devilx** [comment]
@joshlemer understood the problem. I will work on allowing the demo-server to build these sources on its own and we should proceed the way you suggested it (not checking in compiled/compressed sources). Thanks!

**Comment by santosh-k1** [comment]
i want to set the height of the div at runtime but  there is issue that angular function call first and DOM load so shown that element undefined.. to fix this issue as a alternate used below code :+1: 
angular.element(document).ready(function () {
                setTimeout(function () {
                    var windowHeight = $(window).height() - 100;
                    $('#page-layout').css({ 'overflow-x': 'auto', 'max-height': windowHeight });
                }, 1000);
                $(window).resize(function () {
                    var windowHeight = $(window).height() - 100;
                    $('#page-layout').css({ 'overflow-x': 'auto', 'max-height': windowHeight });
                });
any one let me know what is the best way to do this??
