### ISSUE TITLE
php-xml package missing from CentOS/Fedora Instructions

### ISSUE THREAD

**Issue by mjtobias** [twostairs/paperwork#520]
Based on this page, https://github.com/twostairs/paperwork/wiki/Installation-----CentOS-Fedora
It looks like the php-xml package is missing in the CentOS-Fedora instructions.  Without this package it seems when trying to save anything in the body of a note the following error shows up in the nginx error log.  Installing php-xml, restarting nginx and php-fpm fixes this issue.

2015/09/14 22:33:19 [error] 1019#0: *453 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'DOMDocument' not found in /var/www/html/paperwork/frontend/app/lib/Paperwork/Helpers/PaperworkHelpers.php on line 27" while reading response header from upstream, client: <snip IP>, server: localhost, request: "PUT /api/v1/notebooks/00000000-0000-0000-0000-000000000000/notes/d7326fdb-168c-49bd-a0f6-0aeae12ee98f HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "<snip host>", referrer: "http://<snip URL>"

**Comment by Liongold** [comment]
I've edited the relevant wiki page and thus will now close this issue. However, if you find the text to not be good or find any other issue, feel free to let us know through this or another new issue. Thanks for your contribution.
