### ISSUE TITLE
API to create notebooks does not work

### ISSUE THREAD

**Issue by theSoenke** [twostairs/paperwork#522]
I can't create new notebooks via the api. The response code is 200 and it returns all notebooks, but it does not create a new notebook. 

POST  /api/v1/notebooks
>{
"type":0,
"title":"Test",
"shortcut":""
}

**Comment by Liongold** [comment]
Any more info? I've been trying to reproduce but am having problems with curl. Can you spot any differences between the headers you are sending and those sent by Paperwork UI when doing the same thing. Sorry if I'm asking for too much.

**Comment by theSoenke** [comment]
Sorry but i can't provide much more information. I'm using Postman to test the api. The header is definitly different when using Paperwork UI instead of Postman, but that's the case for all apis. E.g. it's uses a cookie instead of a hash etc. for authorization

**Comment by Liongold** [comment]
@theSoenke Thanks for telling me about Postman. Very nice product. I've tried it and it worked for me. I'll give you the headers generated by the app so that you can check whether there's some discrepancy. The body of the request: `{ "type": 0, "title": "API Test", "shortcut":"" }` and Content-type: application/json. I tested it on develop branch. Let me know if you get it to work. 

```
Cache-Control → no-cache
Connection → Keep-Alive
Content-Length →
171
Content-Type → application/json
Date → Sat, 26 Sep 2015 13:25:38 GMT
Keep-Alive → timeout=5, max=100
Server → Apache/2.4.7 (Ubuntu)
X-Powered-By → PHP/5.5.9-1ubuntu4.11
```

**Comment by Liongold** [comment]
BTW, I put the body content using the raw form.

**Comment by theSoenke** [comment]
@Liongold I did everything exactly like you and i'm using the develop branch, but it still does not work.
I also couldn't test it on demo.paperwork.rocks, because there are still problems with the certificate

**Comment by Liongold** [comment]
@theSoenke I really can't understand what's happening then. Do you know some PHP just some basic knowledge, nothing special)? Would you be open to trying and finding the problem through some experimentation? Sorry but I don't know any other way to try and trace this problem.

**Comment by theSoenke** [comment]
Issue seems to be gone in the latest paperwork
