### ISSUE TITLE
Note last update time

### ISSUE THREAD

**Issue by wongalvis** [twostairs/paperwork#524]
I get the date shown in each note of the note list updates whenever the note is moved to another notebook.
I think moving a note shouldn't count as a an "update action".
The last updated time should refer to the time of latest update to the note's content.
For instance, if the user moves a few note to a new notebook, and the notes inside the notebook are all having the same date, which makes it less easy for the user to identify the notes with respect to the date.

**Comment by theSoenke** [comment]
This would make it problematic to sync moved notes. Because to determine whether a note has been moved i use the last updated time in the app [Paperwork-Android](https://github.com/theSoenke/Paperwork-Android)

**Comment by wongalvis** [comment]
Oh right, you just reminded me that.
