### ISSUE TITLE
File > New Collection does nothing

### ISSUE THREAD

**Issue by berndblume** [twostairs/paperwork#527]
When I click on 'New Collection' under 'File', nothing happens. I just installed the latest version today.

**Comment by Baldrs** [comment]
I think it must be removed until somebody comes up with an implementation

**Comment by sdiver78** [comment]
If Collections are to be a collections of notebooks I would like this feature. If not, not sure what it's purpose would be personally. Having nested Notebooks would accomplish the same thing I would think too.

**Comment by Liongold** [comment]
@sdiver78 More information about the actual feature in #15

**Comment by Liongold** [comment]
The collections feature has now been implemented. Thanks for your contribution to Paperwork. If you encounter any issues and/or have any feedback about Paperwork, please open a new issue. This issue will be closed.
