### ISSUE TITLE
Code snippets are not visible in note

### ISSUE THREAD

**Issue by slayit** [twostairs/paperwork#539]
* Code snippets are not displayed correctly:
![2015-10-01 13_48_10-paperwork](https://cloud.githubusercontent.com/assets/657768/10219936/6c065ee2-6843-11e5-8a96-0ba32d9ed7c4.jpg)

* In the code editor everything seems right:
![2015-10-01 13_48_33-paperwork](https://cloud.githubusercontent.com/assets/657768/10219963/a5c96e08-6843-11e5-9728-c1ed08f56694.jpg)

**Comment by Liongold** [comment]
This issue has been fixed in #540 and therefore this issue will be closed. It is now available on the develop branch of our repository. If you encounter any other issues and/or have any feedback about Paperwork, please open a new issue.
