### ISSUE TITLE
Filtered note list gets lost after note is closed

### ISSUE THREAD

**Issue by JamborJan** [twostairs/paperwork#543]
To reproduce this issue follow these steps as shown in the example below:
- Click one tag ("tag_02" in the example is clicked)
- The list of notes gets filtered (only the note "Note Title (Tag_02)" is shown)
- Click the edit note button, note editor opens
- Change something or simply close the editor again
- The filtered list view expands again to the full list of notes despite the fact that the applied filter "tag_02" still appears in the search box

![untitled](https://cloud.githubusercontent.com/assets/7508960/10284682/8bc0f5a4-6b85-11e5-9d88-ce21d18e56c6.gif)

**Comment by Liongold** [comment]
This issue has been fixed in #544 and therefore this issue will be closed. It is now available on the develop branch of our repository. If you encounter any other issues and/or have any feedback about Paperwork, please open a new issue.
