### ISSUE TITLE
note content not displayed in main view

### ISSUE THREAD

**Issue by daeavelwyn** [twostairs/paperwork#546]
I'm using the last git version (make a git pull before reporting this issue) and as you can see in the picture below, the note content isn't displayed as it should.

![paperwork-issue](https://cloud.githubusercontent.com/assets/4292225/10426359/d3136496-70df-11e5-9ad3-2e543df20ad0.png)

**Comment by Liongold** [comment]
@daeavelwyn Any console output? Screenshot of the Network tab, please as well.

**Comment by daeavelwyn** [comment]
@Liongold hi, thks for your interest, I've nothing mentioned in my apache logs, but perhaps a better way than apache log exists to debug paperwork ? Please let me know the steps and I'll enjoy to follow your instruction :)
And last question, wht do you mean by "Network tab" ? I've found no network tab in the paperwork's UI :-/

**Comment by Liongold** [comment]
@daeavelwyn Sorry for that. If you're on Chrome, please on the menu button and then more tools and then find Developer Tools. There are the tabs there. If you're on other browsers or I haven't explained well, please let me know. Also, are you using develop branch?

**Comment by daeavelwyn** [comment]
oh sorry, I wasn't realize you wanted javascript  console output :)

here is the log from firefox (I just changed the domain name to my-domain.com) : 

Error: $(...).editable is not a function
@https://my-domain.com/js/paperwork.min.js:1079:7
$RootScopeProvider/this.$get</Scope.prototype.$emit@https://my-domain.com/js/angular.min.js:13028:15
.link/<@https://my-domain.com/js/paperwork.min.js:332:11
timeout/timeoutId<@https://my-domain.com/js/angular.min.js:14417:28
completeOutstandingRequest@https://my-domain.com/js/angular.min.js:4411:7
Browser/self.defer/timeoutId<@https://my-domain.com/js/angular.min.js:4725:7
 angular.min.js:10126:18

Error: $(...).editable is not a function
@https://my-domain.com/js/paperwork.min.js:1079:7
$RootScopeProvider/this.$get</Scope.prototype.$emit@https://my-domain.com/js/angular.min.js:13028:15
.link/<@https://my-domain.com/js/paperwork.min.js:332:11
timeout/timeoutId<@https://my-domain.com/js/angular.min.js:14417:28
completeOutstandingRequest@https://my-domain.com/js/angular.min.js:4411:7
Browser/self.defer/timeoutId<@https://my-domain.com/js/angular.min.js:4725:7

**Comment by Liongold** [comment]
@daeavelwyn Are you on the master branch of the repository?

**Comment by daeavelwyn** [comment]
@Liongold : perhaps I'm missing something. Here are the steps I do to update my version.

1- go to the paperwork directory
2- git pull

git branch returns * master, so I guess i'm on the master branch.

Am I wrong ?

**Comment by Liongold** [comment]
@daeavelwyn Sorry for the late reply. We know of an issue similar to that on the master branch. I've just opened a pull request to bring master up-to-date with the changes done to the 'develop' branch that is the branch used for development. Even though there's no fixed schedule, it shouldn't take long to merge this request. Thus, I suggest you wait a little more so that you can check if the latest code fixes the problem for you. 

If you don't want to wait, you can do `git checkout develop` and then `npm install`, `bower install` and `gulp`. Please let us know if you fixed the issue. Thanks.

**Comment by Liongold** [comment]
After the checkout command, you should do `git pull` also.

**Comment by daeavelwyn** [comment]
@Liongold : Thanks for your efforts, but your instructions totaly breaks my installation .... 
![paperwork01](https://cloud.githubusercontent.com/assets/4292225/10994681/293363de-8478-11e5-8596-1436b3f7d0c9.png)

**Comment by daeavelwyn** [comment]
@Liongold I just made a fresh install following those instructions : https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Ubuntu-14.10 and have exactly the same issue. 
As i haven't modified mysql DB, I guess the DB is corrupted. Do you agree ? Have you another suggestion to help me in debuuging this ?

**Comment by jamesrascal** [comment]
@daeavelwyn 

Are you having issues with the clean install? 
Did you follow the instructions on using Apache? https://github.com/twostairs/paperwork/wiki/Using-Apache-in-place-of-Nginx

If you are using the newest build you made need to make some additional changes to the database.php file in order to get paperwork to connect to MySQL.

**Comment by daeavelwyn** [comment]
@jamesrascal  : 
My apache settings worked very well with the previous installation of paperwork I had. 
The issue comes when I made a ` git pull`
removing extra stuff (isset in mysql array) in the database.php no more returns this error : "

```
php artisan migrate
**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? Y
                                                                                 
  [PDOException]                                                                               
  SQLSTATE[28000] [1045] Access denied for user 'paperwork'@'localhost' (using password: YES)  
    
migrate [--bench[="..."]] [--database[="..."]] [--force] [--path[="..."]] [--package[="..."]] [--pretend] [--seed]
```

so I succeeded in reinitializing mysql db. But, i stil got the same error : 

![paperwork02](https://cloud.githubusercontent.com/assets/4292225/11012418/f6d9bc04-84f3-11e5-93f7-501c97047624.png)

an clicking on MySql returns this javascript error : "TypeError: event.currentTarget.innerText is undefined" and just displayed me that : 
![paperwork03](https://cloud.githubusercontent.com/assets/4292225/11012430/22a59c90-84f4-11e5-92d1-4ed896f8089f.png)

**Comment by Liongold** [comment]
That's the Setup Wizard, not an error actually. The Javascript error, that's something else. Also pleased do not change any of the config files. If you want to skip the wizard, please check out this page: https://github.com/twostairs/paperwork/wiki/Installing-and-configuring-Paperwork-without-using-the-Setup-Wizard. Please let us know what is the problem after that. Thanks for your patience.

**Comment by daeavelwyn** [comment]
Ok guys, it seems my previous post wasn't so clear I expected. All apologies. 
So, I gonna try to be cleared here.

In my test, I make a clean paperwork install configured on ubuntu 14.04 with apache2. Here are exactly the steps I followed : 

Install the dependencies

```
apt-get update
apt-get install mysql-server php5-mysql nginx php5-fpm curl wget git php5-cli php5-gd php5-mcrypt nodejs nodejs-legacy
```

Enable mcrypt in the PHP configuration files, adding the following to the bottom of the config for php5-cli and php5-fpm:

`extension=mcrypt.so`

```
vi /etc/php5/fpm/php.ini
vi /etc/php5/cli/php.ini
```

Install composer

`curl -sS https://getcomposer.org/installer | php`

This will allow us to run composer without specifying the path

`sudo mv composer.phar /usr/local/bin/composer`

Create the directory that you want to install Paperwork at and CD into it:

```
mkdir /var/www/
cd /var/www/
```
Download Paperwork using git:

`git clone https://github.com/twostairs/paperwork.git`

Enter the front end directory:

 `cd ./paperwork/frontend/`

Run "composer install" and/or "composer update". This will install all the needed dependencies.

`composer install`

Create a file in the storage directory (`frontend/app/storage`), named: `db_settings`.

I'm using MySQL so I wrote the contents of the file in this form: 
`mysql, server, port, username, password`

 __remove the file named `setup` before trying to access Paperwork.__

After completing these steps go back to `paperwork/frontend` , run the migration jobs, that fill the database:

```
cd ../..
php artisan migrate
```

Change ownership of the Paperwork web-directory to the user nginx is running under:

`sudo chown www-data:www-data -R /var/www/`

Install gulp and bower:

 `npm install -g gulp bower`

And then npm dependencies inside project

 `npm install`

Then you install bower dependencies and just run the default task
``
 bower install
 gulp
``

Now we can configure apache 2 virtualhost with GnuTLS encryption : 

```
<VirtualHost paperwork.domain.com:443> 
        GnuTLSEnable on
        GnuTLSPriorities NORMAL
        GnuTLSCertificateFile /path/to/your/CRT/file.crt
        GnuTLSKeyFile /path/to/your/key/file.key

        DocumentRoot /var/wwwl/paperwork/frontend/public
        ServerName paperwork.domain.com:443
        ServerAlias www.paperwork.domain.com:433
        ServerAdmin  admin@paperwork.domain.com


        <Directory "/var/wwwl/paperwork/frontend/public">
           Options Indexes FollowSymlinks
           AllowOverride All
           Require all granted
        </Directory>

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
                AllowOverride None
                Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
                Order allow,deny
                Allow from all
        </Directory>

ErrorLog ${APACHE_LOG_DIR}/paperwork-error.log

# Possible values include: debug, info, notice, warn, error, crit,
# alert, emerg.
LogLevel warn

CustomLog ${APACHE_LOG_DIR}/paperwork-access.log combined

</VirtualHost>


```
Restart Apache2 and php

service apache2restart
service php5-fpm restart


So, following those steps work quite well, BUT, I had to restore my DB (thanks to phpmyadmin) to have the first user register, because following those steps doesn't permit to create the first user.

Perhaps you can use my post as a starting point to write documentation (WIKI) about isntalling paperwork on a ubuntu 14.04 with apache2 and gnutls, and add your own comments, and a way to add the first (admin) user for the installation.

Hope it's now clearer and can help someone else.

**Comment by Liongold** [comment]
Yes indeed, it's very helpful. Yeah, it's expected that, if you skip the Setup Wizard, the registration will have to be done through the normal registration page. However, the first user will till get admin privileges (or should get). 

@daeavelwyn Would you be interested in writing the article yourself and contributing to Paperwork?

**Comment by daeavelwyn** [comment]
@Liongold ok, so, the first user always has admin privileges. I won't have the time to write the article, sorry. But I will continue to test and report issues :)

**Comment by Liongold** [comment]
@daeavelwyn No problem, everything helps.

**Comment by daeavelwyn** [comment]
close in last update
