### ISSUE TITLE
Demo never works !

### ISSUE THREAD

**Issue by xerosanyam** [twostairs/paperwork#551]
http://demo.paperwork.rocks/
Always gives "The webpage is not available."
Tested in latest version of chrome as well as firefox.

**Comment by devilx** [comment]
https://twitter.com/paperworkrocks/status/650329394112806912

and

https://twitter.com/paperworkrocks/status/650329414287405056

:-)

**Comment by xerosanyam** [comment]
I am sorry to hear that.
but, following should  be done:
the link should be removed from the main repository, screenshots, link to a video must be added.

**Comment by Baldrs** [comment]
@devilx look who's come back!

**Comment by devilx** [comment]
@xerosanyam do you have capabilities / knowledge of providing us with a video? This would be really awesome indeed and I would support this. However, for the suggested steps separate issues should be opened here, in order to keep this one as reference for others who might ask the same question.
