### ISSUE TITLE
Problem with # after upgrade

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#553]
After last upgrade, when I push paperwork logo or "library" button (I will go to the start page), I get  link "paperwork_link.com/#" not "paperwork_link.com/" & I must allways manually delete "#"

**Comment by DeviantEng** [comment]
I am having this same issue.

**Comment by Liongold** [comment]
Can you please explain a bit more? Is the problem an extra #? Does it affect the page at all?

**Comment by jamesrascal** [comment]
If you are editing a note for instance. Save and then click on the Paperwork Logo to go back to the main page it shows as blank: 

![2015-11-10_17-00-20](https://cloud.githubusercontent.com/assets/6054150/11080860/ed64b4d6-87cc-11e5-92fa-d1880bd33812.png)

Once you remove the # and refresh the page it restores the content:

![2015-11-10_17-00-37](https://cloud.githubusercontent.com/assets/6054150/11080866/fc405d48-87cc-11e5-939a-aec637a067d5.png)

This also occurs if you click on the Library link after editing a note.

Please note that I seem to only be able to re-create this issue when editing a note.

**Comment by Liongold** [comment]
@jacek-1210 @DeviantEng @jamesrascal Any errors in the browser's console?

**Comment by jacek-1210** [comment]
Hi, I closed it (new collection). 
 
 
I have some errors if I try to edit some notes. Usually if copy/paste some web page into paperwork, and next when go to edit I see blank card in paperwork :(   But now (from 1 month) I haven't newest version of paperwork. I must update and try.
 
about the problems  (when touch logo I get http://paperwork_adress/#   where # prevents proper opening webpage )   I have already written 
 
 
 
 
 
 
W dniu 2015-11-18 20:02:11 użytkownik Liongold <notifications@github.com> napisał:
@jacek-1210 @DeviantEng @jamesrascal Any errors in the browser's console?

**Comment by jamesrascal** [comment]
This is the only error that I am seeing in console: 
    
    Error: Unknown language: "xhtml"
    at c [as highlight] (highlight.pack.js:1)
    at d.highlight (angular.min.js:36755)
    at d.setLanguage (angular.min.js:36755)
    at angular.min.js:36755
    at angular.min.js:5990
    at Scope.$eval (angular.min.js:12851)
    at Scope.$digest (angular.min.js:12663)
    at Scope.$apply (angular.min.js:12955)
    at done (angular.min.js:8466)
    at completeRequest (angular.min.js:8680)

**Comment by Liongold** [comment]
@jamesrascal That shouldn't be related to that. However, some more research is needed for this.

**Comment by jacek-1210** [comment]
After new upgrade is the same:

I add/edit note:

![paperwork4](https://cloud.githubusercontent.com/assets/13505686/11311851/d6f8a500-8fd2-11e5-91c0-4ab61124d786.JPG)

and save note:

![paperwork5](https://cloud.githubusercontent.com/assets/13505686/11311859/e78944ce-8fd2-11e5-86f7-8721fe23ef33.JPG)

next I will go to home - I touch logo (or "library"):

![paperwork6](https://cloud.githubusercontent.com/assets/13505686/11311901/0ca0c3fe-8fd3-11e5-8b1a-859bdd7c9f55.JPG)


and I get blank screen :(  

![paperwork7](https://cloud.githubusercontent.com/assets/13505686/11311930/222ed242-8fd3-11e5-9f71-9513920eda9f.JPG)


whats wrong ?

**Comment by jacek-1210** [comment]
I reply on git
 
 
 
W dniu 2015-11-18 20:02:11 użytkownik Liongold <notifications@github.com> napisał:
@jacek-1210 @DeviantEng @jamesrascal Any errors in the browser's console?

**Comment by Liongold** [comment]
@jacek-1210 Do you have an idea when did you do the update that broke Paperwork? And which branch do you run?

**Comment by jacek-1210** [comment]
I did the update probably in the first half of October. But previously I did not update more than a month. Probably, I had a properly functioning program from August. 

I found an old copy paperwork (files are dated 31 July, 4 and 24 August), now I reinstalled this copy and work OK, no problem with home page function. After returning to the new / latest version again is a problem with #

**Comment by Liongold** [comment]
So at August 24, there were no problems? Thanks a lot for your help.

**Comment by jacek-1210** [comment]
I'm not sure. In the same folder/install, I have files with these various dates. More files is dated 31 July. Maybe I installed 4-24 August ?

**Comment by Liongold** [comment]
Oh I think I'm understanding. So we can say that the version there was on July 31 was working well, right?

**Comment by jacek-1210** [comment]
I think so

**Comment by Liongold** [comment]
OK, that's very valuable information. What branch do you run? (Did you do `git checkout develop` at any time)?

**Comment by Liongold** [comment]
You can also check it by doing `git status` in the command line and check what follows the text: "On branch" near the top.

**Comment by jacek-1210** [comment]
I get this:

![paperwork15](https://cloud.githubusercontent.com/assets/13505686/11665119/ecdb658a-9de5-11e5-8b38-ccee5db4ea72.JPG)

on branch develop
Your branch is up-to-date with 'origin/develop'  
etc.

**Comment by Liongold** [comment]
OK, thanks for your help. This will surely help when it comes to fixing this problem.

**Comment by Liongold** [comment]
I've opened a pull request with a fix for this. However, I still haven't found the exact cause of this problem.

**Comment by jamesrascal** [comment]
This is  now working in the Develop branch. I know its a work around but it's now functional.

**Comment by jacek-1210** [comment]
thx

**Comment by foozleface** [comment]
I see this on both the develop and master branch. It happens when I create a new note, then hit the "home" button (paperwork icon in the upper right).

**Comment by jacek-1210** [comment]
The same problem come back :/  
I dont make upgrade from Jan.2016. Now, after reinstall (git clone) - the same problem
Copy before 2016.01.01 work correcty

**Comment by Liongold** [comment]
Thanks for this information.
