### ISSUE TITLE
Paperwork via ssl (https)

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#554]
I can't find, what configure paperwork to work via https. Is it possible ? When I set server to https work via 443 port, I get "page not found" (another sites works via ssl)

**Comment by jacek-1210** [comment]
How to configure generate internal links in paperwork to: https://paperwork_link.com ? Maybe this help ?

**Comment by ntnn** [comment]
That should happen automatically, considering that all links are relative to the paperwork-root (afair). Seems to be a problem with the configuration of your webserver.

**Comment by jacek-1210** [comment]
Very thx, really server ssl config was bad, not for paperwork (symlinks etc.). Now works via ssl :)
