### ISSUE TITLE
Setupwizard and db_settings does not support Database name

### ISSUE THREAD

**Issue by jamesrascal** [twostairs/paperwork#557]
With the new setup process there is not a way to specify database name.

In order to use a database that is not named "paperwork" you need to modify the settings in the database.php file.

Setup wizard and db_settings should allow for database name.

**Comment by Liongold** [comment]
Thanks for this suggestion.

**Comment by Liongold** [comment]
@jamesrascal I've done some code for this already. Is it fixed now then?

**Comment by jamesrascal** [comment]
Is this in master or dev? I'll configure a new install and test tonight.

**Comment by Liongold** [comment]
It's on develop branch.

**Comment by Liongold** [comment]
A setup wizard is now available. The database name should now be configurable. Thus, I'll close this issue. Thanks for your feedback. If you re-encounter this issue, please open a new issue.
