### ISSUE TITLE
Adding code block without setting a type causes the note to render blank.

### ISSUE THREAD

**Issue by jamesrascal** [twostairs/paperwork#558]
If you add a code block to a note with out setting the code type the note will render blank.
![2015-11-11_10-39-23](https://cloud.githubusercontent.com/assets/6054150/11099508/93f69b14-8860-11e5-9f8b-62b83ab3eeb2.png)

![2015-11-11_10-39-13](https://cloud.githubusercontent.com/assets/6054150/11099515/9aaf6d96-8860-11e5-8313-10ff7adc9740.png)

Once you define the code type the note will render correctly:

![2015-11-11_10-39-42](https://cloud.githubusercontent.com/assets/6054150/11099527/aae06e2c-8860-11e5-87f8-5cf203d756b3.png)

**Comment by Liongold** [comment]
This issue can be closed. A fix for it is available in our develop branch. If you encounter any issues, please open a new issue. Thanks for your contribution.
