### ISSUE TITLE
easy fix for paperwork demo

### ISSUE THREAD

**Issue by ninja-** [twostairs/paperwork#559]
so, demo.paperwork has been dead for quite a while.
but there's an easy fix - we could link to sandstorm demo + paperwork instance :+1:

**Comment by Liongold** [comment]
@JamborJan @ninja- Can someoen of you help with this and check if it's possible?

Anyone has any objection to this?

**Comment by JamborJan** [comment]
Ho guys, okay for me. Maybe it is possible to create a one click demo. I know it is available for other apps too. Maybe @jadeqwang is able to give some input?

The downsides from my point of view are: it is not the latest version, some UI elements are hidden as they are not usable in Sandstorm.

I'm off for the next two months so if I can be of any help it will be January. 

Cheers
JJ

**Comment by paulproteus** [comment]
Hi all,

The Sandstorm app market already runs a demo service for Paperwork: https://oasis.sandstorm.io/appdemo/vxe8awcxvtj6yu0vgjpm1tsaeu7x8v8tfp71tyvnm6ykkephu9q0

You can find that link by going to:

* https://apps.sandstorm.io/

* Look for Paperwork

* Click "Demo" if you see that button

https://docs.sandstorm.io/en/latest/administering/demo/#app-demos documents that in more depth!

**Comment by paulproteus** [comment]
@Liongold you should be able to use that link right now and link to it from the Paperwork website; let me know if that works for you!

**Comment by Liongold** [comment]
@paulproteus @JamborJan Thank to both of you. This has got to the next stage and I opened a pull request with the new information. If and when the pull request is accepted, then this issue will be fixed.

**Comment by Liongold** [comment]
Pull request accepted. Thanks for your feedback, help and availability. I'll close this issue now. Feel free to open a new one should you encounter any problems.
