### ISSUE TITLE
trying to upgrade: commit your changes or stash...

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#561]
1. So far, I updated paperwork:  "php artisan paperwork:update". Last updated a month ago. Now, I try "php artisan paperwork:update" and get "bla, bla, bla  commit your changes or stash them before You merge". How to properly do the updating - I dont want "stash", only new files copy in paperwork directory.

2. Where is in paperwork database (Mariadb) connect config ? In old version of paperwork I havent frontend/app/storage/db_settings file, but paperwork works properly

**Comment by jacek-1210** [comment]
because no one answered, I worked it out so, that I typed "git commit -a" and unhashed everything except      xxx.old.

And next, after go on paperwork page I get:

![paperwork1](https://cloud.githubusercontent.com/assets/13505686/11301153/198b066c-8f95-11e5-89f5-da2e1d319954.JPG)

![paperwork2](https://cloud.githubusercontent.com/assets/13505686/11301155/24394b78-8f95-11e5-9c84-4000437cc00e.JPG)

![paperwork3](https://cloud.githubusercontent.com/assets/13505686/11301162/2badf9a8-8f95-11e5-9204-abffa3260fcb.JPG)


What about "messages.setup.database_setup.database_form_label" field 
and why I must new first user account register ???

**Comment by Liongold** [comment]
You can skip the Setup Wizard if you want by following [this wiki page](https://github.com/twostairs/paperwork/wiki/Installing-and-configuring-Paperwork-without-using-the-Setup-Wizard). Admittedly, the wizard is not the best part of Paperwork and that it needs to be fixed. I can't promise any dates, however. I hope it isn't too much of an inconvenience for you. Sorry for not replying on your first message.

**Comment by jacek-1210** [comment]
I don't understand: I make db_settings file in paperwork/frontend/app/storage/  directory  and what write into db_settings file ?
E.g.:
>>>

mysql = database_name,
server = localhost,
port = 3306,
username = paperwork_user_name,
password = paperwork_user_password,

<<<

I this ok ? or:

>>>

database_name, localhost, 3306, paperwork_user_name, paperwork_user_password,


<<<

?

Where in paperwork are mysql settings ? In my old paperwork isn't "db_settings" file and all works good when I go back to old paperwork (copy/paste)  (?)

**Comment by jacek-1210** [comment]
Ohh yes, I write:

mysql, localhost, 3306, paperwork_user_name, paperwork_user_password


and work :)
