### ISSUE TITLE
Auto logout on time out

### ISSUE THREAD

**Issue by jamesrascal** [twostairs/paperwork#562]
When session times out page should refresh or log user out. 

Currently only a banner message is displayed that you session has timed out. As the user you need to click the logout button then login again.

**Comment by Liongold** [comment]
@jamesrascal Can you tell us what happens if you click on the notification? Does it reload or not?

**Comment by jamesrascal** [comment]
Red notification does not reload the page. Nothing in the console indicating an issue other than a 401 not authorized error. Unable to find any other errors.

**Comment by Baldrs** [comment]
Fixed in #568
