### ISSUE TITLE
Paperwork wrong show some notes

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#563]
Sometimes I have notes, which displays wrong:

Hedline is OK, but the content is blank:

![paperwork1](https://cloud.githubusercontent.com/assets/13505686/11410416/7ac1327c-93c7-11e5-8199-afe0960ba8d5.JPG)

or content is from different note:

![paperwork2](https://cloud.githubusercontent.com/assets/13505686/11410429/95df31c6-93c7-11e5-84e7-53bbdee91f36.JPG)

I dont know ? DB ? ( I have MariaDB) or paperwork ? Maybe the problem is text in the frame ? (I copy/paste from git):

![paperwork3](https://cloud.githubusercontent.com/assets/13505686/11410467/ea502e04-93c7-11e5-8c1a-37a861bfed45.JPG)

Edition note is OK, but after save is again wrong

**Comment by jamesrascal** [comment]
I can confirm this issue. In some cases when switching notes the content of the not will not change but will continue to show the previous notes content.

**Comment by Liongold** [comment]
Very strange and possibly serious issue. Can you try reproducing and posting an image of the Developer Tools console, please?

**Comment by jacek-1210** [comment]
"Can you try reproducing and posting an image of the Developer Tools console, please?"

Uppsss... how do it ? What "Developer Tools console" ? Demo page ?

**Comment by jacek-1210** [comment]
Thats it ? (hedline ok, content from different note):

![paperwork8](https://cloud.githubusercontent.com/assets/13505686/11472621/187c5466-976e-11e5-84fc-cef96e3bc2b5.JPG)

**Comment by Liongold** [comment]
I've opened a pull request for #558. I'm not 100% sure but it could fix this issue as well. So, please could someone of you test the branch or wait until the pull request is merged and then comment on whether this issue is fixed or not, please?

**Comment by jacek-1210** [comment]
Yes, probably problem is in frames (?) I edit and erase copy/paste text (in frame) and note works OK.

Try it: go to https://github.com/twostairs/paperwork/issues/469 

copy/paste selected frame with text into paperwork:

![paperwork13](https://cloud.githubusercontent.com/assets/13505686/11664435/06c5fca2-9de2-11e5-96ed-1d70b499a125.JPG)

and check it out

**Comment by Liongold** [comment]
This issue can be closed. A fix for it is available in our develop branch. If you encounter any issues, please open a new issue. Thanks for your contribution.

**Comment by jacek-1210** [comment]
The same problem come back :/  
I didnt have any time to upgrade paperwork (I have any problems with upgrade). Now, today I erased paperwork directory and make git clone (& reinstall in blank directory)
And again some notes are displayed incorrectly (is a title but no content)

I have copy before 2016-01-01 and it works properly

**Comment by Liongold** [comment]
@jacek-1210 Thanks for the information.
