### ISSUE TITLE
Files upload limit (?)

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#564]
When I'm trying to upload 14 files (eg. jpg's) into note, paperwork load only 10 files and not allow upload more files. Bug ? Limit ? Case ?

**Comment by jamesrascal** [comment]
What are you seeing in your error log? You may need to adjust your HTTP request length or max upload settings. Please provide your webservers error logs for further assistance.

**Comment by jacek-1210** [comment]
Normal, when I click "upload documents" in paperwork, open system window to select files. I select eg. 14 files and click "open". System window close. On paperwork, to upload, I see only 10 files.
Next I click "upload" in paperwork, upload 10 files. When I again click "upload documents", open system window, I select 1 file, click "open", system window close and reopen, but no file add in paperwork.  Dont help repeated attempts. I work on XP/Chrome (?)

**Comment by Liongold** [comment]
I've gone through the code and it should give you some sort of reply. Can you do this please: 
Go to Chrome Menu > Developer Tools (don't know which sub menu right now sorry). When it opens up, go to Network tab and then after that loads (if it contains some rows already, click clear at the top), try the upload. A row should be added then showing the request. Could you take a screenshot of it after clicking on the URL (it should open a part containing some tabs - please screenshot the Preview tab). This is so we help you. I agree some improvements could be done for this. They'll be done hopefully soon.

**Comment by jacek-1210** [comment]
My english is not very well. Is it ?:

![paperwork9](https://cloud.githubusercontent.com/assets/13505686/11633512/0117b7f4-9d0c-11e5-8cae-e7e1de5162b0.JPG)


on the same server (linux) and same xp/chrome computer I have resourcespace (for fotos) and at once I add hundreds files and work ok.

On paperwork:

I select 15 files:

![paperwork10](https://cloud.githubusercontent.com/assets/13505686/11633608/870059a2-9d0c-11e5-83a3-1a3c81eb2a73.JPG)


and get 10 files, and no more:

![paperwork11](https://cloud.githubusercontent.com/assets/13505686/11633623/a24083c2-9d0c-11e5-8c86-4a11e8676dd9.JPG)

**Comment by Liongold** [comment]
@jacek-1210 This isn't an actual bug. There's a limit imposed on notes limiting them to upload a maximum of 10 files. The reason for this is what I'm not sure about?

What do you all think? Should this be removed or increased?

**Comment by jacek-1210** [comment]
I may be wrong, but I think that the limit is not needed or increase it. db should deal with it (?). (maybe the problem is that the paperwork remembers various editions and this takes the disk resources ? If not, I think that the limit is not needed) In my case, the problem was, that the paperwork is not reading pdf. I need upload in paperwork some manuals and view them on paperwork. So, I thought, manuals pages scan and throw as jpg's. And here I stopped at the limit

**Comment by Liongold** [comment]
What do you mean by "not reading pdf"?

**Comment by jacek-1210** [comment]
This:

![paperwork4](https://cloud.githubusercontent.com/assets/13505686/11664572/e77ed30e-9de2-11e5-9444-44f3c50de1c9.JPG)

in red field I will see content of pdf, but I see only link to pdf. I can download this link and open, but it is easier to read directly in the notebook

**Comment by jamesrascal** [comment]
PDF reading is not something that has been implemented see #535

**Comment by jacek-1210** [comment]
Yes, and from https://github.com/twostairs/paperwork/issues/535 

"That isn't possible for PDFs right now. You can have that effect for images if you put the image in the note itself (not as an attachment)"

So, I try upload images and stop at upload limit :)

**Comment by jacek-1210** [comment]
Please, increase limit of upload files from 10 to min. 20-30 files. For me, optimal would 50 files

**Comment by jacek-1210** [comment]
Probably next some limit: try copy/paste eg. this www: http://vp-systems.eu/manual_cr.html  - load up on paperwork only part of the whole www page :(

**Comment by Liongold** [comment]
Now, the maximum number of attachments in a note can be set in config.php. Please recheck whether this bug is still valid.

**Comment by jacek-1210** [comment]
Hi,

I had no time to take paperwork update. Now I look for config.php and can't find this in ../frontend/.. . Is it paperwork file ? Or apache file ?

**Comment by Liongold** [comment]
@jacek-1210 This can be found in frontend/app/config/paperwork.php file. It's the last setting at the bottom. Let us know if there are any problems.

**Comment by jacek-1210** [comment]
paperwork.php it's: 

https://github.com/twostairs/paperwork/blob/master/frontend/app/config/paperwork.php

Last setting bottom is line no. 174      'purgeTagList' => ['script'],   

Change 'script' on eg. '30'  ?

**Comment by Liongold** [comment]
@jacek-1210 Are you using the develop branch?

**Comment by jacek-1210** [comment]
thx, after switch to develop branch is ok
