### ISSUE TITLE
Moving note into another notebook

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#570]
If I choose notebook, next click note and next go to upper bar Edit->move note, choose another notebook and click "select", I get error "Something went wrong...."

Anytime

**Comment by w00p** [comment]
Hi, i have the same problem. Is there a fix for this?

**Comment by jacek-1210** [comment]
Hi,
 
Yes, its fixed on December 2015, works ok
 
 
 
 
W dniu 2016-02-02 09:49:45 użytkownik w00p <notifications@github.com> napisał:
Hi, i have the same problem. Is there a fix for this?
