### ISSUE TITLE
paperwork_settings is not working

### ISSUE THREAD

**Issue by morskipas** [twostairs/paperwork#573]
If  I disable functions in config file "paperwork_settings" like this
_debug: true
registration: false
forgot_password: false
showIssueReportingLink: false_
all of the disabled functions are still enabled at the start page.

Also in case edit the paperwork.php in directory config
_'registration' => false,_
the registration is still available

**Comment by Liongold** [comment]
Sorry for the late reply, even on your mailing list post. Thanks for telling us of this issue. A fix is in a pull request, which hopefully fixes your issue.

**Comment by morskipas** [comment]
Thx for your answer, unfortunately the change of the file paperwork.php was not helpful :-(
I changed the file like this

old -->    $configLines = explode(**"\r\n"**, $configString);
new -->    $configLines = explode(**PHP_EOL**, $configString);

**Comment by morskipas** [comment]
Hi Linongold,

I found one more thing abaut the problem. 
I changed now directly the paperwork.php
*'registration' => false,*
No effect, the registration function is still there. But now I deleted the file paperwork_settings in the storage folder ... and noe it works :-)

**Comment by Liongold** [comment]
@morskipas Sorry for the late reply. Paperwork will be getting a new Setup Wizard soon which will change the configuration part of Paperwork. Since you currently have a workaround, I suggest you wait a little until the new wizard is pushed, if you don't have any problems with that.

**Comment by morskipas** [comment]
No worries ... it's christmas :-)
Yes, I totally agree .... this workaround is more than enough

Thanks for your reply

**Comment by Liongold** [comment]
The setup wizard has been rewritten. Please recheck this bug.

**Comment by davidtorcivia** [comment]
I'm on the latest stable build installed fresh (today). I manually edited the paperwork_settings file to read "registration: false" but the registration link is still present and functioning.

**Comment by Liongold** [comment]
This issue should be fixed in the develop branch. Are you using this branch? Which file did you edit?

**Comment by davidtorcivia** [comment]
Ah, my error there. I'm on the master branch, that explains why my edit didn't affect this!

**Comment by Liongold** [comment]
Should this be closed then?

**Comment by Liongold** [comment]
Since the last reply in this issue, the Setup Wizard has been rewritten. Thus, this issue will be closed. If anyone encounters any new issues with Paperwork, please open a new issue.
