### ISSUE TITLE
copy/paste hyperlink problem

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#575]
When I copy hyperlink:

![paperwork16](https://cloud.githubusercontent.com/assets/13505686/11907560/22089d12-a5d5-11e5-9f84-b11fdf88565b.JPG)

and paste into paperwork, i get normal text, not hyperlink :(  Only if "upload -> insert", hyperlink is right genrated:

![paperwork17](https://cloud.githubusercontent.com/assets/13505686/11907586/694d6680-a5d5-11e5-8719-3de094704c0c.JPG)

**Comment by morskipas** [comment]
It think it works as disigned, you can use the "link" option/format from the CKEditor.
If you copy a real link for an internet page it works as a link after pasting it to paperwork.

**Comment by jacek-1210** [comment]
I don't use CKEditor. It isn't a big problem, but in the future, IMO it would be better if it worked so, that paperwork independently would recognize "http://....." and automatically would create hyperlink, as do other editors.
So, if I copy/paste all html page, links in this page copy with the correct hyperlinks

**Comment by morskipas** [comment]
Hi jacek, yes of course it would be nice if paperworks recognize automatically if everything started with http:// or https:// is a hyperlink.

Just a short question, do you replaced the CKEditor by something else? Or why don't you use the CKEditor, it integrated and not so bad.

![paperwork](https://cloud.githubusercontent.com/assets/6042276/11914886/f161acd0-a68d-11e5-9809-5c33775f7a96.png)

**Comment by jacek-1210** [comment]
Thx for Your help !  I had no idea, that the paperwork has built-in editor :)))))
OK, link in CKE works me as hyperlink 
 
 
 
 
 
W dniu 2015-12-19 20:21:02 użytkownik morskipas <notifications@github.com> napisał:
Hi jacek, yes of course it would be nice if paperworks recognize automatically if everything started with http:// or https:// is a hyperlink.
Just a short question, do you replaced the CKEditor by something else? Or why don't you use the CKEditor, it integrated and not so bad.
