### ISSUE TITLE
Switch to bower?

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#58]
Not sure, whether it would be a good idea to switch to Bower for managing all JavaScript libraries needed and (currently) maintained manually within `/app/js/`.

What are the pros and what are the cons of switching to Bower?

**Comment by ponychicken** [comment]
The only con I see is that you might have to reorganize the folder structure a bit. Bower components will contain a lot of file you don't want (tests etc), so it would be sensible to have a gulp or grunt task to concat/minify/copy/whatever the files to the place you want.

**Comment by devilx** [comment]
@ponychicken thanks! So, what would be the pro, compared to the current setup? We wouldn't have to keep the libraries within our Git repository, since every user could fetch them on their own, using the bower.json – but that's pretty much it, right?

**Comment by ponychicken** [comment]
Keeping the dependencies up to date is pretty much the one. You can use semver to get patch/minor updates automatically and use `bower list` to see which one got a major update.

**Comment by Baldrs** [comment]
Done in #306

**Comment by Baldrs** [comment]
Merged into develop.
