### ISSUE TITLE
Can't Upload all Documents

### ISSUE THREAD

**Issue by wuggenid** [twostairs/paperwork#580]
I have a problem uploading a document when editing a note.
If i press "Upload document...", choose my document and select it, the file select window closes and opens up again. If i press cancel it does the same. After it closes and opens 5 times, it stays closed, but there is no file uploaded.

This doesn't happen everytime and with every file, but with most of them...

Thank you for helping, paperwork rocks!

**Comment by ovizii** [comment]
I think not all file types are allowed. 
I can upload .PDF without problems but not.XLS

**Comment by ovizii** [comment]
Found another workaround: instead of selecting the file from Paperwork, just drag and drop the file and it should work.

**Comment by Liongold** [comment]
More info on how to replicate this issue is needed. Please include screenshots (if possible), the branch you are running and clear instructions and description of the problem. If possible, please provide information about the browser and OS being used. Thanks for your feedback.

**Comment by ovizii** [comment]
OK, I jsut realized I was on the wrong github page as I am having this issue with the sandstorm version of paperwork: https://github.com/JamborJan/paperwork 
If you still want details I can supply, otherwise I'll open a new issue over there.

**Comment by Liongold** [comment]
It's better if you open an new issue in that page then. Thanks for your feedback.

**Comment by JamborJan** [comment]
Hey @ovizii thanks for finding the issue. I'll take a look at it. I can confirm that the described behavior can be reproduced and that the workaround works.

https://github.com/JamborJan/paperwork/issues/44

**Comment by nebulade** [comment]
Using the HEAD revision of paperwork dumps an angular error in the webinspector console for both firefox 53 and chromium 56, rendering both file upload methods (dialog and drag'n'drop) unusable:
```
Error: [$parse:syntax] Syntax Error: Token 'undefined' not a primary expression at column null of the expression [maximumAttachmentsPerNote=] starting at [maximumAttachmentsPerNote=].
http://errors.angularjs.org/1.2.32/$parse/syntax?p0=undefined&p1=not%20a%20…on&p2=null&p3=maximumAttachmentsPerNote%3D&p4=maximumAttachmentsPerNote%3D
    at https://example.com/js/angular.min.js:78:12
    at Parser.throwError (https://example.com/js/angular.min.js:10654:11)
    at Parser.primary (https://example.com/js/angular.min.js:10629:14)
    at Parser.unary (https://example.com/js/angular.min.js:10877:19)
    at Parser.multiplicative (https://example.com/js/angular.min.js:10860:21)
    at Parser.additive (https://example.com/js/angular.min.js:10851:21)
    at Parser.relational (https://example.com/js/angular.min.js:10842:21)
    at Parser.equality (https://example.com/js/angular.min.js:10833:21)
    at Parser.logicalAND (https://example.com/js/angular.min.js:10824:21)
    at Parser.logicalOR (https://example.com/js/angular.min.js:10812:21) <div ng-controller="FileUploadController" class="file-upload-wrapper ng-scope" uploader="uploader" nv-file-drop="" filters="queueLimit, customFilter" ng-init="maximumAttachmentsPerNote=">
(anonymous) @ angular.min.js:10160
(anonymous) @ angular.min.js:7427
nodeLinkFn @ angular.min.js:6762
compositeLinkFn @ angular.min.js:6156
publicLinkFn @ angular.min.js:6052
link @ angular.min.js:23740
nodeLinkFn @ angular.min.js:6779
compositeLinkFn @ angular.min.js:6156
publicLinkFn @ angular.min.js:6052
boundTranscludeFn @ angular.min.js:6176
controllersBoundTransclude @ angular.min.js:6800
update @ angular.min.js:23690
$broadcast @ angular.min.js:13146
(anonymous) @ angular.min.js:23372
wrappedCallback @ angular.min.js:11735
wrappedCallback @ angular.min.js:11735
(anonymous) @ angular.min.js:11821
$eval @ angular.min.js:12864
$digest @ angular.min.js:12676
$apply @ angular.min.js:12968
done @ angular.min.js:8479
completeRequest @ angular.min.js:8693
xhr.onreadystatechange @ angular.min.js:8632
ckeditor.js:913 Detecting changes using MutationObservers
```

**Comment by Liongold** [comment]
@nebulade Please try clearing your cache and try again. Please use the latest version and when writing a report, please mention the code included in the Settings page > About tab. If you encounter this problem again, please try again.

**Comment by Liongold** [comment]
Since the bug report has been open for more than a year and been pending feedback since May, this issue will be closed. If anyone re-encounter this issue, please open a new one. Thanks for your feedback and use of Paperwork.
