### ISSUE TITLE
Moving storage directory

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#581]
I use paperwork not only for notes, but for storage different files. Storagedir is bigger and bigger. Now, storage dir is  paperwork/frontend/app/storage/attachments. If I upgrade paperwork, I copy/paste all paperwork directory with bigger storagedir and next git pull. It is a bit annoying. Is it possible (now or in the future) to moving storagedir e.g. in paperwork/storagedir (paperwork/attachments) ?

**Comment by Liongold** [comment]
@jacek-1210 Sorry for the delay in replying. Yes, it should be possible to change the attachments folder by changing the config setting in paperwork.php (probably in line 110). The storage_path() is a helper function that returns the paperwork/frontend/app/storage part of the filename. Does this fix the issue for you?

**Comment by jacek-1210** [comment]
I'm not sure: how correctly write new directory ? I have paperwork eg. in /srv/www/paperwork. I move files and directories from ./attachments into /srv/www/paperwork_attachments directory and change paperwork.php line 110 
from 
'directory' => storage_patch() . '/attachments'
to
'directory' => '/srv/www/paperwork_attachments'
and isnt work :(

**Comment by Liongold** [comment]
@jacek-1210 Can you try doing, temporarily, `die($array['attachmentsDirectory']);` in the line before the return in config/paperwork.php. That way you can compare what you're putting with what you get there. Maybe that is the problem. Also, make sure that you change permissions in a way to allow Laravel to create and move files and directories in it. If it still doesn't work, please show what error you're getting.

**Comment by jacek-1210** [comment]
Thx, work.
 at first time I change directory:

![pwork1](https://cloud.githubusercontent.com/assets/13505686/13889058/d8134362-ed44-11e5-9fe4-1be930bdec68.JPG)

and no results, no jpgs etc.:

![pwork2](https://cloud.githubusercontent.com/assets/13505686/13889084/000b28bc-ed45-11e5-83bb-706d4742aa11.JPG)


Now I change attachmentsDirectory:


![pwork3](https://cloud.githubusercontent.com/assets/13505686/13889111/1ce05b4c-ed45-11e5-8287-e2945f72922e.JPG)


and work:

![pwork4](https://cloud.githubusercontent.com/assets/13505686/13889126/2b71017a-ed45-11e5-9c0d-d3fd5a66b73e.JPG)


Interestingly, even if I delete the directory:

![pwork5](https://cloud.githubusercontent.com/assets/13505686/13889157/5314bc80-ed45-11e5-89df-2a7492217acc.JPG)


paperwork work correctly - I don't notice problems
