### ISSUE TITLE
Where to get API Hash?

### ISSUE THREAD

**Issue by MrPurplz** [twostairs/paperwork#588]
Hi,

This is perhaps a very basic question but I'm not sure where I generate/locate the hash used for authenticating to the API.

[The documentation](http://docs.paperwork.apiary.io/#reference/notebooks/notebooks-collection) states one method of authentication is:

> by providing auth information through a regular HTTP Basic Auth header: Authorization: Basic hash

I've looked through the settings pages and can't locate it.

**Comment by techknowlogick** [comment]
In the documentation there is a sample auth header being sent `Authorization:Basic dGVzdEBwYXBlcndvcmsucm9ja3M6dGVzdDEyMw==` and that hash base64 decodes to `test@paperwork.rocks:test123`.

So it's just your email/pass separated by `:`

More information about this can be found here: https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side

Note: As this passes your auth creds in plaintext I highly recommend using HTTPS when communicating with the API.

**Comment by Liongold** [comment]
I think this issue can thus be closed. Thanks for your interest in Paperwork. Feel free to open new issues or using Gitter.
