### ISSUE TITLE
Paperwork Cloudron App

### ISSUE THREAD

**Issue by gramakri** [twostairs/paperwork#597]
Thanks for paperwork! We made a Cloudron app for Paperwork (The Cloudron is a smartserver on which you can install apps and manage users).

We have been following paperwork for quite a while now and keep it updated. The app source is at https://github.com/cloudron-io/paperwork-app. We also have selenium based integration tests under https://github.com/cloudron-io/paperwork-app/tree/master/test.

Do you think it's possible to get us listed in the README.md or the paperwork.rocks site as an installation option?

**Comment by gramakri** [comment]
If you want to try a demo, https://my-demo.cloudron.me (username: cloudron password: cloudron).

I installed paperwork there, but you can install it again if someone removed it. It's complete paperwork with no features removed (and Cloudron app's generally reside outside the main project). It's got LDAP integration in place to integrate with Cloudron's user management.

If the app/Cloudron sounds interesting, please let me know and I can add you guys to the app repo. Feel free to contact me by mail as well (email in profile).

**Comment by Baldrs** [comment]
Hey, yet another sandstorm.io

**Comment by Baldrs** [comment]
@JamborJan

**Comment by Baldrs** [comment]
@gramakri I think we can if sandstorm integration by @JamborJan will be also added

**Comment by JamborJan** [comment]
Hey @gramakri please give me some time to check out your project and how it is done and I will create a proposal for the part mentioning your project on the readme. I'll come back to you asap.

**Comment by JamborJan** [comment]
Hey @gramakri I quickly checked your demo, it's running quite good. Some questions:
1. Is there any mission your project follows? Whats your story in few words?
2. Is your project also open source? What is the license and what are terms of services you use (I didn't dig into that would be cool if you can provide a short answer here).
3. I have seen you have linked us already in the app store, could we improve that a bit? I would be willing to send you a proposal
4. How do you run updates when we update our repository?

Thanks!

**Comment by gramakri** [comment]
To be clear, no code changes are required on your end in paperwork to run on the Cloudron. We package and preconfigure apps to run sandboxed with our single sign on.

To reply to your questions:
1. We provide private single-tenant servers for each customer. The idea here is individuals and companies can decide which region to use to host their apps and data (for example, one might want all their servers in europe). The focus is to provide a easy UI for anyone to have their own server and automate all aspects of server management.
2. Our project is not opensource. Our current focus is to get our business model right before we move in that direction (which is to say, we are not against opensourcing, we just haven't decided yet).
3. Yes, we would love to have you guys contribute. I will add you to the repo. It's simply a matter of fixing the DESCRIPTION.md and changes to CloudronManifest.json for different screenshots.
4. We track paperwork upstream releases. We have selenium tests on our side specific to paperwork (the tests install paperwork, creates notes etc and verify that paperwork works correctly on Cloudron for each update. tests are at https://github.com/cloudron-io/paperwork-app/tree/master/test). Once the tests pass, we create a new release for the paperwork app and all Cloudrons automatically get this update.

Currently, our app store does not have paid apps. But it will be great to start a conversation with you on how we can contribute back to paperwork.

Thanks!

**Comment by gramakri** [comment]
@JamborJan @Baldrs i have added you to the cloudron-io/paperwork-app repo.

**Comment by JamborJan** [comment]
Hi @gramakri , I was not able to find the ```DESCRIPTION.md``` I guess you mean I only have to change  the ```CloudronManifest.json```right? Any chance that I can place pictures in your repo? Just in case when we update our repo and change / remove picture it will break your app store. Not a good idea I guess.

**Comment by gramakri** [comment]
@JamborJan I fixed the repo now to use a DESCRIPTION.md. Feel free to fix it as you see fit (I removed the obvious quoting typo).

Good point about the screenshots, fixed that as well.

**Comment by JamborJan** [comment]
Hey @gramakri done! I updated the description, added new screenshots and also proposed the change of our readme.md (see https://github.com/twostairs/paperwork/tree/Readme-Partner-Info). 

Thanks for hosting Paperwork and watch out for amazing updates coming!

**Comment by gramakri** [comment]
@JamborJan thanks! I pushed it to the store - https://cloudron.io/appstore.html?app=rocks.paperwork.cloudronapp
