### ISSUE TITLE
Some problem with new note after last upgrade

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#607]
After last upgrade I have some problem: often after touch "new note" I get this window:

![paperwork20](https://cloud.githubusercontent.com/assets/13505686/14244944/665eec9a-fa5e-11e5-8747-3d39e0e497ad.JPG)

![paperwork18](https://cloud.githubusercontent.com/assets/13505686/14244963/7c02783c-fa5e-11e5-9270-561b27b1d40c.JPG)

(Isn't button)

next, after reload page I get:

![paperwork19](https://cloud.githubusercontent.com/assets/13505686/14244978/8c4ea7a6-fa5e-11e5-993a-42ab4aee3ea5.JPG)

with title "Untitled". Previously there were no such this problems

(Win XP + Chrome). Someone else has these problems?

**Comment by Liongold** [comment]
@jacek-1210 Please update Paperwork and try again.
