### ISSUE TITLE
No Login Window

### ISSUE THREAD

**Issue by ccuellar14** [twostairs/paperwork#609]
Hi,

I have a problem on final config at PaperWork, in final step in confirmation create account, for a post login, no loading next window.

Attached File demo
![image](https://cloud.githubusercontent.com/assets/16178871/14443778/ed372874-0006-11e6-9f47-0f4a900c18ae.png)

**Comment by Liongold** [comment]
@ccuellar14 Can you update Paperwork (develop branch) and try again please?

**Comment by wongalvis** [comment]
I think this specific issue only occurs in that old version, after updating it should be fine.

**Comment by Liongold** [comment]
Since there hasn't been a reply on this issue and another user has confirmed this issue is fixed, I'll close this issue. If anyone encounters this issue again, please reopen this issue.
