### ISSUE TITLE
"Previous" button should not appear in step 1 of Setup Wizard

### ISSUE THREAD

**Issue by wongalvis** [twostairs/paperwork#612]
In the Setup Wizard, the "Previous" as well as the "Next" button appears at the bottom. However, the "Previous" button should not appear in step 1, although nothing happens when clicking it. It could be disabled or hidden as a resolution to the issue.

**Comment by Liongold** [comment]
I've opened a pull request for this and some minor changes in the CSS applied for mobile devices. Thanks for your help.

**Comment by Liongold** [comment]
The pull request has been merged. Thus, I'll close this issue. Thanks for your help and contribution to Paperwork.
