### ISSUE TITLE
postgresql support broken ?

### ISSUE THREAD

**Issue by foxmask** [twostairs/paperwork#615]
I tried to install paperwork with postgresql, then I meet this error after entering the command `php artisan migrate`

from app/storage/logs/laravel.log

```
125:[2016-05-07 15:37:25] production.ERROR: exception 'PDOException' with message 'SQLSTATE[23502]: Not null violation: 7 ERROR: a NULL value violates the NOT NULL constraint for the column « created_at »
148:Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23502]: Not null violation: 7 ERREUR:  a  NULL value violates the NOT NULL constraint for the column « created_at »
```

**Comment by Liongold** [comment]
Which branch are you using? Also, are you using the Setup Wizard?

**Comment by foxmask** [comment]
I made my installation from https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Debian-7 for debian 8

**Comment by foxmask** [comment]
I checked what [was the none setup wizard installation](https://github.com/twostairs/paperwork/wiki/Installing-and-configuring-Paperwork-without-using-the-Setup-Wizard), and no I didnt use Wizard. But I had to debug how paperwork check the RDBMS to use postgresql and found to create a file db_settings and just put `pgsql,̀ in it.

**Comment by Baldrs** [comment]
AFAIK we never supported postgres anyway, so it is not done, not broken.

**Comment by foxmask** [comment]
on another side, there is PDO which permits to use it

**Comment by foxmask** [comment]
it looks lie that this pass when doing 

```php
        Schema::create('languages', function (Blueprint $table) {
            $table->char('id', 36)->default(null)->primary();
            $table->char('language_code', 7);
            $table->nullableTimestamps();
            $table->softDeletes();
            $table->engine = 'InnoDB';
        });
```
in the file 2014_07_22_194050_initialize.php 
where `$table->timestamps()` becomes `$table->nullableTimestamps()` as I could finish to run artisan migrate: 

```bash
foxmask@foxmask:~/paperwork/frontend $  php artisan migrate
**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? y
Migration table created successfully.
Migrated: 2014_07_22_194050_initialize
Migrated: 2014_07_24_103915_create_password_reminders_table
Migrated: 2014_10_08_203732_add_visibility_to_tags_table
Migrated: 2015_01_21_034728_add_admin_to_users
Migrated: 2015_05_05_094021_modify_tag_user_relation
Migrated: 2015_05_22_220540_add_version_user_relation
Migrated: 2015_06_15_224221_add_tag_parent
Migrated: 2015_06_30_125536_add_sessions_table
Migrated: 2015_07_29_130508_alter_versions
```
I know that this is not the right place to do this "alter" but as I really dont know how to write a migration script, I give a solution "as is" that you could use ;)

**Comment by Baldrs** [comment]
If it works with mysql/mariadb, I think we can introduce this fix

**Comment by Liongold** [comment]
@foxmask Do you want to open a pull request with this fix?

**Comment by Liongold** [comment]
Actually, there seems to be more than one way to fix this. It seems that the timestamps can effectively be removed from the languages table since they do not seem to be used. Then, another way would be to change the insert statements in the migrate file to include the timestamps. 

@mrusme What do you think should be done here?

**Comment by foxmask** [comment]
@Liongold unfortunatly, i cant. I'm just a curious user who spotted an issue :)

**Comment by Liongold** [comment]
@foxmask A pull request has been merged which should help with your issue. Can you pull the latest changes to the develop branch and try again, please?

**Comment by kuc** [comment]
Tried postgres with latest master branch, still same error in logs.

**Comment by kuc** [comment]
OK, I think that I get it:

1. Laravel, when using `$table->timestamps();`, creates fields `created_at` and `created_at` with type `timestamp`
2. MySQL does it's weird, specific shit, as usual: http://stackoverflow.com/questions/22860351/mysql-column-type-timestamp-implicitly-includes-not-null-default-current-time
3. Postgres does what is told to do
4. Aaand we have database errors on every INSERT.

So we need to change all
```
$table->timestamps();
```
to
```
$table->timestamps()->default(DB::raw('CURRENT_TIMESTAMP'));
```
and it should work.

**Comment by kuc** [comment]
Hmm, seems that Laravel 4.2 doesn't support altering columns, only 5.0+ does :disappointed: 
I will use `DB::statement` then...

**Comment by kuc** [comment]
This is now fixed in `develop` branch.

**Comment by Liongold** [comment]
This issue will thus be closed then. Thanks for your feedback. If you have any feedback, please open a new issue.
