### ISSUE TITLE
Blank popup shown after clicking "New Note" when selecting "All Notes"

### ISSUE THREAD

**Issue by wongalvis** [twostairs/paperwork#619]
When "All Notes" is selected, clicking File > New Note will result in a blank popup as shown.

![screencapture-13-84-154-69-1463299773130](https://cloud.githubusercontent.com/assets/6073063/15272810/b697d1c6-1ab7-11e6-9a2a-ee89380f6113.png)

**Comment by Liongold** [comment]
This issue has been fixed. IOf you re-encounter it, please open a new issue. Thanks for your feedback.
