### ISSUE TITLE
Paperwork wrong show some notes - again :(

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#641]
Old issues: #563 & #553

The same problem come back :/

I didnt have any time last months to upgrade paperwork (I have any problems with upgrade). Now, today I erased paperwork directory and make git clone (& reinstall in blank directory)
And again some notes are displayed incorrectly (is a title but no content)

I have copy before 2016-01-01 and it works properly

**Comment by Liongold** [comment]
@jacek-1210 Can you show the version you are using? You can check it from the Settings > About tab. There should be a code. Can you post it here?

**Comment by jacek-1210** [comment]
Hmmm, very sorry, now, after copy/paste new version into paperwork directory (after problems I back to the old version) it works (?) Earlier it has not worked. I don't know - I messed versions (?)  Where is About Tab ? Under Settings I have only this:

![paperwork21](https://cloud.githubusercontent.com/assets/13505686/16244485/90e7302c-37fc-11e6-8876-03464cef024e.JPG)

?

**Comment by Liongold** [comment]
Are you on develop branch (code `bd1c58d7ba1f400b4a42e21520b31084a67317eb`)?

**Comment by jacek-1210** [comment]
I don't know how check it (?) The only source of paperwork I know, is git.
Year ago I make ( #469 ):

cd /www
rm -rf paperwork
git clone https://github.com/twostairs/paperwork.git
cd paperwork/frontend
composer install
php artisan paperwork:install



next months I make "php artisan paperwork:update", until now. Now I get some errors via update, primarily from npm, gulp & bower. So, I clear paperwork directory & again "git clone https://github.com/twostairs/paperwork.git". I thought, I download stable versions (?) It's wrong ?
I don't know, where look for (code bd1c58d7ba1f400b4a42e21520b31084a67317eb) etc. In my paperwork don't see "about program" "?" etc. buttons (?) How check: is develp branch or not ?

**Comment by Liongold** [comment]
Run `git checkout develop`, then the usual install commands (backup your paperwork database - it may overwrite). The latest code is in the develop branch.

**Comment by jacek-1210** [comment]
OK, thx, with small problems I was able to switch to develop. Without loss of the database.
& all works, no bugs

Sorry for lamer questions, but I don't know much about git, git branch etc.

So, now correct update is still "php artisan paperwork:update" ?

& how to correctly instal paperwork in blank directory:

cd /www
rm -rf paperwork
git clone https://github.com/twostairs/paperwork.git
CD PAPERWORK                    <--- ????? (of course lowercase)
GIT CHECKOUT DEVELOP      <--- ????? (of course lowercase)
cd frontend
composer install
php artisan paperwork:install


This is a good idea ?

**Comment by Liongold** [comment]
@jacek-1210 The answer to the second question is yes, that's correct. You can do `cd paperwork/frontend` in the first cd and then skip the second cd directly if you want to but it's good. About thew update, I think it should work. However, I have not tested it. You are free to test it and report any issues you encounter. If you do not have any other queries, please close the issue.
