### ISSUE TITLE
RFE: Allow admins to register new users whether "registration" is true or false

### ISSUE THREAD

**Issue by strikerttd** [twostairs/paperwork#644]
I would like the ability to be added for Admins to register new users (possibly some registration ability added under -admin area-) whether 'registration' is true or false.  This will allow small teams who are a part of large organizations to better manage their own Paperwork servers.

**Comment by Liongold** [comment]
This has now been fixed. If you encounter any new issues, please open a new issue. Thanks for your contribution.
