### ISSUE TITLE
Bug: A blank note will show the last viewed note that has information in it

### ISSUE THREAD

**Issue by strikerttd** [twostairs/paperwork#647]
Description:
 - When selecting a blank note after viewing one that has information in it, the information from the previous note will show in the body of the blank one.

Reproduce:
 1. Create a note with a subject, tags and a body.
 2. Create a blank note.
 3. Click the note that has information.
 4. Click the blank note.

Notice the body of the note with information carries over into the blank note.

**Comment by Liongold** [comment]
This has been fixed. Thanks for your feedback. If you encounter any issue please open a new issue.
