### ISSUE TITLE
Error in file naming preventing loading 

### ISSUE THREAD

**Issue by wassimseif** [twostairs/paperwork#658]
When setting up the app and the database, it creates a `/app/storage/config/database1.json`file. but in the` index.php` file this code is executed before running the app 

```
    if(!file_exists("../app/storage/config/setup") ||
        file_get_contents("../app/storage/config/setup") == 3 && !$_SERVER['HTTP_X_REQUESTED_WITH'] ||
        file_get_contents("../app/storage/config/setup") == 4 && !$_SERVER['HTTP_X_REQUESTED_WITH'] ||
        file_get_contents("../app/storage/config/setup") == 6 && !$_SERVER['HTTP_X_REQUESTED_WITH'] ||
        file_get_contents("../app/storage/config/setup") == 5 && !$_SERVER['HTTP_X_REQUESTED_WITH'] ||
        !file_exists("../app/storage/config/paperwork.json") && !$_SERVER['HTTP_X_REQUESTED_WITH'] ||
        !file_exists("../app/storage/config/database.json") && !$_SERVER['HTTP_X_REQUESTED_WITH']) {

            header("Location: setup.php");
```
if checks for `/app/storage/config/database.json`
i had to rename the database1.json to database.json in order to run the app

**Comment by Liongold** [comment]
Thanks for noticing this. In reality, this issue has been fixed in the develop branch but not in master branch. Thanks for your feedback. I hope develop will be merged to master again soon. 

Do you think this issue can be closed then?
