### ISSUE TITLE
Evernote import: "You must choose an ENEX file!"

### ISSUE THREAD

**Issue by artin-phares** [twostairs/paperwork#666]
Imperatively found that when you try to import .enex file which size is > 2MB:
`The import failed. The technical error message is: You must choose an ENEX file!`

**Comment by Liongold** [comment]
Can you dump the contents of `$e->getMessage()` in line 72 of `frontend/app/lib/Paperwork/Import/EvernoteImport.php`, please? That should give you more information about what is happening? Otherwise you can check the error log file.

**Comment by artin-phares** [comment]
It was actually PHP limit in my environment.
Fixed that in `php.ini` (increased `upload_max_filesize ` and `post_max_size`)
