### ISSUE TITLE
Evernote import: "simplexml_load_string(): Entity: line 3: parser error : EntityRef: expecting ';'"

### ISSUE THREAD

**Issue by artin-phares** [twostairs/paperwork#667]
Error message:
`simplexml_load_string(): Entity: line 3: parser error : EntityRef: expecting ';'`

Source [.enex](https://github.com/twostairs/paperwork/files/435239/evernote_parser_error.enex.gz)

**Comment by Liongold** [comment]
Do you think it is possible to post your source files on a public website such as Github?

**Comment by artin-phares** [comment]
Not sure what you mean. There's link to source .enex in original post..

**Comment by Liongold** [comment]
I mean something like Github Gist or something similar. If you can't, it's not madatory. It just would make it more accessible.

**Comment by artin-phares** [comment]
Moved them to github.  
ps. weird thing, github does not allow .zip for attachments, but .gz is ok..

**Comment by JamborJan** [comment]
Hey guys, this issue is happening when you have a character in your tags for example wich is encoded in HTML special characters: for example if you use a tag `B&B` its is appearing in the enex file you export as `B&amp;B` and this is the point where the import fails.

I'll try to find out what happens here and send a PR to the dev branch.

**Comment by JamborJan** [comment]
As mentioned here: https://github.com/JamborJan/paperwork/issues/27#issuecomment-137203848

The paperwork export is not working as expected, it is not dealing with `&` the way it should in the note name and tags. Thats why I tried to make it more robust in this commit here: https://github.com/JamborJan/paperwork/commit/0182edf2624ce4faa6b6499d910583cdb2df2ee8

This was not a good solution. I tested now a lot more and found a solution which might work better.

But there are still a lot of issues. The used PHP method `SimpleXML_load_string` seems to me super weak or at least you can not set a acceptable tolerance rate where the import should keep going and ignore errors.

**Comment by Liongold** [comment]
@JamborJan Can this be closed then?
