### ISSUE TITLE
Editing a note then clicking library to go home is blank

### ISSUE THREAD

**Issue by jeremye77** [twostairs/paperwork#673]
When I am finished editing a note I often click library to go back home. The link target is "/#" which leads to a blank page. Oddly...when I click the Paperwork logo to go home it works fine...though that seems to actually be a link to the note I was editing. Target "/#/n/00000000-0000-0000-0000-000000000000/0d95e137-29ce-4dcc-bd68-bf283249a0c6" That is fine...better than blank. 

It seems for some reason "/#" is a blank page but if I was to load "/#/" it would work fine. That is unless Chrome pulled something from history. I was fighting with the URL bar to load what I wanted.

I did a git pull...indicating this is in the most recent version but I can recall it happening for some time I just hadn't gotten around to reporting it. (sorry)

I am sorry I do not have the ability, currently, to dig in and fix this. Maybe I will come back later if this is hanging around.

If this is not clear please feel free to ask any questions. I will get back as quick as I can.

**Comment by Liongold** [comment]
A pull request is open with a workaround for this bug.

**Comment by Liongold** [comment]
This issue has been fixed. If you re-encounter this or any other issue, please open a new issue.
