### ISSUE TITLE
adldap is abandoned, please swich to adldap2

### ISSUE THREAD

**Issue by joepalma** [twostairs/paperwork#676]
strebl/adldap hasn't been updated in over a year, please move to https://github.com/Adldap2/Adldap2

adldap never worked with openldap anyway, adldap2 has experimental support.

**Comment by Gynidark** [comment]
all agree! +1

**Comment by Liongold** [comment]
Can someone test this and then contribute a pull request?

**Comment by Liongold** [comment]
Thanks for the feedback. Since this issue is similar to #605, this issue will be closed as duplicate. Please follow issue #605 for updates. This issue remains open for a contributor to help by doing.
