### ISSUE TITLE
milestones update

### ISSUE THREAD

**Issue by leo90skk** [twostairs/paperwork#677]
... can someone please update or remove the due dates for the milestones?

**Comment by leo90skk** [comment]
... and maybe a cleanup of the branches would be nice too. there seems to be some branches that are deprecated and already merged.

**Comment by Liongold** [comment]
The only branches that should be used are (depending on taste and requirements), deploy-heroku-develop, develop and master. The others are only used for development or testing.

**Comment by leo90skk** [comment]
are these branches still active? It seems to me that they are outdated and that confused me.

**Comment by Liongold** [comment]
The deploy, master and deploy-heroku-develop branches are active. They should not be outdated. What do you mean by them being outdated?

**Comment by mrusme** [comment]
Updated the milestones.
