### ISSUE TITLE
Check for JS code within note upon saving and ditch it

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#68]
It shouldn't be possible to add any kind of executable code (e.g. JS) through the note editor into the note. The saving functionality should check the note content for executable code and ditch either the executable part or maybe even the whole note, with an additional error message displayed to the user.

**Comment by Liongold** [comment]
How about only showing an error and not saving? (and not reloading the page so nothing is lost).

**Comment by devilx** [comment]
Yupp, that would work, I think.

**Comment by joshlemer** [comment]
Why do we want to forbid JavaScript in notes? What about people who want to make notes including code snippets?

**Comment by jamesrascal** [comment]
@joshlemer This is to prevent  executable code from being run. If you allowed code to be executed in the application you risk compromising the server.

**Comment by devilx** [comment]
@joshlemer imagine (as soon as sharing is available) that someone would share you a notebook, containing a note that uses un unpatched flaw within your browser that allows him to run code directly on your machine. Of course, the likelihood that someone you share a notebook with would do so is near to non-existent. Still I think allowing JavaScript to run from within a note would be evil (and probably require eval()).

Do you know of any scenarios, where someone would like to have a note that runs JavaScript code after opening?

**Comment by joshlemer** [comment]
@devilx Wait are we talking about all notes that contain javascript or just notes that are purely Javascript? I mean, if we deny all notes that contain any Javascript, we're alienating anyone who wants to use Paperwork to take notes about JavaScript for instance. 

Maybe I have a not like this:

For loops:
for(i=0; i<10; i++) {
    console.log(i + "\n");
}

While loops:
i = 0;
while (i <10);
    console.log(i + "\n");
    i = i+1;
}

So there's an example of someone learning javascript who wants to take notes about it.

**Comment by devilx** [comment]
Ah, I see what you mean. I was actually referring to notes that (in their HTML code, as notes technically contain of HTML) contain inline JavaScript code that could get executed by the browser.

Writing JavaScript Code into the note from a user's point of view should work just fine, as it will be saved as something like:

```html
&nbsp;&nbsp;for(i=0; i&lt;10; i++) { ...
```

This tickets refers to code that (maybe unintentionally) slipped into the HTML code as ```<script type="javascript"></script>```.

**Comment by ponychicken** [comment]
Isn't then the simplest solution just strip any strip tags and onclick="" etc attributes on save?

**Comment by devilx** [comment]
@ponychicken yupp, it would be the simplest, yet not the best solution. Here again, we should provide configurability through the app/config/paperwork.php, so every Paperwork admin could define own rules of what content to strip away and what not.

I'm not sure yet what's the best way to allow this. I remember Drupal having something similar built in, maybe a peek into their code might help.

**Comment by Baldrs** [comment]
I propose to filter out tags on save.

Something like that snippet(this is for partials and does not strip attributes, but it can be improved to do so): 
```php
// This is part of the bigger thing I can't disclose
$body = mb_convert_encoding($body, 'UTF-8', mb_detect_encoding($body));
$body = mb_convert_encoding($body, 'html-entities', 'utf-8');

$dom                     = new DOMDocument('1.0', 'UTF-8');
$dom->substituteEntities = TRUE;

// Suppress warnings about malformed html.
$previous_value = libxml_use_internal_errors(TRUE);

$dom->loadHTML($html);

libxml_clear_errors();
libxml_use_internal_errors($previous_value);

// @formatter:off
$tags_to_remove = array(
  'script', 'style', 'iframe', 'frame', 'form', 'object', 'video', 'audio',
  'SCRIPT', 'STYLE', 'IFRAME', 'FRAME', 'FORM', 'OBJECT', 'VIDEO', 'AUDIO',
);
// @formatter:on

$remove = array();

foreach ($tags_to_remove as $removal_target) {
  $sentenced = $dom->getElementsByTagName($removal_target);

  foreach ($sentenced as $item) {
    $remove[] = $item;
  }
}

foreach ($remove as $sentenced_item) {
  $sentenced_item->parentNode->removeChild($sentenced_item);
}

// Convert dom object back to html.
$html = '';

$body_node = $dom->getElementsByTagName('body')->item(0);

foreach ($body_node->childNodes as $child) {
  $html .= $dom->saveXML($child);
}
```

**Comment by devilx** [comment]
Why filtering video or audio? However, this needs to be configurable anyway.

**Comment by Baldrs** [comment]
Ah that's the code that filters snippets in an infinite scroll js payload. Just left it as is.

**Comment by Baldrs** [comment]
CKEditor removes scripts by default, now note saving api does that too.
