### ISSUE TITLE
Unable to remove notebook once added to collection

### ISSUE THREAD

**Issue by antaeusdk** [twostairs/paperwork#684]
Installed on: Raspberry Pi 2 running Fedora.

I added a notebook to a collection, and now I can't remove it from the collection.

**Comment by antaeusdk** [comment]
Is this not considered a bug?

**Comment by Liongold** [comment]
Yes you're right. This is a bug.

**Comment by Liongold** [comment]
This issue has now been fixed. Thanks for your contribution. If you encounter any issues, please open a new issue.
