### ISSUE TITLE
/setup/setConfig redirects to non-existing page /setup/setup.php in setup step 'Customise your Paperwork'

### ISSUE THREAD

**Issue by kuc** [twostairs/paperwork#685]
I have used [Installing Paperwork on Debian 7](https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Debian-7) as a reference.

Nothing interesting in server logs.

Browser console afer clicking 'Next':

```
GET http://example.com/setup/setup.php 404 (Not Found)
send @ jquery.js:9664
ajax @ jquery.js:9215
(anonymous function) @ setup.php:412
dispatch @ jquery.js:4670
r.handle @ jquery.js:4338
```

**Comment by kuc** [comment]
OK, adding file `setup` to directory `/frontend/app/storage/config/` with content `4` solved problem.
But documentation for semi-manual installation is outdated.

**Comment by bu2zhouzhu** [comment]
I got the same problem.

**Comment by Liongold** [comment]
You're right the semi-manual documentation is outdated. Which branch are you using?

**Comment by kuc** [comment]
@Liongold Latest commit from master.

**Comment by Liongold** [comment]
Can you test this on the develop branch?

**Comment by kuc** [comment]
@Liongold I will do this, maybe today.

**Comment by kuc** [comment]
@Liongold OK, my results from latest `develop` branch & using manual installation as described on wiki. Slightly modified, because I only run command
```
sudo chown www-data:www-data . attachments/ cache/ config/ logs/ sessions/ views/
```
in `frontend/app/storage` - this is enough to get everything working, and improves security.

Step 1 works.

Step 2 is showing bullshit about available databases (only MySQL support is detected), and is failing section `NPM Dependencies` - probably because what I said above. It would be nice to be able to force-skip that part...

**Comment by kuc** [comment]
But manually skipping to step 4 still works.

**Comment by kuc** [comment]
Setup Wizard is not also totally not working with `php artisan serve` development server...
Infinite redirect loop on step 4.

**Comment by Liongold** [comment]
About Step 2, are you sure there's a mistake in it? If yes, then that needs to be fixed. Manual skipping should work always but will skip important steps that need to be done manually. As for `php artisan serve`, the wizard has not been tested with that. Can you clarify what is causing the infinite loop, please?

Thanks for your contributions to making Paperwork better.

**Comment by kuc** [comment]
>About Step 2, are you sure there's a mistake in it?

When I have both mysql and pgsql PHP drivers enabled, it shows that only MySQL in available.
When I have only pgsql enabled, it shows that no databases are available.

------------

>As for php artisan serve, the wizard has not been tested with that.

Yeah, that's what I thought... I will try to use XAMPP or something like this on Windows instead.

------------

>Can you clarify what is causing the infinite loop, please?

Something about `/setup/setUp` -> `/setup/setup.php` -> `/setup/setup.php` -> ....
I will check that at home.

**Comment by kuc** [comment]
Logs after successful setup - using XAMPP - and trying to open `index.php` using `php artisan serve` instead of Apache:

```
php artisan serve
Laravel development server started on http://localhost:8000
[Tue Nov  1 13:17:51 2016] ::1:64172 [302]: /setup.php
[Tue Nov  1 13:17:54 2016] ::1:64191 [302]: /setup.php
[Tue Nov  1 13:17:57 2016] ::1:64203 [302]: /setup.php
[Tue Nov  1 13:18:01 2016] ::1:64210 [302]: /setup.php
[Tue Nov  1 13:18:04 2016] ::1:64223 [302]: /setup.php
[Tue Nov  1 13:18:07 2016] ::1:64230 [302]: /setup.php
[Tue Nov  1 13:18:10 2016] ::1:64238 [302]: /setup.php
[Tue Nov  1 13:18:13 2016] ::1:64245 [302]: /setup.php
[Tue Nov  1 13:18:17 2016] ::1:64252 [302]: /setup.php
[Tue Nov  1 13:18:20 2016] ::1:64261 [302]: /setup.php
[Tue Nov  1 13:18:24 2016] ::1:64273 [302]: /setup.php
[Tue Nov  1 13:18:27 2016] ::1:64280 [302]: /setup.php
[Tue Nov  1 13:18:30 2016] ::1:64289 [302]: /setup.php
[Tue Nov  1 13:18:34 2016] ::1:64296 [302]: /setup.php
```

**Comment by Liongold** [comment]
Can these issues be reproduced after #715 is merged? If the redirect loop occurs again, please specify at which step this is happening (what is content of the `setup` file?).

**Comment by kuc** [comment]
@Liongold I will test that in a free time. And about what exact issues you are talking?
Issues with `php artisan serve`, or issues present without manually adding file setup to directory `/frontend/app/storage/config/` with content `4`?

**Comment by Liongold** [comment]
If it isn't a problem for you, It'd be a lot of help if you could test for all of them again.

**Comment by kuc** [comment]
If waiting isn't a problem for you, I can do that... in the closely unspecified future.

**Comment by CentrixDE** [comment]
Hello, I have the same problem. But adding the File "setup" with the Content "4" didn't make any difference :( Can anyone help to fix this problem? The only thing it shows me is: "POST https://example.com/setup/setConfig 404 (Not Found)"

**Comment by Liongold** [comment]
Do you have mod_rewrite enabled? Are you using Apache?

**Comment by CentrixDE** [comment]
nvm, I just managed to install the application. I just had to disable the redirect rules in the htaccess to get into the setup.PHP, otherwise it would say I have too many redirects. Now I enabled the redirect rules after finishing steps 1-3 and it worked :) But thank you for your answer 👍

**Comment by Liongold** [comment]
The pull request #715 has been merged and no one has reposted that has encountered any problems that could not be solved. Thus, until someone else reconfirms that this issue is still valid, this issue will be closed. If anyone re-encounters this issue, please re-open this issue or open a new one. Thanks for the feedback.
