### ISSUE TITLE
Fix password reset feature

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#69]
The password resetting feature currently does not work properly.

**Comment by Liongold** [comment]
Do you exactly know what is the problem?

**Comment by devilx** [comment]
As far as I remember, the regular Laravel functionality for resetting a user's password expects a username, while we only use an e-mail address as userid. Therefor, we'd probably need to rebuild this feature on ourself.

**Comment by Liongold** [comment]
Possible cause: https://github.com/laravel/framework/blob/4.2/src/Illuminate/Auth/Reminders/RemindableTrait.php

**Comment by Liongold** [comment]
Possible starting point: https://github.com/laravel/framework/blob/4.2/src/Illuminate/Auth/Reminders/RemindableTrait.php#L12

**Comment by brunobatista** [comment]
I get this:

![error](https://cloud.githubusercontent.com/assets/441774/5910665/baf9cab0-a5a3-11e4-83e3-0405d37c2ad3.gif)

**Comment by devilx** [comment]
@brunobatista yes, this is a known feature. The issue here is the following:

Laravel expects the database to have a username and an email address column, while Paperworks uses only the username column (which is the e-mail address). Now the built-in functionality for resetting the password tries to look up the email column, which doesn't exist.

The question now is: what's the easier way? Rebuilding Paperwork's "users" table in order to have a separate email column which is kept in sync with the "username" column or making Laravel accept "username" as "email", so I could send the reset mail?

**Comment by iamgeef** [comment]
The starting point provided by @Liongold works. 
Changing line 12 from
`return $this->email;` 
to
`return $this->username;` 
enables the password reset option

Requires app/config/mail.php to be updated with smtp details for the email to actually send...obvs.

By default, the emails come through with no subject but editing the getPasswordRemindResponse (L#168) function of UserController.php enables a custom subject like so:

![paperwork](https://cloud.githubusercontent.com/assets/10751405/5954826/e241738a-a7f0-11e4-996a-7b4762831a4a.png)

and

![mailpaperwork](https://cloud.githubusercontent.com/assets/10751405/5954830/e984b5f8-a7f0-11e4-8ce0-8e9476f53fb8.png)

I've Just put through a pull request to enable the subject.

**Comment by devilx** [comment]
@iamgeef thanks for the detailed info! Now, as far as I see it, changing ```src/Illuminate/Auth/Reminders/RemindableTrait.php``` isn't the nicest way to fix this. Is there a more elegant way, which does not imply chaning Laravel itself, but rather "overwriting" this through an own Class that extends Laravel's?

**Comment by Liongold** [comment]
This has just been fixed.

**Comment by devilx** [comment]
4 Lines without modifying Laravel's core code? Great dude! :+1:

**Comment by Liongold** [comment]
Thanks. However, Google helped with this too. :D

On Monday, February 2, 2015, Marius <notifications@github.com> wrote:

> 4 Lines without modifying Laravel's core code? Great dude! [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twostairs/paperwork/issues/69#issuecomment-72556795>.
>


-- 
Sincerely,
Jean Spiteri.
