### ISSUE TITLE
Locked out of local site

### ISSUE THREAD

**Issue by ajlee** [twostairs/paperwork#703]
I have been trying to get into my local install. However, my password manager has not saved my new password and I do not have another copy, and can't get in. 

I have tried to use the password reset function, but I experienced a bug similar to [bug #69](https://github.com/twostairs/paperwork/issues/69). I hardcoded the email address into Illuminate/Mail/Mailer.php to resolve this, but the password reminder is still not sent, despite the message saying that a password reminder was sent successfully. Other php mailer functions work on my local machine.

I then tried to change the password manually by inserting a new password into the database with md5('mypassword') but this didn't work either.

**Comment by Liongold** [comment]
To generate the new password use this `$hash = password_hash("password", PASSWORD_BCRYPT, array('cost' => 10));`. 

Please open a new issue for the missing email. Please specify which branch you're running.
