### ISSUE TITLE
Auto import PDF from folder

### ISSUE THREAD

**Issue by bassebaba** [twostairs/paperwork#718]
Hello.

I have searched but cannot find it..
How do I do to "auto import" every pdf i drop in a certain folder, into a new note?
Just like the auto-feature in Evernote.. that's what Im trying to replace.

Is that feature available?

**Comment by kuc** [comment]
I'm sure that Evernote *web client* doesn't have that feature.

**Comment by bassebaba** [comment]
Sorry if I was unclear. 
Of course I'm referring to a folder on the machine where I will run paperwork.

I want to set up a samba shared folder on the server and then be able to place pfd files there which will get auto-imported.

I guess one way around would to build some middleware myself doing this by using the api?

Or is there another existing way to auto-import files?

**Comment by kuc** [comment]
>I guess one way around would to build some middleware myself doing this by using the api?

I think that this would be the most reasonable solution.

BTW: You want to import PDFs as note attachments *or* as extracted text content? If the later, then you also need some external tool to convert PDFs to text files.

**Comment by bassebaba** [comment]
Just the pdf as they are.

We have a network connected scanner that has the ability to Scan to a network share.
Then we have one install of Evernote on a VM which this Scan destination folder resides on.
Evernote is always open, so it adds the pdfs as the users scan their documents.

The problem with this solution is that its one User at a time, and quite heavy since you need remote desktop.

Another problem I guess tho, is that Evernote shows the pdfs directly, the pdf "is" the note...

So i guess unless paperwork has the ability to preview pdfs in the browser, I'm out of luck.

Thanks for tor feedback, I have to keep searching for a tool :)

**Comment by kuc** [comment]
Adding a PDF preview directly in the browser isn't difficult. It is enough to just embed PDF using direct link to file in `<iframe>`, or use `pdf.js`.
