### ISSUE TITLE
No File and Edit menus available on clean install

### ISSUE THREAD

**Issue by rzippert** [twostairs/paperwork#72]
Hello.

I've found Paperwork really interesting and tried to install it on my own server. It's an ArkOS server that runs nginx and mariadb. I were able to install it without much trouble but I'm unable to create any new note as both the File and Edit menus are not shown to me. Only the Paperwork logo and text appear on the left side of the top panel. Everything else that should work seems to be working, but this makes me unable to do anything. I know I'm not giving much information, but I don't really know where to look...

Thank you for your time.

**Comment by Liongold** [comment]
Do you get any errors in your browser's console?

**Comment by rzippert** [comment]
My full console (I'm using firefox nightly as it's the only way I could get the log in english here):
 > Unknown pseudo-class or pseudo-element '-webkit-inner-spin-button'.  Ruleset ignored due to bad selector. paperwork-v1.min.css:145:22
 > Unknown pseudo-class or pseudo-element '-webkit-search-cancel-button'.  Ruleset ignored due to bad selector. paperwork-v1.min.css:155:22
 > Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. paperwork-v1.min.css:270:25
 > Expected color but found 'auto'.  Expected color but found '-webkit-focus-ring-color'.  Expected end of value but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. paperwork-v1.min.css:914:15
 > Expected end of value but found '\9 '.  Error in parsing value for 'margin-top'.  Declaration dropped. paperwork-v1.min.css:2312:18
 > Expected color but found 'auto'.  Expected color but found '-webkit-focus-ring-color'.  Expected end of value but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. paperwork-v1.min.css:2330:15
 > Error in parsing value for 'box-shadow'.  Declaration dropped. paperwork-v1.min.css:2367:15
 > Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. paperwork-v1.min.css:2373:14
 > Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. paperwork-v1.min.css:2376:15
 > Expected end of value but found '�'.  Error in parsing value for 'line-height'.  Declaration dropped. paperwork-v1.min.css:2397:26
 > Expected end of value but found '�'.  Error in parsing value for 'line-height'.  Declaration dropped. paperwork-v1.min.css:2404:19
 > Expected end of value but found '�'.  Error in parsing value for 'line-height'.  Declaration dropped. paperwork-v1.min.css:2411:20
 > Unknown pseudo-class or pseudo-element '-ms-fullscreen'.  Ruleset ignored due to bad selector. paperwork-v1.min.css:2413:2
 > Unknown pseudo-class or pseudo-element '-ms-fullscreen'.  Ruleset ignored due to bad selector. paperwork-v1.min.css:2423:2
 > Unknown pseudo-class or pseudo-element '-ms-fullscreen'.  Ruleset ignored due to bad selector. paperwork-v1.min.css:2433:2
 > Expected end of value but found '\9 '.  Error in parsing value for 'margin-top'.  Declaration dropped. paperwork-v1.min.css:2467:18
 > Error in parsing value for 'box-shadow'.  Declaration dropped. paperwork-v1.min.css:2615:15
 > Error in parsing value for 'box-shadow'.  Declaration dropped. paperwork-v1.min.css:2619:15
 > Error in parsing value for 'box-shadow'.  Declaration dropped. paperwork-v1.min.css:2653:15
 > Error in parsing value for 'box-shadow'.  Declaration dropped. paperwork-v1.min.css:2657:15
 > Error in parsing value for 'box-shadow'.  Declaration dropped. paperwork-v1.min.css:2691:15
 > Error in parsing value for 'box-shadow'.  Declaration dropped. paperwork-v1.min.css:2695:15
 > Unknown property 'touch-action'.  Declaration dropped. paperwork-v1.min.css:2801:14
 > Unknown property 'user-select'.  Declaration dropped. paperwork-v1.min.css:2813:13
 > Expected color but found 'auto'.  Expected color but found '-webkit-focus-ring-color'.  Expected end of value but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. paperwork-v1.min.css:2822:15
 > Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:2844:10
 > Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:3297:10
 > Error in parsing value for 'background-image'.  Declaration dropped. paperwork-v1.min.css:4836:20
 > Error in parsing value for 'background-image'.  Declaration dropped. paperwork-v1.min.css:4837:20
 > Error in parsing value for 'background-image'.  Declaration dropped. paperwork-v1.min.css:4851:20
 > Error in parsing value for 'background-image'.  Declaration dropped. paperwork-v1.min.css:4852:20
 > Error in parsing value for 'background-image'.  Declaration dropped. paperwork-v1.min.css:4859:20
 > Error in parsing value for 'background-image'.  Declaration dropped. paperwork-v1.min.css:4860:20
 > Error in parsing value for 'background-image'.  Declaration dropped. paperwork-v1.min.css:4867:20
 > Error in parsing value for 'background-image'.  Declaration dropped. paperwork-v1.min.css:4868:20
 > Error in parsing value for 'background-image'.  Declaration dropped. paperwork-v1.min.css:4875:20
 > Error in parsing value for 'background-image'.  Declaration dropped. paperwork-v1.min.css:4876:20
 > Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:5480:10
 > Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:5488:10
 > Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:5558:10
 > Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:5562:10
 > Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:5628:10
 > Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:5632:10
 > Expected media feature name but found 'transform-3d'. paperwork-v1.min.css:5857:16
Expected media feature name but found '-webkit-transform-3d'. paperwork-v1.min.css:5857:32
 > Error in parsing value for 'perspective'.  Declaration dropped. paperwork-v1.min.css:5861:17
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:5917:10
 > Error in parsing value for 'background-image'.  Declaration dropped. paperwork-v1.min.css:5924:20
 > Error in parsing value for 'background-image'.  Declaration dropped. paperwork-v1.min.css:5925:20
 > Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:5928:10
 > Error in parsing value for 'background-image'.  Declaration dropped. paperwork-v1.min.css:5933:20
 > Error in parsing value for 'background-image'.  Declaration dropped. paperwork-v1.min.css:5934:20
 > Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:5937:10
 > Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:5945:10
 > Expected end of value but found '\9 '.  Error in parsing value for 'background-color'.  Declaration dropped. paperwork-v1.min.css:5999:25
 > Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. paperwork-v1.min.css:6280:25
 > Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:6380:10
 > Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:6388:10
 > Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:6396:10
 > Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:6404:10
 > Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. paperwork-v1.min.css:6412:10
 > Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. paperwork-v1.min.css:7943:40
 > Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. paperwork-v1.min.css:7946:41
 > Unknown property 'user-select'.  Declaration dropped. paperwork-v1.min.css:7973:13
 > Error in parsing value for 'box-shadow'.  Declaration dropped. paperwork-v1.min.css:8358:15
 > Error in parsing value for 'box-shadow'.  Declaration dropped. paperwork-v1.min.css:8367:15
 > Error in parsing value for 'box-shadow'.  Declaration dropped. paperwork-v1.min.css:8382:15
 > Unknown property 'user-select'.  Declaration dropped. freqselector.min.css:12:13
 > Expected declaration but found '*'.  Skipped to next declaration. typeahead.min.css:166:2
 > Expected declaration but found '*'.  Skipped to next declaration. typeahead.min.css:167:2
 > Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. index.php
 > The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page.

**Comment by Liongold** [comment]
Since you're on Firefox, can you show the Network tab as well, please?

**Comment by rzippert** [comment]
I've just erased my site's URL:
![network](https://cloud.githubusercontent.com/assets/2091971/5783795/2b82bc30-9dbe-11e4-8f62-068adb6a562c.png)

I do not have those api and template folders it is looking for. Tried to rebuild the whole thing with composer but there's no folders still... Did I forget to install something?

**Comment by Liongold** [comment]
Did you set up the paperwork folder to be the public root folder? In other words, is the paperwork URL similar to domain.com/paperwork or domain.com only.

**Comment by rzippert** [comment]
Yes it is. The public folder is the root and the index file is index.php... It doesn't open index.php automatically when I try opening the URL. I have to type manually the URL/index.php...
A little weird, but could that be related?

**Comment by Liongold** [comment]
Do you have mod_rewrite enabled? Did you fix the problem?

**Comment by rzippert** [comment]
I don't know what that mod_rewrite is. Is it a php configuration? 
No, the problem persists.

**Comment by Liongold** [comment]
It's a sort of PHP/Apache add-on. Can you try the answer in this question: http://stackoverflow.com/questions/9021425/how-to-check-if-mod-rewrite-is-enabled-in-php ? to test whether you have it or not? If you don't have it, can you try installing it?

**Comment by rzippert** [comment]
Actually, it's running on nginx. Is this applicable?

**Comment by jamesrascal** [comment]
What does your nginx config look like?

**Comment by rzippert** [comment]
########### nginx.conf
	#user  nobody;
	worker_processes  1;

	#error_log  logs/error.log;
	#error_log  logs/error.log  notice;
	#error_log  logs/error.log  info;

	#pid        logs/nginx.pid;


	events {
		worker_connections  1024;
	}


	http {
		server_names_hash_bucket_size 64;
		client_max_body_size 100M;
		include       mime.types;
		default_type  application/octet-stream;

		#log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
		#                  '$status $body_bytes_sent "$http_referer" '
		#                  '"$http_user_agent" "$http_x_forwarded_for"';

		#access_log  logs/access.log  main;

		sendfile        on;
		#tcp_nopush     on;

		#keepalive_timeout  0;
		keepalive_timeout  65;

		#gzip  on;

		include /etc/nginx/sites-enabled/*;

		#server {
		#    listen       80;
		#    server_name  localhost;

		    #charset koi8-r;

		    #access_log  logs/host.access.log  main;

		#    location / {
		#        root   html;
		#        index  index.html index.htm;
		#    }

		    #error_page  404              /404.html;

		    # redirect server error pages to the static page /50x.html
		    #
		#    error_page   500 502 503 504  /50x.html;
		#    location = /50x.html {
		#        root   html;
		#    }

		    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
		    #
		    #location ~ \.php$ {
		    #    proxy_pass   http://127.0.0.1;
		    #}

		    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
		    #
		    #location ~ \.php$ {
		    #    root           html;
		    #    fastcgi_pass   127.0.0.1:9000;
		    #    fastcgi_index  index.php;
		    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
		    #    include        fastcgi_params;
		    #}

		    # deny access to .htaccess files, if Apache's document root
		    # concurs with nginx's one
		    #
		    #location ~ /\.ht {
		    #    deny  all;
		    #}
		#}


		# another virtual host using mix of IP-, name-, and port-based configuration
		#
		#server {
		#    listen       8000;
		#    listen       somename:8080;
		#    server_name  somename  alias  another.alias;

		#    location / {
		#        root   html;
		#        index  index.html index.htm;
		#    }
		#}


		# HTTPS server
		#
		#server {
		#    listen       443;
		#    server_name  localhost;

		#    ssl                  on;
		#    ssl_certificate      cert.pem;
		#    ssl_certificate_key  cert.key;

		#    ssl_session_timeout  5m;

		#    ssl_protocols  SSLv2 SSLv3 TLSv1;
		#    ssl_ciphers  HIGH:!aNULL:!MD5;
		#    ssl_prefer_server_ciphers   on;

		#    location / {
		#        root   html;
		#        index  index.html index.htm;
		#    }
		#}

	}

**Comment by jamesrascal** [comment]
Can you also post the config you configured under /etc/nginx/sites-enabled/

**Comment by rzippert** [comment]
Faked the port and urls:

	server {
		listen 6789 ssl;
		server_name url1 url2 url3;
		root /srv/http/webapps/paperwork/frontend/public;
		index index.php;

		location ~ ^(.+?\.php)(/.*)?$ {
		    include fastcgi_params;
		    fastcgi_param SCRIPT_FILENAME $document_root$1;
		    fastcgi_param PATH_INFO $2;
		    fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
		    fastcgi_read_timeout 900s;
		}
		ssl_certificate /etc/ssl/certs/genesis/arkos.crt;
		ssl_certificate_key /etc/ssl/private/genesis/arkos.key;
		ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
		ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:EDH-DSS-DES-CBC3-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK;
		ssl_session_timeout 5m;
		ssl_prefer_server_ciphers on;
		ssl_session_cache shared:SSL:50m;
	}

**Comment by rzippert** [comment]
To illustrate a little better what is happening:

![captura de tela de 2015-01-16 19 17 06](https://cloud.githubusercontent.com/assets/2091971/5784570/30b73832-9dc5-11e4-8c87-e85a022542ea.png)

**Comment by jamesrascal** [comment]
Add this to in the server block to your config  under /etc/nginx/sites-enabled/
    location / {
                try_files $uri $uri/ /index.php;
        }

**Comment by rzippert** [comment]
You're a magician! It works! Thanks!
What does this block means?

**Comment by jamesrascal** [comment]
Checks for the existence of files in order, and returns the first file that is found. A trailing slash indicates a directory - $uri /. In the event that no file is found, an internal redirect to the last parameter is invoked.

http://wiki.nginx.org/HttpCoreModule#try_files

(That is the best answer I can find for you)

**Comment by jamesrascal** [comment]
(This issue is now resolved and can be closed)
