### ISSUE TITLE
Error when creating a note with content

### ISSUE THREAD

**Issue by anonimou0** [twostairs/paperwork#721]
If I create a note without any content, it will be created. I can add tags, title, upload files, ..., but I cant put any content on the main "note taker".
Please refer to the video attached:
[Screencast 2016-11-29 22:38:14.mp4.zip](https://github.com/twostairs/paperwork/files/620643/Screencast.2016-11-29.22.38.14.mp4.zip)
I can even edit the tags, files, title, after creating the note. However, if I try to put some content on the real note, it will fail. The message error is: "Something went wrong while saving your note. Please try again".

EDIT: 1- I tried dropping the database and recreating it, as stated here: https://github.com/twostairs/paperwork/wiki/Initial-installation . Still no luck.
2- Not sure if related. After reentering the "http://localhost" without being able to save the note, I got the message that "An auto-saved version of this content from "November 29 2016 10:53 PM" has been found. Would you like to compare content versions and choose which one to load?" If I say "OK" and put it "Side-by-side view", it returns just "true", without showing nothing in the box before.
3- The webserver user (www-data) has the permission (actually, is the owner) of the storage/ folder. So, permissions seems OK.
4- I had the .htacess file, however, without the following in there:
`RewriteEngine on`
`RewriteCond %{REQUEST_URI} !paperwork/frontend/public/`
`RewriteRule (.*) /paperwork/frontend/public/$1 [L]`
Add it. No luck
5- After every change, I restart php7-fpm and nginx.

**Comment by Liongold** [comment]
Can you indicate the code associated with your version, please? You can
find this by going to the Settings page.

**Comment by anonimou0** [comment]
@Liongold, there we go: 50527ed5c22a9c31ea88ad2561a1652435a4a984

**Comment by Liongold** [comment]
Can you try switching to the `develop` branch using `git checkout develop` and then rerunning `gulp`? If it happens again, please post a screenshot of the browser's develop tools' network tab. Please also post a screenshot of the request done when saving (the line added after clicking the Save button). Thanks for your feedback.

**Comment by anonimou0** [comment]
@Liongold, let's see if I made this right:
![cookies](https://cloud.githubusercontent.com/assets/14253996/20942938/bffa02f6-bbe4-11e6-86f3-5184fa5fcace.png)
![headers](https://cloud.githubusercontent.com/assets/14253996/20942940/bffe9f5a-bbe4-11e6-95f7-f5738f561889.png)
![params](https://cloud.githubusercontent.com/assets/14253996/20942942/c000fa5c-bbe4-11e6-8c8c-9319bffcb1c3.png)
![response](https://cloud.githubusercontent.com/assets/14253996/20942939/bffd8ec6-bbe4-11e6-8633-154990d1ceba.png)
![screen](https://cloud.githubusercontent.com/assets/14253996/20942941/bffeeeb0-bbe4-11e6-9024-738c84014b65.png)

**Comment by Liongold** [comment]
Yes, you did it right. Please try installing `php-xml` and then restart `apache` or `nginx` please and let us know if it works.

**Comment by anonimou0** [comment]
yeap.. that made it!
as a suggestion, update the wiki: https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Ubuntu-14.10 so it include, as well, the `php-xml`

thanks!!

**Comment by Liongold** [comment]
I see that you added it yourself. Thanks for your feedback and contribution.
