### ISSUE TITLE
Text lost, when session times out.

### ISSUE THREAD

**Issue by nanu-c** [twostairs/paperwork#725]
Sometimes I am investigating about a topic and i need lot of time. I also suspend my laptop from time to time.
The session timout check hits than when I do the next action and this is always when I hit the save button.
It would be really nice to use a local storage to save a draft and resume it from there after a successful login.

**Comment by Liongold** [comment]
Thanks for using Paperwork. Paperwork should have an auto-saving feature that saves a copy in local storage and then shows a popup the next time you visit the note editor. Are you saying that this does not work for you? If yes, you can try changing the session expiry as a workaround for now. You can do this in frontend/app/config/session.php by changing the lifetime value. Please comment if it does not work. Thanks.

**Comment by ardichoke** [comment]
The auto-save feature has also failed me, though I just started using paperwork so it only did it once... I took notes while in a meeting and forgot to click save... there was no copy ever saved in local storage. I just have an empty note in paperwork at this point.

**Comment by Liongold** [comment]
@ardichoke Did you have Auto-saved or something similar written at the bottom of the editor box?

**Comment by nanu-c** [comment]
After more work with paperwork, this mainly happens, when I didn't save  a new notice a the beginning.
Once I just got a "TRUE" as text. But normally the function works just fine.

**Comment by Liongold** [comment]
In pull request #737, there's an update to CKEditor and the autosave plugin. This should improve the autosave feature. Can you test it or wait until the request is merged please?

**Comment by ardichoke** [comment]
I haven't tested session timeout, but the autosave functionality worked in my first test which is a big step up. Typed some text in, closed the tab, loaded the page in a new tab, opened the note and was prompted to load the autosaved version of the note. Definite improvement here.

**Comment by Liongold** [comment]
Good to know. Are you interested in testing the session timeout?

**Comment by nanu-c** [comment]
this works for me now

**Comment by Liongold** [comment]
This issue will now be closed since CKEditor has been updated completely. If you encounter any issues, please open a new issue. Thanks for your feedback and interest in Paperwork.
