### ISSUE TITLE
Paperwork Demo site not available

### ISSUE THREAD

**Issue by longshot902** [twostairs/paperwork#726]
http://demo.paperwork.rocks/ is showing not available.

**Comment by mrusme** [comment]
In Progress.

**Comment by erm3nda** [comment]
Still not avail...

**Comment by Komish** [comment]
Currently shows the DNS record is not created for the domain.

**Comment by Liongold** [comment]
@mrusme Any updates?

**Comment by theerror** [comment]
I would like to give a try paperwork as server install is not quote straightforward so I can see, if it makes sense. It's almost two years and nothing. So sad...
