### ISSUE TITLE
Bower install ENOENT error

### ISSUE THREAD

**Issue by andyforceno** [twostairs/paperwork#727]
Every time I run the 'bower install' command, it fails with:

> bower angular-route#~1.2                                        retry Download of https://github.com/angular/bower-angular-route/archive/v1.2.32.tar.gz failed with ECONNRESET, retrying in 1.3s
bower angular-ui-bootstrap-bower#~0.12.1                      extract archive.tar.gz
bower retinajs#~1.3.0                                           retry Download of https://github.com/imulus/retinajs/archive/1.3.0.tar.gz failed with ECONNRESET, retrying in 1.2s
bower ngDraggable#~0.1.3                                      extract archive.tar.gz
bower html5shiv#~3.7.2                                        extract archive.tar.gz
bower angular-resource#~1.2                                   extract archive.tar.gz
bower angular-loading-bar#~0.7.1                                retry Download of https://github.com/chieffancypants/angular-loading-bar/archive/0.7.1.tar.gz failed with EINCOMPLETE, trying with git..
bower textAngular#~1.3.0                                      extract archive.tar.gz
bower angular-loading-bar#~0.7.1                             checkout 0.7.1

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, rename '/tmp/andy/bower/619f97b2e901db3872c71513b086fa8f-9635-W0r1zZ/archive.tar.gz.1752772268'

I'm not sure why it's failing at those archives, if I open the links in my browser, they download fine. Let me know if you more further information.

**Comment by andyforceno** [comment]
After reading some other issues on here, I'll give the develop branch a try and see if that helps.

**Comment by Liongold** [comment]
Is this still happening? It does not seem to be related to Paperwork itself.

**Comment by andyforceno** [comment]
I'm not sure if this issue is still occuring. I've since abandoned getting Paperwork running on that particular machine. I've managed to successfully install it on another machine, so I'm going to go ahead and close this. If I had to guess, I would  say this issue was due to user error during installation.

**Comment by mbrooks-public** [comment]
I am seeing the same issue.  I did a docker-compose up from the main directory and got this error:

 bower retinajs#~1.3.0                                           retry Download of  https://github.com/imulus/retinajs/archive/1.3.0.tar.gz failed with EINCOMPLETE, trying with git..
 bower angular-highlightjs#~0.4.3                             download https://github.com/pc035860/angular-highlightjs/archive/v0.4.3.tar.gz
 bower retinajs#~1.3.0                                        checkout 1.3.0

 events.js:72
        throw er; // Unhandled 'error' event
              ^
 Error: ENOENT, rename  '/tmp/a3ddc5ef17d5bc61ed6bf3fa7fcfa2f5/bower/169eecc629a56cba310d835ed0c15aad-210-yti1IE/archive.tar.gz.3133574486'
 The command '/bin/sh -c find ./app/storage -type d -print0 | xargs -0 chmod 0755 &&     find ./app/storage -type f -print0 | xargs -0 chmod 0644 &&     composer install && npm update && npm install &&     npm install -g gulp bower && bower --allow-root install && gulp &&     chown -R www-data:www-data /app && chmod +x /app/docker-runner.sh' returned a non-zero code: 8

**Comment by Liongold** [comment]
That should not have to do with Paperwork. Can you try again?
