### ISSUE TITLE
Upgrade problem

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#732]
throughout the year I had no problem with updates. My last update (php artisan paperwork:update)  was 2016-11-21. Now, I try update and get error:

![paperwork_4](https://cloud.githubusercontent.com/assets/13505686/21444788/ca241896-c8b1-11e6-83a5-fa9741b81262.png)

Last update kill config file ?

**Comment by Liongold** [comment]
Are you using the develop branch? Did you use that command on Nov 21 as well? There don't seem to be any changes that should have touched config. If you did not use that command in November, then probably it's an issue with the interaction between that command and the Setup Wizard.

**Comment by Liongold** [comment]
Also please recheck the database.json config file to be sure that it's correct.

**Comment by jacek-1210** [comment]
database.json  look as right. All settings are identical as alder paperwork version

Is develop ? Probably yes:

![paperwork_develop](https://cloud.githubusercontent.com/assets/13505686/21556380/3fdabfe0-ce20-11e6-824e-c056b50f12dc.png)


On Nov 21 I did my last paperwork upgrade (Wasn't  Nov 21 paperwork version, was earlier version). And this upgrade work right. Now, (today) actually upgrade don't work (?)

**Comment by Liongold** [comment]
Can you try running `php artisan migrate` please and post the output? Make sure to backup your database before.

**Comment by jacek-1210** [comment]
Some syntax problems with SQL (?):

![paperwork_5](https://cloud.githubusercontent.com/assets/13505686/21596063/2556f08a-d136-11e6-8dac-44fbfa5cce30.png)

**Comment by Liongold** [comment]
Can you try backing up the database, then reinstalling it and then trying to transfer the old tables to the new database?

**Comment by Liongold** [comment]
The attachments folder should not affect it. Can you add --verbose to php artisan migrate?

**Comment by jacek-1210** [comment]
![paperwork_6](https://cloud.githubusercontent.com/assets/13505686/21797910/0dccc44e-d712-11e6-9abc-15785825733e.png)

I did restart mysqlservice (he's working for almost a year) - without result :/

**Comment by Liongold** [comment]
Thanks for the info. Which version are you using please? Workaround for now - just remove the 2016_10_03_ migration file and then run everything as normal. It should work then. But this is now a bug.

**Comment by jacek-1210** [comment]
Wchich version of paperwork ? I don't know, how to check it (?). In my notes: this year I did update on: 2016-01-01 (work OK), 2016-06-21 (work OK), 2016-09-10 (work OK), 2016-11-21 (work OK), 2016-12-22 & newer (don't work).  
Hmmm, where can I find 2016_10_03 migration file, to remove ? Google does'nt help :) I found only:

frontend/vendor/laravel/framework/src/Illuminate/Foundation/Console/MigratePublishCommand.php
frontend/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateMakeCommand.php
frontend/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php

and this is probably not it?

**Comment by Liongold** [comment]
To check Paperwork version, go to Settings page in the About tab. Please include your MariaDB version as well.

**Comment by Liongold** [comment]
The file to remove can be found in frontend/app/database/migrations folder.

**Comment by Liongold** [comment]
I've removed the file from a branch named issue-732-test. You can just do `git checkout issue-732-test` and then run `php artisan migrate --force` and see if it works.

**Comment by jacek-1210** [comment]
MariaDB was 10.0.22, now I update to 10.0.27 - paperwork don't work
I delete 2016_10_03_ migration file but paperwork don't work :/

*************************************************************************************

Hmm, in settings is: 

About Paperwork (worked copy)
Please include this identification code in any issues you open on our Github repository. This code does not contain any personal information and can be shared freely.

873efa01faff763d25d371da42592b913d62da94

*************************************************************************

I'll try tomorrow 732-test

It isn't a big problem - I have old copy 2016-11-21, make copy-paste and this version work. But I can't upgrade to newer version

**Comment by Liongold** [comment]
When you test it, feel free to share the result to make sure that this gets fixed.

**Comment by jacek-1210** [comment]
I had no time earlier:

1) git pull, git checkout issue-732-test and then run php artisan migrate --force   - don't work: this same error

2) today:  php artisan paperwork:update - don't work: this same error

3) & migrate - this same error

:(((

Typical I work on Chrome, today I tested on Chrome & Edge

**Comment by Liongold** [comment]
Did you try to do a clean install?

**Comment by jacek-1210** [comment]
Wrrrr.. I'm very angry: I try clean install, it worked, but the base was empty. When try importing the old dumped data into empty database, SQL server was crashed.  ibdata1 was crashed. I have dump of first base, but haven't dump second base - another aplication ;/////  I lost a whole day and I was not able to solve the problem. And dumped base does not want to import: I get error: "table not exist". even after manually creating the table, when I try to access the table (via phpmyadmin), I get: "table not exist"

**Comment by Liongold** [comment]
@jacek-1210 Sorry for the questions. I understand this is annoying but most probably the problem lies in your setup. You can try moving the tables one-by-one so that you don't lose everything but without any additional information, a bug can't be identified in Paperwork. 

@JamborJan Sorry for pinging. Do you have, maybe, a setup similar to this and you can test this problem please?

**Comment by jacek-1210** [comment]
Maybe this is the problem (?):

![paperwork1](https://cloud.githubusercontent.com/assets/13505686/22685027/0a24470e-ed1f-11e6-9064-fe9b4a237a4f.png)

new, clean sqlbase, new, initiated paperwork worked, but via import old sql base; attachments go, but attachments_version stopped. "version_id" vs. "id" ?

************************
Meanwhile, if someone - like me- SQL server was crashed and no dump, only original database files. The internet is a lot of guides, but hard to find one that would work. I relied on it, but for me it was easier: 
https://bobcares.com/blog/database-crash-rescue-how-we-re-built-an-innodb-mysql-database-when-ibdata1-file-was-corrupted/

My sql is MariaDB 5.6. (InnoDB)

1. Uninstall MariaDB sql server
2. Total clean /var/lib/mysql directory
3. Again instal (new) MariaDB sql server
4. Create empty base (eg. paperwork)
5. Install the base structure of the application installer (eg. Paperwork installer)
6. In each a new database table step-by-step perform (eg. The table collections):

# mysql paperwork
mysql> alter table collections discard tablespace;
....
quit

7. After working all the tables in the new database, you must copy from the old database to new database all the tables * .ibd
8. Perform: 
            chown -R mysql: mysql /var/lib/ mysql
      You can also: chmod -R 660 /var/lib/mysql/paperwork

9. Then the table after table import the data:

# mysql paperwork
mysql> alter table collection import tablespace;
....
quit

10. SQL database should automatically without additional steps to import data into the new system (new base)
11. Restart SQL server
12. This should be at least enough to perform a dump, and perhaps even base moves easily

**Comment by jacek-1210** [comment]
Hmm, hokus-pokus, abracadabra. Before, the renewal of the base by the archive (dump/import) did not help.
Now, completely by accident, I'll copy the old database to the new base (I change the name of old database to paperwork name). (The new program has already been initiated at the new, now erased base)
And, probably, - for now - it works  O.o

**Comment by Liongold** [comment]
The develop branch has been updated to fix the bug you described. This should now be fixed. Can you please test it? This should be the final test.

**Comment by jacek-1210** [comment]
Don't works :(  Old database, old paperwork and after php artisan paperwork upgrade I get the same error. Maybe there are other problems (?) My new paperwork works. Interestingly, I did php artisan paperwork update, paperwork get via git 2 new files and still works

**Comment by Liongold** [comment]
This is getting complicated. Try a totally fresh install, run php artisan migrate as normal and then copy the table contents from the backup to the new one. That should work. If you do not have postgresql, nothing should change. 

Are you saying what I said above does not work?

**Comment by jacek-1210** [comment]
OK, so, my last, final, today try and findings:

1) old database, old paperwork: 
php artisan paperwork:update - don't work, I get error from top of this issue

2) new install:

cd /www
rm -rf paperwork
git clone https://github.com/twostairs/paperwork.git
cd paperwork/frontend
composer install
php artisan paperwork:install
php artisan migrate

run https://paperwork....  and init via setup.php

git checkout develop

----to this moment all works but database is empty



import via phpmyadmin from old base dump to the new base - don't work (via import I get error "attachments_version")


BUT:

if I make copy/paste - not import from old to new base, but only change name of old base eg. from paperwork_backup to paperwork, old base works with new versions of paperwork files. 
I checked it twice

**Comment by Liongold** [comment]
Good to know you have a working version. If you can use the data present in the "old" paperwork, I suggest to use a clean Paperwork install and use the way you mentioned to use the "old" database. Please note, that db_settings and paperwork_settings have been replaced by database.json and paperwork.json. If you have any new issues, please comment on this issue. If you've solved your problem, please close this issue.
