### ISSUE TITLE
Image upload file size limit?

### ISSUE THREAD

**Issue by scooter7** [twostairs/paperwork#734]
Hi, I'm trying to upload images from my phone into a note while using Paperwork on a mobile device. However, it appears that the image must be too big because the upload won't work. I have uploaded smaller images successfully when uploading from a desktop machine. Where in the file structure can I make edits that will enable larger image files to be uploaded into notes? Thanks!

**Comment by Liongold** [comment]
Thanks for using Paperwork. Paperwork doesn't have a setting itself for this. The maximum upload size should be regulated by PHP itself. Try increasing the values in your php.ini (`upload_max_filesize` and `post_max_size`). This should help. Can you please confirm if this works or not?

**Comment by plbeane** [comment]
Hello, I'm having a similar issue but no luck after adjusting the PHP values (upload_max_filesize and post_max_size). It seems that I can't upload anything over >1 MB on the desktop or mobile version. Any attachments 1000KB or less upload fine. Thank you!!

**Comment by Liongold** [comment]
There should not be anything from Paperwork's side. Can you check the response of the upload request? You can see it in the network tab of the Developer Tools. Do you have any errors in the Apache/PHP error log?

**Comment by plbeane** [comment]
I looked in the error log and found out it was actually an error from Nginx - client_max_body_size is set to 1M by default! My fault for not checking them before posting this bug. Thank you for doing an awesome job developing this software - I am really enjoying Paperwork :)!

**Comment by Liongold** [comment]
Thank you for using Paperwork. Since this question has been resolved, I'll close the issue. If you have any issues with Paperwork, please open a new one.
