### ISSUE TITLE
Selecting a different notebook (or all notebooks) on mobile screen does not change notes dropdown

### ISSUE THREAD

**Issue by joshlemer** [twostairs/paperwork#74]
On a small screen (for instance, less than ~700 pixels), there are two dropdown menus. The "Notebooks" and "Notes" dropdowns. If the "Notebooks" dropdown is changed to a different notebook, the "Notes" dropdown should change its contents to contain notes from the newly selected notebook.

**Comment by Liongold** [comment]
Can you post a screenshot, please?

**Comment by joshlemer** [comment]
Here's the branch: https://github.com/joshlemer/paperwork/tree/dropdown-notebook-switching
![Screenshot of the issue](http://i.imgur.com/5TUCaMg.png)

As you can see, selecting a notebook in that dropdown doesn't actually change the notes listed in the second dropdown (hard to capture that behavior in a screenshot).

**Comment by devilx** [comment]
This is a duplicate of #46. I'm going to close it, as it will be referenced there. Thank you for reporting it, please feel free to subscribe to the other ticket. :-)
