### ISSUE TITLE
secure issue and version & integration check

### ISSUE THREAD

**Issue by peyoot** [twostairs/paperwork#742]
Hi, guys,

I haven't make it a good experience after install paperwork. it's not work out of box.
there's some issues:
1. I use let's encrypt but the index.php seems cause "parts of this page are not secure" issue.
![pp-notsecure](https://cloud.githubusercontent.com/assets/2165697/21670561/152d4d8c-d350-11e6-9758-3338ed1482cc.png)

2. after login, there's some code rather than normal content displayed.
![ppcode](https://cloud.githubusercontent.com/assets/2165697/21670570/2a8379e0-d350-11e6-9033-e64b75e73a6d.png)

I use paperwork behind a let's encrypt encrypted ssl nginx reverse proxy server. It shouldn't be the problem of my configuration because I also have owncloud running in the same way and that one works just fine. 

I wonder if it's because I install the wrong version of paperwork. I use master branch, is this one too old? which one is recommend? should I use develop one?

Also I have nodejs 4.2 and npm 3.5.2 installed. is it the proper version?

**Comment by Liongold** [comment]
Paperwork does not seem to support reverse proxies. However, the Sandstorm version has been patched to have this ability. I've now created a test branch by using that edit. Can you test it please? Just use `issue-742-test` instead of develop. Please state whether this works or not to be able to add it to the official repo. 

@JamborJan I'm sorry for not waiting for you to do this but, if the patch, you can then recommit it yourself to the official repo.

**Comment by JamborJan** [comment]
Hi @Liongold no need to say sorry, I was not aware until now that I'm an official collaborator who can edit the paperwork repo :-) Thanks for applying the fix.

**Comment by Liongold** [comment]
Well, I did not actually apply it. I need someone to confirm that it works, even outside Sandstorm first and that it does not break it for the others. So you're still in time. :)

**Comment by peyoot** [comment]
Hi, Liongold. I haven't got time to try. 
But are you sure the issue-742-test branch is the right version. 
I simply git clone this branch, but didn't find that app/paperwork.php have the trustproxy() option, which mentioned in some thread. 
As I will install in a production server, so I just want to make sure it won't introduce some trash script and verify it before I continue.

**Comment by Liongold** [comment]
@peyoot No, in that branch only the routes.php file was changed. Can't you test it in a test/dev environment please? Right now, there's no confirmation this will work, so it is not good for production, I think.

**Comment by Liongold** [comment]
However, thee do not seem to be any changes to that file (assuming you meant app/_config_/paperwork.php). @JamborJan Did you change anything there to make the proxy work?

**Comment by JamborJan** [comment]
Hey guys, sorry for my late reply I'm a bit down under a big pile of work. 

The issue https://github.com/JamborJan/paperwork/issues/4 is old and outdated, I don't think that we need to do all of the mentioned things. What I'm doing today when I'm building a new paperwork version for [Sandstorm](https://github.com/sandstorm-io/sandstorm) which works with an included nginx reverse proxy and has exact the same issue with https.

What I'm doing is I pull in the latest branch of paperwork and then change some files for my use case: https://github.com/JamborJan/paperwork/tree/master/changedfiles

You definetly will need to check out these changes: https://github.com/JamborJan/paperwork/blob/master/changedfiles/frontend/app/routes.php#L3-L15

More should not be required. Please let me know if that works. If not I'm here to help.

JJ

**Comment by Liongold** [comment]
@JamborJan Actually sorry for disturbing you. I've done the routes.php update. Now, someone is needed to test it if it works.

**Comment by peyoot** [comment]
today I try to install paperwork dev branch and it failed in the step "php artisan migrate"
here's error picture:
![screen](https://cloud.githubusercontent.com/assets/2165697/22617580/c083b8b8-eb03-11e6-8acd-306d6f8e6225.png)
I need to fix this issue to continue as all changes seems have been applied into dev rather than master.

what I do is follow the wiki>installing paperwork on Ubuntu 14.10. But my system is ubuntu 16.10. 
I can install master successfully, but not able to make dev branch installation work.
other environment: nodejs 4.2.6, npm 4.0.5

anything wrong?

**Comment by peyoot** [comment]
well, I take some time and do a research. and I found that paperwork use laravel v4.2, and it seems not fully support php7. As I use PHP7 , so I doubt the dev branch installation problem is because of the Laravel version. But I just curious why master version can be installed in the same PHP7 environment.
This topic should cause some misunderstanding. Because "master" version doesn't support reverse proxy, and "dev" branch doesn't able to be installed to test the reverse proxy capability. 
Maybe someone can take a look into ig and find out a solution so that I can test and provide feedback again.

**Comment by Liongold** [comment]
That issue should not be related to PHP7. As it is, Paperwork should work well on PHP7. A change was done to the develop branch which should fix your problem. The reverse proxy is waiting for someone to test the temporary branch before opening a pull request to put this functionality. The temporary branch issue-742-test has also been updated with the latest. 

Can you test it please? If you (or someone else) confirms that, that branch works, then reverse proxy support can be added to the official repo.

**Comment by peyoot** [comment]
Hi, Liongold, I want to do the test, but if I use master branch again, I can perform "php artisan migrate" without error. But with develop or 742-test branch, I can't finish "php artisan migrate" command. The error shows it have something to do with SQL synax. It seems develop branch have something wrong with this command. as I can't finish installation, so I can't test it.

**Comment by Liongold** [comment]
@peyoot The branch has been updated and does not run the migration file anymore if you do not use PostgreSQL. If you use pgsql, then the file should not have a problems with your database. Please run `git pull` before testing to update your copy.

**Comment by peyoot** [comment]
I just test issue-742-test branch and it seems works for sign up users. 
only some small issues in the setup wizard as bellow:
1. in step2 it doesn't autodetect database availability. I have to click reload to go to mysql configure page.
2.  the first account registration page doesn't show up.
![paperwork-setup6](https://cloud.githubusercontent.com/assets/2165697/23293258/22c166aa-faa0-11e6-9153-4ea08a73d1ef.PNG)

**Comment by Liongold** [comment]
Do you get any console output in the Developer Tools of your browser?

**Comment by eccee** [comment]
Hi, Liongold, I haven't retry it yet. as it works for me after installation and I can manually register first user as admin.
So I think you need to merge it first.

**Comment by Liongold** [comment]
The code needed for this feature has been submitted in pull request #775.

**Comment by Liongold** [comment]
@peyoot The pull request has been merged and this feature should be available on both the develop and master branches. Thus, this issue will be closed. Thanks for your feedback. If you encounter any issues, please open a new issue.
