### ISSUE TITLE
php composer.phar install fails

### ISSUE THREAD

**Issue by dnhodgson** [twostairs/paperwork#743]
Trying to install on CentOS 7.3.1611
3.10.0-514.2.2.el7.x86_64

When running the php composer.phar install commaned it terminates with "Killed"
```
[root@web1 frontend]# php composer.phar install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed
```

I installed composer and ran composer install and got the same result. I ran it again with "-vvv" below is that last few lines.

```
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$view.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$workbench.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$config.json from cache
Killed
```

I tried re-creating the VM again but got the same results.

**Comment by kuc** [comment]
This issue with Composer, not with Paperwork. Your server has too low amount of RAM available.

**Comment by dnhodgson** [comment]
Yup, that's what it was. Thanks!
