### ISSUE TITLE
How to update to latest version?

### ISSUE THREAD

**Issue by lukasp2** [twostairs/paperwork#744]
Hi community,

how I can update paperwork to latest version?

Thank you,
Lukas

**Comment by Liongold** [comment]
@lukasp2 Sorry for the late reply. Paperwork can be updated by running `git pull` and then `composer install`, `npm install`, `bower install` and `gulp`. The database may need to be updated as well. This is done by running `php artisan migrate`. Thanks for your interest in Paperwork. This issue will now be closed. If you'll encounter any issues with updating, feel free to open a new issue.
