### ISSUE TITLE
Markdown support for Paperwork?

### ISSUE THREAD

**Issue by CentrixDE** [twostairs/paperwork#748]
Hello,

I love paperwork and even after a few issues while installing it, I just managed to use this as my main application for now :) I just have a little request, is it possible to integrate some sort of formatting function into it like markdown editing?

**Comment by Liongold** [comment]
Thanks for using Paperwork. Good to know you like it. This is, however a duplicate of #95. Please continue following that issue for any progress. To avoid having open duplicates, this issue will be closed. Thanks for your feedback.
