### ISSUE TITLE
Unable to disable user registration

### ISSUE THREAD

**Issue by andyforceno** [twostairs/paperwork#751]
I would like to disable registration. The setting for that is in frontend/app/paperwork.php. I set the registration line to false, but the registration option is still available on the page, and clicking on it takes you to the registration page. I changed the Registration line to read:
` 'registration' => isset($configuration->registration) ? ($configuration->registration == "true") : false,`

Am I doing this correctly? Is there anything I have to do after making changes to paperwork.php?

**Comment by Liongold** [comment]
That file should be left as it is. Can you change the value corresponding to registration in frontend/app/storage/config/paperwork,json? Does that work for you? Thanks for using Paperwork.

**Comment by andyforceno** [comment]
Thank you, that did it :-)

**Comment by Liongold** [comment]
This issue has now been closed. Thanks for your interest in Paperwork.
