### ISSUE TITLE
The problem of NPM Dependencies

### ISSUE THREAD

**Issue by loveshizuka** [twostairs/paperwork#765]
I walk through the setup wiki step by step to install the PerperWork many times, but always have the same problem: NPM Dependencies failed. I will show you my install steps,  could you help me to find the problem what it is please? Thank you!!

![20170227152520](https://cloud.githubusercontent.com/assets/25612355/23352474/3a10dd7c-fd02-11e6-88c0-cfa101c41a97.png)

 My VPS in Vultr, Centos6.5, php5.6.3.0, mysql5.6, Apache2.4, gcc 4.9.1, Python 2.6.6, node 7.6.0, npm4.1.2 .

1. Install node.js and npm

`# wget http://nodejs.org/dist/node-latest.tar.gz`
`# tar -zxvf node-latest.tar.gz`
`# cd node-v7.6.0`
`# ./configure`
`# make && make install`
`# ln -s /usr/local/bin/node /usr/bin/node`
`# curl -L https://www.npmjs.com/install.sh | sh`

2. Install composer

`# curl -s https://getcomposer.org/installer | php`
`# mv composer.phar /usr/local/bin/composer`

3. Created the Mysql database by phpMyAdmin

4. Install PaperWork

`# cd data/wwwroot/note.kvsky.com`  (the website directory)
`# git clone https://github.com/twostairs/paperwork.git`
`# cd paperwork/frontend`
Put the mysql parameters into "frontend/app/storage/config/database.json".
`# composer install`
`# php artisan migrate`
`# chown -R www /data/wwwroot/note.kvsky.com`
Set Apache vhost conf file point to website directory.
`# npm install -g gulp bower`
`# npm install`
`# bower install --allow-root`  **(can't use 'bower install' directly, why?)**
`# gulp`
`# service httpd restart`

That is all, but failed.. --ll

**Comment by Liongold** [comment]
@loveshizuka Can you try `sudo npm install -g gulp bower` and then the rest of the commands please?

**Comment by loveshizuka** [comment]
Thanks for your help, Liongold! The same issue happened when I tried to use the command you told me. I consider the problem is that I haven't install the nodejs and npm correctly. So I use the other way to install it.
```
curl --silent --location https://rpm.nodesource.com/setup_7.x | bash -
yum -y install nodejs
```
then, PaperWork installed successfully! Thank you for your help again!
