### ISSUE TITLE
Route not defined after one day of runtime

### ISSUE THREAD

**Issue by njordr** [twostairs/paperwork#766]
Hi.

I try two times to use the docker image of paperwork. Both the times after about one day of runtime, I've got thi error when I try to connect:

Route [user/register] not defined. (View: /app/app/views/user/login.blade.php)

**Comment by Liongold** [comment]
So you're saying that one day, the route is defined and the other
disappears? Did you move any files around? Or maybe you changed something
else?


-- 
Sincerely,
Jean.

**Comment by njordr** [comment]
Yes, after one day the issue. No changes in the meantime.

I already try to re-deploy the docker machine, with the same result

**Comment by Liongold** [comment]
Any info in the Apache/Nginx/PHP error logs?

**Comment by njordr** [comment]
This is the only logs I can found (laravel.log)
[2017-03-06 16:33:03] development.ERROR: exception 'InvalidArgumentException' with message 'Route [user/register] not defined.' in /app/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:231
Stack trace:
#0 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\Routing\UrlGenerator->route('user/register')
#1 /app/app/storage/views/949f773aaa89afd1638da60a533b47b2(40): Illuminate\Support\Facades\Facade::__callStatic('route', Array)
#2 /app/app/storage/views/949f773aaa89afd1638da60a533b47b2(40): Illuminate\Support\Facades\URL::route('user/register')
#3 /app/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(37): include('/app/app/storag...')
#4 /app/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(57): Illuminate\View\Engines\PhpEngine->evaluatePath('/app/app/storag...', Array)
#5 /app/vendor/laravel/framework/src/Illuminate/View/View.php(140): Illuminate\View\Engines\CompilerEngine->get('/app/app/config...', Array)
#6 /app/vendor/laravel/framework/src/Illuminate/View/View.php(109): Illuminate\View\View->getContents()
#7 /app/vendor/laravel/framework/src/Illuminate/View/View.php(78): Illuminate\View\View->renderContents()
#8 /app/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#9 /app/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#10 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#11 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#12 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /app/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#16 /app/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#17 /app/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#18 /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#19 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#20 /app/public/index.php(65): Illuminate\Foundation\Application->run()
#21 {main}

Next exception 'ErrorException' with message 'Route [user/register] not defined. (View: /app/app/views/user/login.blade.php)' in /app/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:231
Stack trace:
#0 /app/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(InvalidArgumentException), 1)
#1 /app/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(57): Illuminate\View\Engines\PhpEngine->evaluatePath('/app/app/storag...', Array)
#2 /app/vendor/laravel/framework/src/Illuminate/View/View.php(140): Illuminate\View\Engines\CompilerEngine->get('/app/app/config...', Array)
#3 /app/vendor/laravel/framework/src/Illuminate/View/View.php(109): Illuminate\View\View->getContents()
#4 /app/vendor/laravel/framework/src/Illuminate/View/View.php(78): Illuminate\View\View->renderContents()
#5 /app/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#6 /app/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /app/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /app/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /app/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 /app/public/index.php(65): Illuminate\Foundation\Application->run()
#18 {main} [] []

hope this helps

**Comment by Rerryn** [comment]
Hi, I've encountered the same issue with the docker image.
Initially I had user registration enabled to allow some users to self-register (as a trial), but I wanted to close it off so I edited the paperwork.json file to disable registration.

All was fine for a while, and then I received the same error. I suspect that it is related to not having a session (i.e. not being logged in) + registration being disabled.

I can reliably replicate this by toggling registration on/off and reloading the login page. Hope that helps.

**Comment by njordr** [comment]
The same for me. Initially I leave "enable registration" to true. The issue began when I set it to false

**Comment by Liongold** [comment]
Sorry for the late reply and thanks for the additional information. There was a bug with the disabling of registration. A pull request has now been submitted and can be found here, #776. You are encouraged to test the fix to make sure that the bug is fixed completely, by testing the code in that request.

**Comment by Liongold** [comment]
@njordjr @Rerryn The pull request has been merged and this feature should be available on both the develop and master branches. Thus, this issue will be closed. Thanks for your feedback. If you encounter any issues, please open a new issue.
