### ISSUE TITLE
Can't upload attachments to notes

### ISSUE THREAD

**Issue by oliver9042** [twostairs/paperwork#767]
Hi,

I just installed paperwork on debian jessie with latest nodejs.
the sites works without hassle except for uploading attachments to any note.
the bar loads, there's a green bar at the top without any text and a warning symbol text to the attachments. after that, the attachment disappears.

I chowned the paperwork folder, saving notes isn't a problem.
whats wrong?

best regards!

**Comment by oliver9042** [comment]
Sorry, my bad. open_basedir directive in php wasnt set correctly...

**Comment by JamborJan** [comment]
hey @oliver9042 great that you where able to solve the issue on your own. Maybe it's a good idea to state what exactly was your directive before and after your change. This way others running in the same issue are able to solve it.

Thanks!

**Comment by oliver9042** [comment]
My paperwork folder was located in /var/www/, but that path wasn't enabled in /etc/php5/fpm/php.ini's open_basedir settings.
I restricted php execution to used folders only, not systemwide, and my webserver root was in /usr/share/nginx/html before. That's why I had to add /var/www/ to succesfully upload files :)
