### ISSUE TITLE
Installation screen step 6 (admin registration)

### ISSUE THREAD

**Issue by Habilya** [twostairs/paperwork#768]
Installation screen with new admin registration doesn't open up, the view generates an error

Next ErrorException: Undefined variable: admin (View: /web/www/paperwork.mysite.com/paperwork/frontend/app/views/partials/registration-form.blade.php)

**Comment by Liongold** [comment]
This seems to be a duplicate of #758. Thus, this issue will be closed. If you want to keep informed on the solution to this problem, please follow #758. Thanks for your interest in Paperwork.
