### ISSUE TITLE
array_key_exists() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by letlive** [twostairs/paperwork#77]
After installing by using Composer, I visited my paperwork site and found error message above.
This error occurs in filters.php in line 29.

**Comment by letlive** [comment]
screenshot.
![voila_capture 2015-01-22_12-45-49_](https://cloud.githubusercontent.com/assets/10461211/5839298/9d41b8ce-a1d0-11e4-976e-4795b9574bc6.png)

**Comment by letlive** [comment]
Env: Debian/jessie (x64) PHP 5.6.4-4, Apache/2.4.10 (Debian) OpenSSL/1.0.1j

**Comment by jamesrascal** [comment]
Are you using MySQL and what does your vhost config look like?

**Comment by devilx** [comment]
Please show us your app/config/paperwork.php (be sure to blank your sensitive data before posting here).

**Comment by letlive** [comment]
@jamesrascal Yes, vhost...Apache site configuration?

<IfModule mod_ssl.c>
<VirtualHost *:443>

        ServerAdmin webmaster@example.com
        ServerName  note.example.com
        DocumentRoot /srv/paperwork/frontend/public
        <Directory /srv/paperwork/frontend/public>
                Options MultiViews SymLinksIfOwnerMatch
                AllowOverride None
                Require all granted
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/note.example.com_error.log
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/note.example.com_access.log combined

        SSLEngine on
        SSLCertificateFile    /usr/local/etc/ssl/example.com.cacrt
        SSLCertificateKeyFile /usr/local/etc/ssl/example.com.key

        <FilesMatch "\.(cgi|shtml|phtml|php)$">
                SSLOptions +StdEnvVars
        </FilesMatch>
        <Directory /usr/lib/cgi-bin>
                SSLOptions +StdEnvVars
        </Directory>

        BrowserMatch "MSIE [2-6]" \
                nokeepalive ssl-unclean-shutdown \
                downgrade-1.0 force-response-1.0
        BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

</VirtualHost>
</IfModule>

@devilx please see below:

    <?php
        
    return array(
        /*
        |--------------------------------------------------------------------------
        | Access settings
        |--------------------------------------------------------------------------
        |
        | Configure under what DNS entries and ports your Paperwork server is
        | accessible for clients.
        |
        | 'external' defines the settings for access Paperwork from an external
        | network. Example: If you're hosting Paperwork within your LAN
        | (192.168.1.0/24) and use port-forwarding on your router to allow access
        | from outside of your LAN, this configuration tells clients, which
        | host-/domainname and ports to use for reaching Paperwork.
        |               
        | 'internal' defines the settings for access Paperwork within your LAN. If
        | your Paperwork installation is reachable from your LAN using the
        | previously defined 'external' settings, you can skip the 'internal'
        | configuration.
        |               
        */      
        'access' => array(
                'external' => array(
                        'dns'   => 'note.example.com',
                        'ports' => array(
                                'http'           => 80,
                                'https'          => 443,
                                'forceHttps' => true
                        )       
                ),
        //  if same as external:
                'internal' => null
        //      'internal' => array(
        //              'dns' => 'localhost',
        //              'ports' => array(
        //                      'http'           => 8888,
        //                      'https'          => 8443,
        //                      'forceHttps' => false
        //              )
        //      )
        ),

        /*
        |--------------------------------------------------------------------------
        | Enable registration
        |--------------------------------------------------------------------------
        |
        | If set to true, user registration is enabled. If set to false
        | no new users will be able to register.
        |
        */
        'registration' => false,

        /*
        |--------------------------------------------------------------------------
        | Automatically detect language through user agent
        |--------------------------------------------------------------------------
        |
        | If set to true, Paperwork will automatically set the user-interface
        | language depending on the user-agent languages. If set to false, the
        | language set in app.php -> locale will be used.
        |
        */
        'userAgentLanguage' => false,

        /*
        |--------------------------------------------------------------------------
        | Directory where uploaded files are being saved in
        |--------------------------------------------------------------------------
        |
        | The directory for saving uploaded files in.
        |
        */
        'attachmentsDirectory' => storage_path() . '/attachments',

        /*
        |--------------------------------------------------------------------------
        | Attachments preview settings
        |--------------------------------------------------------------------------
        |
        | Settings regarding attachments preview generation.
        |
        | 'resolution' defines the generated resolution. The higher this is, the
        | more disk space previews will consume.
        |
        | 'directory' defines the directory in which to store the previews.
        | This usually is the same as 'attachmentsDirectory'.
        |
        */
        'attachmentsPreview' => array(
                'resolution' => array(
                        'x' => 500,
                        'y' => 500
                ),
                'directory' => storage_path() . '/attachments'
        ),

        /*
        |--------------------------------------------------------------------------
        | Tesseract temporary directory
        |--------------------------------------------------------------------------
        |
        | The directory where temporary tesseract files are being store into.
        |
        */
        'tesseractTempDirectory' => storage_path() . '/cache',

        /*
        |--------------------------------------------------------------------------
        | Show issue reporting link
        |--------------------------------------------------------------------------
        |
        | If set to true, a link for reporting issues is being displayed.
        |
        */
        'showIssueReportingLink' => true,

        /*
        |--------------------------------------------------------------------------
        | Prefix character that describes a public tag
        |--------------------------------------------------------------------------
        |
        | The prefix character that describes a public tag. Example:
        | When a user adds a new tag (e.g. "meeting") without this character, the
        | tag is only visible to him, even when the note is being shared with
        | other users.
        | If the user prefixes the tag with this character (e.g. "+meeting"), this
        | tag will be visible to him and others he shared the note with.
        |
        | The maximum accepted length of this variable is exactly one character.
        |
        | WARNING: This value may only be changed during setup, as long as no
        | tags have been added. If you change this afterwards, things will
        | break.
        |
        */
        'tagsPublicPrefixCharacter' => '+',
    );

**Comment by devilx** [comment]
@letlive please comment the line ```'internal' => null``` and check again.

**Comment by letlive** [comment]
Spot on! I could login to paperwork! Thanks, @devilx!

**Comment by devilx** [comment]
@letlive thank you for reporting this, as the config-checker definitely needs to catch this exception.
