### ISSUE TITLE
Always have a blank "Untitled" revision in the note history

### ISSUE THREAD

**Issue by loveshizuka** [twostairs/paperwork#774]
When I created a new note, always have a blank "Untitled" revision in the note history. Is this normal? I think the blank "Untitled" revision in the note history is unnecessary.
![20170312145831](https://cloud.githubusercontent.com/assets/25612355/23829737/d417c340-0734-11e7-9169-4e4795c1d3fc.png)

**Comment by Liongold** [comment]
The first version is automatically set on note creation. However, a solution to this issue could be that the first version is hidden from history.

**Comment by Liongold** [comment]
A pull request has been opened which should fix this. This is #777. If you test the fix and confirm it works, it would help a great deal. Thanks.

**Comment by Liongold** [comment]
@loveshizuka The pull request has been merged and this feature should be available on both the develop and master branches. Thus, this issue will be closed. Thanks for your feedback. If you encounter any issues, please open a new issue.
