### ISSUE TITLE
Issue: Configuration has not been set correctly

### ISSUE THREAD

**Issue by petrk94** [twostairs/paperwork#778]
Hello,

after installing Paperwork dependencies (damn, please make it easier, I have no idea what all I have installed), I could finally run the setup and it could connect to the MySQL database successfully.
Unfortunately, I can not finish the installation, because I get this error displayed:
**Configuration has not been set correctly. Please try again.**

See Screenshot
![paperwork_dependencies](https://cloud.githubusercontent.com/assets/19719052/24046245/3025c7ae-0b22-11e7-9960-49975aaa082c.PNG)

![paperwork_customize](https://cloud.githubusercontent.com/assets/19719052/24046251/3383d4c2-0b22-11e7-80c0-506f8155b98d.PNG)

And now I have no idea what is wrong.
Please help, 
thanks

**Comment by Habilya** [comment]
You will have to provide some **corresponding** log entries from
paperwork/frontend/app/storage/logs/laravel.log

Also as quickie checkie, make sure that 
paperwork/frontend/app/storage
is writable by your WebServer user (user you are running webserver from)

**Comment by Liongold** [comment]
Any progress in this?

**Comment by petrk94** [comment]
I have tried that.
Set `chmod 777 paperwork/frontend/app/storage`
and `echo "4" > /var/www/paperwork/frontend/app/storage/config/setup`
But it didnt worked and the page is not accessible. 
Maybe I should try it a later time with a fresh installation.
