### ISSUE TITLE
Issue with running in Docker under HTTPS

### ISSUE THREAD

**Issue by m0nhawk** [twostairs/paperwork#779]
I'm unable to properly run the Paperwork in Docker under HTTPS: the resources are being served with `http` prefix and therefore breaking the application:

![default](https://cloud.githubusercontent.com/assets/8220926/24110846/3a3e1930-0d9d-11e7-8e10-08401f04df54.png)

How can I specify to use HTTPS, instead of HTTP?

**Comment by Liongold** [comment]
Are you using a reverse proxy? If yes, try the code found in this pull request #775.

**Comment by m0nhawk** [comment]
@Liongold Great, thanks. It works now.

Hope it will be merged soon!

**Comment by Liongold** [comment]
Just for your information, the pull request has been merged and the new code can be found in both the develop and master branches.
