### ISSUE TITLE
Skipping the config wizard for a docker container

### ISSUE THREAD

**Issue by gdgeorge** [twostairs/paperwork#786]
I'm working on dockerizing Paperwork using Zukhov's method (https://hub.docker.com/r/zuhkov/paperwork/). The idea is to generate everything inside the dockerfile, assign a pseudo-random password to a database.php file, and thus avoid any setup. I've got everything running but am having issues skipping the setup wizard. I've created the setup file in /app/config directory containing 8 but to no avail. What am I missing?

Thanks!
echo4golf

**Comment by gdgeorge** [comment]
Following up on this. I'm able to confirm that my database and user are loading.  Even if I complete the wizard though I can't log on to Paperwork with either the user created by the dockerfile or the one created by the wizard.  I guess the answer is to step through the the Docker install instructions side by side with the dockerfile, but the issue (and the reason that I started this project)  that docker wouldn't start when installed directly on my Ubuntu 16.04 server.  That led to the same issue with the wizard.

**Comment by Liongold** [comment]
Any progress on this? Apart from setting the setup file to 8, you need to have paperwork.json and database.json. If you are still having this problem, please specify which branch you're using.

**Comment by gdgeorge** [comment]
Thanks for getting back to me.  I 've been away from the project for a bit but will get back to it and will report back with the branch.

Best,
Jerry

**Comment by gdgeorge** [comment]
Given that this is over a year old and the project has moved on, I'm closing this. Thanks all!
