### ISSUE TITLE
See only menu and blank screen can not open notes-frame

### ISSUE THREAD

**Issue by jolinux** [twostairs/paperwork#789]
Hello 
I install paperwork from git. Install it  at virtualbox Debian Server 8.7.

Conect the Server from Host. 
Register Page ok.
Login Page ok

But login as User test can't   open Notes-Frame

![paperwork - mozilla firefox_140](https://cloud.githubusercontent.com/assets/26112620/25055164/83c7a7c4-2161-11e7-99fc-023d862efcc5.png)

Install with info https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Ubuntu-14.10

and info http://paperwork.rocks/  quick and durty !

any installion same Bug no "Notes/Notebock Screen" if I pushed Library

**Comment by Liongold** [comment]
Any errors in the browser console?

**Comment by jolinux** [comment]
Yes,


GET 
http://192.168.1.101/js/jquery.min.js [HTTP/1.1 404 Not Found 71ms]
GET 
http://192.168.1.101/js/angular.min.js [HTTP/1.1 404 Not Found 67ms]
GET 
http://192.168.1.101/js/tagsinput.min.js [HTTP/1.1 404 Not Found 68ms]
GET 
http://192.168.1.101/js/angular.min.js [HTTP/1.1 404 Not Found 21ms]
ReferenceError: angular is not defined
 paperwork.min.js:17:5
Error: Bootstrap's JavaScript requires jQuery
 bootstrap.min.js:8:1
GET 
http://192.168.1.101/js/tagsinput.min.js [HTTP/1.1 404 Not Found 22ms]
ReferenceError: jQuery is not defined
 libraries.min.js:235:1

parts from 
my   /etc/nginix/sites-available/default are

root   /var/www/paperwork/frontend/public


and other Infos from
https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Ubuntu-14.10

defines for  etc/nginix/sites-available/default

**Comment by Liongold** [comment]
Did you run npm install, bower install and gulp as outlined in the instructions?

**Comment by jolinux** [comment]
Yes I install all parts of the instructions. Have problems with a -g option at my host web-server, and install without -g option. 

And at this installation on my Virtual-Box-debian-Server I install as root but 

bower install  

abort with "bower ESUDO   Cannot run with sudo"   so I change to a non-root user and install without no errors.     This was my mistake.


I install now all npm install bower install and gulp  as ROOT.
(the problem "bower install" I change to "bower install --allow-root")

See,  All Ok thank you


![paperwork - mozilla firefox_141](https://cloud.githubusercontent.com/assets/26112620/25135009/560bcf0c-2451-11e7-800e-b7d01724de45.png)

**Comment by Liongold** [comment]
Good to hear that. I'm closing this issue then.
