### ISSUE TITLE
Feature request: Insert and tick checkboxes (for lists) 

### ISSUE THREAD

**Issue by andyforceno** [twostairs/paperwork#790]
It would be great if we could insert checkboxes, or something that allows a line to be cleared or crossed-out. A dedicated "insert checkbox" button next to the insert bullet point button would be very convenient. Plus, it would allow me to ditch Google Keep. :laughing:

**Comment by Liongold** [comment]
A solution for the crossing-out of text can be found in #753.

**Comment by kyserthehun** [comment]
I know this is old but I second the checkboxes request. Crossing-out seems clunkier for a shopping list.

**Comment by Liongold** [comment]
@kyserthehun Do you mean having a clickable checkbox?

**Comment by kyserthehun** [comment]
@Liongold Yep, just something easy to check off while shopping. Hitting edit, highlighting text and selecting cross-out is a little cumbersome.

**Comment by Liongold** [comment]
@kyserthehun Unfortunately, Paperwork does not handle editing outside of the Edit screen. That would of course change when #259 is fixed. Do you think you could be able to find a CKEditor plugin that can give you the possibility to have a checkbox in the note (however still the Edit button will need to be clicked)?

**Comment by kyserthehun** [comment]
I've never heard of CKEditor, i'll look into it.

**Comment by Liongold** [comment]
@kyserthehun Would you be interested in the possibility of supporting this syntax?
`[X]Item 1` transform itself in ~~Item 1~~, for example? If so, can you test the *experimental* branch in checkbox-experiment branch of this repo and see whether it fits your purpose?

**Comment by Liongold** [comment]
AS for CKEditor, it's the editor on which the Paperwork text box is built, more info http://www.ckeditor.com. Paperwork does not run the latest version as far as I know.

**Comment by Liongold** [comment]
#830 has been submitted which implements the experimental code as a feature. For more information, check out the pull request. If anyone would like to test the proposed code, feel free to do so. Thank you.

**Comment by Liongold** [comment]
#830 has been merged to develop. I'm closing this issue. If you have any issue with this or any other feature, please open a new issue,.
