### ISSUE TITLE
Text in the note content is not wrapped on mobile

### ISSUE THREAD

**Issue by cruisemaniac** [twostairs/paperwork#791]
When viewing on mobile, the text area overflows and forces a user to scroll past viewport.

When editing a note, there is whitespace to the right of the screen.

Screenshots attached.
![screenshot_20170419-021525](https://cloud.githubusercontent.com/assets/115579/25152411/7f249f36-24a6-11e7-9081-a5e8e3da0575.png)
![screenshot_20170419-021545](https://cloud.githubusercontent.com/assets/115579/25152412/7f27272e-24a6-11e7-9b18-fbce339a9a8d.png)

**Comment by Liongold** [comment]
Pull request #791 should fix this issue and has been merged to the develop branch. Thanks for using Paperwork and for sending your feedback. I'll close this issue since the pull request should work. If you re-encounter this issues, please open a new issue.
