### ISSUE TITLE
Blank 'Library' Screen

### ISSUE THREAD

**Issue by xendke** [twostairs/paperwork#793]
Here is what I am talking about:
![screenshot from 2017-04-23 01 52 03](https://cloud.githubusercontent.com/assets/1364447/25311151/7a4cc334-27c7-11e7-9489-1fe379ac820e.png)

followed these instructions: [https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Ubuntu-14.10](https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Ubuntu-14.10)

Also
npm install - was done, reported nothing

bower install - reports:
bower                     invalid-meta for:/srv/paperwork/frontend/bower.json
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower angular-animate extra-resolution Unnecessary resolution: angular-animate#~1.2
bower angular-resource extra-resolution Unnecessary resolution: angular-resource#~1.2
bower angular-route    extra-resolution Unnecessary resolution: angular-route#~1.2

gulp - done

**Comment by Liongold** [comment]
@xendke Can you try running bower install --verbose an see whether there any errors. Then run gulp again and try to load again. If it does not work, please mention the code found in the Settings page.

**Comment by xendke** [comment]
here is the output of bower install --verbose: [link](https://pastebin.com/0HAfey2Z)
gulp had no issues again. 
here is the code mentioned: bee708d0931145952596246aeae04bb575c5b557

**Comment by Liongold** [comment]
Sorry for the late reply. Do you have a file named 'textAngular-sanitize.js' in `frontend/app/js/bower_components/textAngular/src/`?

**Comment by xendke** [comment]
there is no src folder inside textAngular :(
``` 
$ ls frontend/app/js/bower_components/textAngular/
bower.json  changelog.md  CONTRIBUTING.md  dist/  karma-jqlite.conf.js  karma-jquery.conf.js  lib/  README.md

```

**Comment by Liongold** [comment]
That's strange. However, you should fix the problem by changing `frontend/gulpfile.js`, line 37 and replacing it with `'app/js/bower_components/textAngular/dist/textAngular-sanitize.js',`. Let us know if it works.

**Comment by xendke** [comment]
Thank you so much, was able to fix it like you said.
fresh `git clone` > edit `frontend/gulpfile.js` > continue with installation steps (`npm`, `bower`, `gulp`)

the edit:
\-  `'app/js/bower_components/textAngular/src/textAngular-sanitize.js'`
\+`'app/js/bower_components/textAngular/dist/textAngular-sanitize.min.js'`
