### ISSUE TITLE
URL not correctly set for Attachments when Paperwork is in Subfolder

### ISSUE THREAD

**Issue by Alexandero89** [twostairs/paperwork#797]
Hey folk,
When i upload an attachment to a note the upload-windows appears to open 3 or 4 times.
I have to close the first 2 or 3 popups and in the final one i can choose my file to upload.

After i uploaded the file i click on it and want to see it (for example a jpg file) , but he is setting the wrong url for the File.
For Example i get redirect to this link:

> https://web.mydomain.com/api/v1/notebooks/00000000-0000-0000-0000-000000000000/notes/f0433f80-53ee-4f41-bd34-cbafb2a416fc/versions/0/attachments/c61dfc97-a2e2-4a19-ab55-16f680123814/raw

Allthough my paperwork is reachable vie web.mydomain.com/notizen.
So if i change the url and add "notizen" to the url from above:

> https://web.ortlieb.guru/notizen/api/v1/notebooks/00000000-0000-0000-0000-000000000000/notes/f0433f80-53ee-4f41-bd34-cbafb2a416fc/versions/0/attachments/c61dfc97-a2e2-4a19-ab55-16f680123814/raw

Its working.

I have to mention that i used an other nginx config than in the wiki, because that one was not working. I always got an empty side as an answer. So im using this right now:
```
location ^~ /notizen {
    alias /var/www/paperwork/frontend/public;
    index index.php index.html index.htm;

    if (!-e $request_filename) { rewrite ^ /notizen/index.php last; }

    location ~ \.php$ {
        if (!-f $request_filename) { return 404; }

        fastcgi_pass unix:/var/run/php5-fpm.sock;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $request_filename;
    }
}
```

Also when i click on the Paperwork-Logo in the right corner he redirects me to "web.mydomain.com" instead to "web.mydomain.com/notizen".

thx in advance

**Comment by andyforceno** [comment]
I have the same issue when accessing attachments, because I am running Paperwork from a subfolder. I don't know if this is the best solution, but it works for me:

    location ~ ^/api/v1/notebooks/(.*){
        return 301 /paperwork/api/v1/notebooks/$1;
    }

**Comment by Alexandero89** [comment]
Good idea andy.
Haven't thought about this way. Will try it out now.

**Comment by Alexandero89** [comment]
Working for me too!

**Comment by Liongold** [comment]
@Alexandero89 @andyforceno I'm not experienced with Nginx and do not really how it works, but if I may, I'd suggest that you use `/api/v1/` instead of `/api/v1/notebooks/`. That way I think you could use the whole API. Sorry if I'm not understanding well. If it isn't a problem for any of you, could you please include your code snippet (maybe updated with my suggestion if it works) to the appropriate wiki page, please. Thanks.

**Comment by Alexandero89** [comment]
@Liongold  yes, your suggestion is correct and also working. Just tested it.
Will start a merge request with an updated wiki for the nginx part.

**Comment by Liongold** [comment]
@Alexandero89 Good to hear and thanks. I'll close this issue then. If you re-encounter any new issues, please open a new one.
