### ISSUE TITLE
Registering user

### ISSUE THREAD

**Issue by jerheij** [twostairs/paperwork#798]
When I am in the admin area and click "register users" I get a 404:

> Four, oh four.
> The requested item could not be found.
> Let's go back in time and try something else!

Nothing appears in the error logs.

**Comment by Liongold** [comment]
That is normal if the configuration setting in your install is not 'admin'. I'll disable the button however to make it clearer.

**Comment by jerheij** [comment]
Do you mean if the user in question is not admin or another setting?

**Comment by Liongold** [comment]
I mean the registration setting in `frontend/app/storage/config/paperwork.json `.

**Comment by jerheij** [comment]
I see my problem, I put "registration" on "false" instead of "admin". Thanks for the help!

**Comment by Liongold** [comment]
@jerheij Pull request #800 should avoid problems like yours because it is much clearer when the feature can't be used. Could you please take a look at that and say whether it is an improvement or not?
