### ISSUE TITLE
Wayback machine invisible elements hide Note Title when history is hidden

### ISSUE THREAD

**Issue by joshlemer** [twostairs/paperwork#80]
Open a note in the main view. Try to highlight the note's title in the right-hand panel. It's impossible because the Wayback Machine elements (immediately above it) are blocking it.

![screenshot from 2015-01-24 10 16 53](https://cloud.githubusercontent.com/assets/5122903/5887983/496727dc-a3b2-11e4-9d56-9fa5e79c7d6c.png)

If the #wayback-machine node is deleted it works fine. I think a good solution would be to toggle the visibility: Hidden; attribute of the #wayback-machine element when the history icon is shown. 

I'll try working on this later today if I get the chance.

**Comment by devilx** [comment]
Maybe this needs to go into https://github.com/twostairs/freqselector - depending whether it's only a problem of the CSS used within Paperwork or a general library issue.

**Comment by Liongold** [comment]
I'd like to do this if it isn't a problem.
