### ISSUE TITLE
Ckeditor settings in paperwork.json

### ISSUE THREAD

**Issue by jerheij** [twostairs/paperwork#804]
I've downloaded the "develop" branch zip and merged it into my apache paperwork folder with rsync but I. I put the following in my `paperwork/frontend/app/storage/config/paperwork.json`:

> {
> "registration": "true",
> "forgot_password": false,
> "showIssueReportingLink": true,
> "removeEditorButtonsCKEditor": "Cut"
> }

Yet my ckeditor buttons are no different, other settings are still working though. How do I know for sure I am running the webapp on the develop branch?

**Comment by Liongold** [comment]
To be sure that you are running the develop branch, do `git status`, the first line of the reply should say `On branch develop`.

**Comment by Liongold** [comment]
This has been fixed in #805 which has just been merged. Please run `git pull` and then `gulp` to be able to use this feature. I'll close this issue. If you re-encounter this issue, please re-open. If you encounter another issue, please open a new one. Thanks.

**Comment by jerheij** [comment]
Sorry for reopening this issue but I successfully tested this today and it works like a charm. Buttons can be removed through the paperwork.json config.
