### ISSUE TITLE
Same as issue 689 - Configuration has not been set correctly. Please try again

### ISSUE THREAD

**Issue by davidtessier** [twostairs/paperwork#807]
Issue 689 was closed, and said it had no one assigned so I thought I'd create a new issue... I'm sorry if that's the wrong thing to do, I don't use github a lot. 

I have reviewed [this thread ](https://github.com/twostairs/paperwork/issues/689) and am in the same boat.
I enforce HTTPS on my server if that matters.
I have mod enable rewrite on.
I have done a chown www-data * -R on the paperwork folder.

My issues are the same as above:

I get to step 4 and am presented with "Configuration has not been set correctly. Please try again."
When I look at the Chrome console it says setup/setConfig not found (404).
The database.json file is created in app/storage/config but the paperwork.json isn't. I do see the default-paperwork.json file though.

I am not using nginx, but a standard LAMP setup on Ubuntu 16.04.

I've been really interested in this software for weeks and have been struggling to get past this step but can't figure out what to do. It may be a permission issue, but I'm not a monster server admin yet so I may need pointers on what else I can do besides the chown.

**Comment by Liongold** [comment]
@davidtessier Why have you closed this issue? Did you fix the problem?

**Comment by Liongold** [comment]
Did you follow some of the solutions in #689? Are you using Paperwork from a subfolder? Can you assign more permissions to the paperwork folder during installation and try again?

**Comment by klm46** [comment]
hi, yes i did try the solutions. subfolder of document root? yes. i did changeown nginx with the hole files. do i need to give 777?

**Comment by Liongold** [comment]
Try 777 during installation and then change it again. However, probably, it's the subfolder that is causing the problem. Can you post a screenshot of the Developer Tools' Network tab of your browser please?

**Comment by klm46** [comment]
i come back tomorrow, need to hurry up. but thanks for the quik replays!

**Comment by klm46** [comment]
So, back here. Console says 500 by building database, but mysql says:

MariaDB [(none)]> SHOW TABLES FROM paperwork;
+---------------------+
| Tables_in_paperwork |
+---------------------+
| attachment_version  |
| attachments         |
| language_user       |
| languages           |
| migrations          |
| note_user           |
| notebook_user       |
| notebooks           |
| notes               |
| password_reminders  |
| sessions            |
| settings            |
| shortcuts           |
| tag_note            |
| tags                |
| users               |
| versions            |
+---------------------+
17 rows in set (0.00 sec)

![screenshot from 2017-06-08 08-59-18](https://user-images.githubusercontent.com/7510750/26916345-539437d6-4c2a-11e7-8f4c-42bea912f788.png)

**Comment by klm46** [comment]
@Liongold any idea?

**Comment by Liongold** [comment]
@klm46 The Setup wizard will be updated soon. Can you try the branch running the new setup wizard version? It can be found in pull request #809. Can you test it and see if it works please?

**Comment by klm46** [comment]
809 pulled, now the failure is @ database step! tried many times, credentials are correct. this is really sad :/

![screenshot from 2017-06-13 15-38-38](https://user-images.githubusercontent.com/7510750/27085087-8e6f753c-504e-11e7-8eba-0fbe3d1586e0.png)

**Comment by klm46** [comment]
`2017/06/13 15:49:27 [error] 1140#0: *75 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: HTTP_REFERRER in /var/www/html/paperwork/frontend/public/setup/check_database_credentials.php on line 37" while reading response header from upstream, client: IP, server: URL, request: "POST /setup/check_database_credentials.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "URL:8888", referrer: "http://URL:8888/setup.php"
2017/06/13 15:49:27 [error] 1140#0: *75 directory index of "/var/www/html/paperwork/frontend/public/setup/" is forbidden, client: IP, server: URL, request: "GET /setup/ HTTP/1.1", host: "URL:8888", referrer: "http://URL:8888/setup.php"`

**Comment by Liongold** [comment]
Are you running Nginx? Anyway, I've done some additional changes to that pull request and I've removed the use of HTTP_REFERRER so that should, in any case, take away one of the errors. Can you try again?
