### ISSUE TITLE
Your credentials are invalid with eloquentldap

### ISSUE THREAD

**Issue by Willzyc** [twostairs/paperwork#826]
I always get the error that my credentials are invalid.

The ldap configuration is correct and everytime I login, I see the right query in the ldap logs, which returns 1 entry.

I use the docker image and if i switch to eloquent in the auth config and turn registration link on everything works fine.

I tried debugging the login process with 

`var_dump($userInfo); `

It returns this for login name john.doe:

`array(4) { 
    ["firstname"]=> string(6) "John" 
    ["lastname"]=> string(6) "Doe" 
    ["username"]=> string(13) "john.doe" 
    ["password"]=> string(8) "ldapAuth" 
} `

added to EloquentLdapAuthenticatedUserProvider.php

`    public function retrieveByCredentials(array $credentials)
{
        //...
                    $userInfo = array();
                    $userInfo['firstname'] = isset($ldapInfo['givenname']) ? $ldapInfo['givenname'][0] : $username;
                    $userInfo['lastname'] = isset($ldapInfo['sn']) ? $ldapInfo['sn'][0] : '';
                    $userInfo['username'] = $username;
                    $userInfo['password'] = 'ldapAuth';
                    var_dump($userInfo); die();

//...

        return $user;
    }`

Every field shows the expected value from my ldap user I tried to login(I tried multiple users, it always worked). 

Then I tried modifing the validateCredentials method to always return true.

`public function validateCredentials(UserInterface $user, array $credentials)
{
    return true;
}`

Still invalid credentials.

Here is my auth.php

`<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Default Authentication Driver
	|--------------------------------------------------------------------------
	|
	| This option controls the authentication driver that will be utilized.
	| This driver manages the retrieval and authentication of the users
	| attempting to get access to protected areas of your application.
	|
	| Supported: "database", "eloquent", "eloquentldap"
	|
	*/

	'driver' => 'eloquentldap',

	/*
	|--------------------------------------------------------------------------
	| Authentication Model
	|--------------------------------------------------------------------------
	|
	| When using the "Eloquent" authentication driver, we need to know which
	| Eloquent model should be used to retrieve your users. Of course, it
	| is often just the "User" model but you may use whatever you like.
	|
	*/

	'model' => 'User',

	/*
	|--------------------------------------------------------------------------
	| Authentication Table
	|--------------------------------------------------------------------------
	|
	| When using the "Database" authentication driver, we need to know which
	| table should be used to retrieve your users. We have chosen a basic
	| default value but you may easily change it to any table you like.
	|
	*/

	'table' => 'users',

	/*
	|--------------------------------------------------------------------------
	| Password Reminder Settings
	|--------------------------------------------------------------------------
	|
	| Here you may set the settings for password reminders, including a view
	| that should be used as your password reminder e-mail. You will also
	| be able to set the name of the table that holds the reset tokens.
	|
	| The "expire" time is the number of minutes that the reminder should be
	| considered valid. This security feature keeps tokens short-lived so
	| they have less time to be guessed. You may change this as needed.
	|
	*/

	'reminder' => array(

		'email' => 'emails.auth.reminder',

		'table' => 'password_reminders',

		'expire' => 60,

	),

);`

After switching to eloquent I tried also with a fresh install.

**Comment by Willzyc** [comment]
I reimplemented the class myself, maybe this issue occured because I am using OpenLDAP, this solution now works for me:

`<?php namespace Paperwork;
use Illuminate\Auth\EloquentUserProvider;
use Illuminate\Auth\GenericUser;
use Illuminate\Hashing\HasherInterface;
use Illuminate\Auth\UserInterface;
use Illuminate\Support\Facades\App;

class EloquentLdapAuthenticatedUserProvider extends EloquentUserProvider
{
    
    private $config;
    
    private $ldapConnection;
    
    public function __construct(HasherInterface $hasher, $model,  $config)
    {
        parent::__construct($hasher,$model);
        $this->config = $config;
    }

    /**
     * Retrieve a user by the given credentials.
     * This will first authenticate against ldap before loading the user with eloquent
     * @param  array  $credentials
     * @return \Illuminate\Auth\UserInterface|null
     */
    public function retrieveByCredentials(array $credentials)
    {
        $username = $credentials['username'];
        $user = $this->createModel()->query()->where('username',$username)->first();
        if ($user == null && ($this->config['autoRegister'] || isset($credentials['isRegister']) )){
            //if our user wasn't found, and we have auto register enabled or we're coming from the user registration
            //directly, then we'll attempt an authentication and take the appropriate action.
            if(!$userLdap = $this->getLdapUser($username)) {
                return null;
            }

            if ($this->checkPassword($userLdap[0]['userpassword'][0], $credentials['password'])){
                if ($this->config['autoRegister']){
                    //if we have auto register enabled, create a user and such using the ldap info.
                    $userInfo = array();
                    $userInfo['firstname'] = isset($userLdap[0]['givenname']) ? $userLdap[0]['givenname'][0] : $username;
                    $userInfo['lastname'] = isset($userLdap[0]['sn']) ? $userLdap[0]['sn'][0] : '';
                    $userInfo['username'] = $username;
                    $userInfo['password'] = 'ldapAuth';
                    $user = App::make('UserRegistrator')->registerUser($userInfo,$this->config['registrationLanguage']);
                } elseif (isset($credentials['isRegister'])) {
                    //if we're not auto registering, but this is the registration process,
                    //we need to return a valid UserInterface object so that Guard will
                    //pass the authentication and actually continue with the registration process.
                    //This is necessary because we don't allow users that can't authenticate to ldap to register
                    $user = new GenericUser(array("id"=>$username));
                }
            }
        }
        return $user;
    }

    /**
     * Validate a user against the given credentials.
     *
     * @param  \Illuminate\Auth\UserInterface  $user
     * @param  array  $credentials
     * @return bool
     */
    public function validateCredentials(UserInterface $user, array $credentials)
    {
        return $this->ldapAuth($credentials['username'], $credentials['password']);
    }
    
    protected function ldapAuth($username, $password)
    {
        if(!$user = $this->getLdapUser($username)) {
            return false;
        }

        return $this->checkPassword($user[0]['userpassword'][0], $password);
    }
    
    protected function getLdapUser($username)
    {
        if (!$this->ldapConnection) {
            if ($this->config['use_ssl']) {
                $ldapHost = 'ldaps://' . $this->config['domain_controllers'][0];
            } else {
                $ldapHost = 'ldap://' . $this->config['domain_controllers'][0];
            }
            
            if (!$connect = ldap_connect($ldapHost, $this->config['ad_port'])) {
                throw new \Exception('Could not establish connection to LDAP');
            }
            
            ldap_set_option($connect, LDAP_OPT_PROTOCOL_VERSION, 3);
            ldap_set_option($connect, LDAP_OPT_REFERRALS, 0);

            if (!$bind = ldap_bind($connect, $this->config['admin_username'], $this->config['admin_password'])) {
                throw new \Exception('Could not login to LDAP');
	    }

            $this->ldapConnection = $connect;
        }

        $fields = '(&';

        foreach($this->config['person_filter'] as $attribute => $value) {
            $fields .= '(' . $attribute . '=' . $value . ')';
        }

        $fields .= '(' . $this->config['user_id_key'] . '=' . $username . '))';

        $search = ldap_search($this->ldapConnection, $this->config['base_dn'], $fields);
	$result = ldap_get_entries($this->ldapConnection, $search);

        ldap_close($this->ldapConnection);
	$this->ldapConnection = null;

	if ($result['count'] != 1) {
            return null;
        }
        return $result;
    }
    
    protected function checkPassword($hash, $password)
    {
        if ($hash == '') { // no password
            return false;
        }
 
        if ($hash{0} != '{') { // plaintext password
            if ($password == $hash) {
                return true;
            }
            return false;
        }
 
        if (substr($hash,0,7) == '{crypt}') {
            if (crypt($password, substr($hash,7)) == substr($hash,7)) {
                return true;
            }
            return false;
        } elseif (substr($hash,0,5) == '{MD5}') {
            $encryptedPassword = '{MD5}' . base64_encode(md5( $password,TRUE));
        } elseif (substr($hash,0,6) == '{SHA1}') {
            $encryptedPassword = '{SHA}' . base64_encode(sha1( $password, TRUE ));
        } elseif (substr($hash,0,6) == '{SSHA}') {
            $salt = substr(base64_decode(substr($hash,6)),20);
            $encryptedPassword = '{SSHA}' . base64_encode(sha1( $password.$salt, TRUE ). $salt);
        } else {
            throw new \Exception("Unsupported password hash format");
        }
 
        if ($hash == $encryptedPassword) {
            return true;
        }
        return false;
    }
} 
`

And the config in config/ldap.php

`<?php 

return array(
     'account_suffix'=>  "",
     'domain_controllers'=>  array("ldap.example.com"),
     'base_dn'   =>  'ou=people,dc=example,dc=com',
     'autoRegister' => true,
     'registrationLanguage' => 'en',
     'use_ssl' => true,
     'ad_port' => '636',
     'admin_username' => 'cn=admin,dc=example,dc=com',
     'admin_password' => 'yourpassword',
     'user_id_key' => 'uid',
     'person_filter' => array('objectClass' => 'inetOrgPerson'),
);
`

**Comment by Liongold** [comment]
@Willzyc Can you please open a pull request with the code you are proposing here? I think this fixes #605.
