### ISSUE TITLE
Disable registration after setup

### ISSUE THREAD

**Issue by OriginalDotte** [twostairs/paperwork#828]
Hi,
Just installed Paperwork yesterday and I am really impressed with it and I hope it can replace Evernote for me. 

After installation, I forgot to turn off allow registration for new users. After looking through the wiki and open issues I found a thread explaining that `frontend/app/config/paperwork.php/` had setting that needed to be changed to false. 

Which was easy enough to do, although that did not solve the problem. I could still see the sign up button at the login screen.

The issue was the Enable registration section didn't have a `== "true"`

/*`
        |--------------------------------------------------------------------------
        | Enable registration
        |--------------------------------------------------------------------------
        |
        | If set to true, user registration is enabled. If set to false
        | no new users will be able to register.
        |
        */
        'registration' => isset($configuration->registration) ? ($configuration->registration) : false,
`

It was easy to add it back though

`'registration' => isset($configuration->registration) ? ($configuration->registration == "true") : false,`

After that was added the sign up button disappeared.

**Comment by Liongold** [comment]
@OriginalDotte Did you try setting to `false` the registration line in `frontend/app/storage/config/paperwork.json`?

**Comment by OriginalDotte** [comment]
Yes I did do that before I changed the `paperwork.php` file, and the sign up button was still there. It didnt go away until I altered the `paperwork.php` file as well.

**Comment by Liongold** [comment]
@OriginalDotte What branch are you using? In the latest develop branch, setting registration `"false"` (with the quotes) removes the Sign up button.

**Comment by OriginalDotte** [comment]
@Liongold Works as expected. My only explanation is perhaps I forgot to restart Nginx after I changed the `paperwork.json` 

My issue can be closed now, thanks for your quick response

**Comment by Liongold** [comment]
Thank you.
