### ISSUE TITLE
Recovery Delete Notebook (?)

### ISSUE THREAD

**Issue by Panagiotarakos** [twostairs/paperwork#835]
Hello,

can be restored folder that has been deleted?

**Comment by jsEveryDay** [comment]
Not sure what folder you are referring to but all your notes and every revision is on a table called "versions" in the db.

**Comment by idreamerhx** [comment]
ext4 or other linux file system folder may not easy to recorver. If you delete a notebook, just set some flags in mysql/pgsql can recorver the notebook.

**Comment by Liongold** [comment]
Thank you for your issue report. To un-delete a note/notebook/collection, just unset the `deleted_at` timestamp field value. Unfortunately, there's no UI to do this at the moment.

**Comment by Liongold** [comment]
#264 is the issue dedicated to the creation of something like this so I'll close this as a duplicate of that issue. Thank you for using Paperwork.. If you have any issues, feel free to open a new issue.
