### ISSUE TITLE
get request to /api/v1/notebooks/{notebookId} should also return created_at and updated_at timestamps

### ISSUE THREAD

**Issue by ntnn** [twostairs/paperwork#84]
Currently the [get request](http://docs.paperwork.apiary.io/#get-%2Fapi%2Fv1%2Fnotebooks%2F{notebookId}) only returns id, title, type and and children, while [put](http://docs.paperwork.apiary.io/#put-%2Fapi%2Fv1%2Fnotebooks%2F{notebookId}), [delete](http://docs.paperwork.apiary.io/#delete-%2Fapi%2Fv1%2Fnotebooks%2F{notebookId}) and [post](http://docs.paperwork.apiary.io/#post-%2Fapi%2Fv1%2Fnotebooks) also return the mentioned timestamps.

Additionally, get requests to [notes](http://docs.paperwork.apiary.io/#get-%2Fapi%2Fv1%2Fnotebooks%2F{notebookId}%2Fnotes%2F{noteId}), [versions](http://docs.paperwork.apiary.io/#get-%2Fapi%2Fv1%2Fnotebooks%2F{notebookId}%2Fnotes%2F{noteId}%2Fversions) and [attachments](http://docs.paperwork.apiary.io/#get-%2Fapi%2Fv1%2Fnotebooks%2F{notebookId}%2Fnotes%2F{noteId}%2Fversions%2F{versionId}%2Fattachments%2F{attachmentId}) also return timestamps, so this would be a nice continuity.

**Comment by devilx** [comment]
Currently I'm refactoring quite a lot regarding the database and the DAL. This will be included as soon as it's done. Thanks for requesting!

**Comment by ntnn** [comment]
Will that also include tagging notes and creating tags via api?

**Comment by devilx** [comment]
@ntnn this will include the things you mentioned later on, initially this refactoring prepares Paperwork for #66. This means, cleaning up the database requests and migrating towards UUIDs. Check out the branch "issue-66-feature" (b121109a83b1d7c5a27058c5e36120ee458355c9) for more details.

**Comment by clemlaf** [comment]
This issue seems to be fixed, since the PaperworkDbNotebookObject class' get function returns the timestamps. Can it be closed ?

**Comment by Liongold** [comment]
I think this issue can be closed. If someone does not agree, please reopen.
