### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by FromBabylon** [twostairs/paperwork#85]
Hi,

I am running an ubuntu 14.04 server with apache. Installation of paperwork goes fine and I launch the app by reaching https://IP/paperwork/frontend/public. 
(I cannot change the docroot because I have other webapps in /var/www/html)

User registration goes fine too but after I am not able to create notebooks. When the "create" button is pushed nothing happens.
Also, image on login screen and logo on top left corner while in the app don't display. When I try right click see image I have a Page not found error and it show the url requested was "https://IP/image/..." instead of "https://IP/paperwork/frontend/public/images/...". 

What can I do to fix it ?

Thanks

EDIT: 
By setting Apache docroot to public/ folder everything goes fine in the app (images, notebooks etc..). I still need to add index.php at the end of url.
But I can't work like this because of my other apps.

**Comment by devilx** [comment]
@FromBabylon check out this issue here: https://github.com/twostairs/paperwork/issues/5#issuecomment-58722504

ToDo for the rest of us: Document the "shared hosting" problematics within the README.md, so that no more questions about this will appear. :-)

**Comment by Liongold** [comment]
I installed Paperwork while having this problem so I can work on this.

**Comment by devilx** [comment]
:+1:

**Comment by FromBabylon** [comment]
Which Readme ?

Finally I understood this is a laravel problem. 
To get things working on a Linux environment I move all frontend/ content into /var/www/ and all frontend/public content into /var/www/html/ (my doc root). Edit bootstrap/path.php and I replaced 'public' by 'html'. Then everything works fine.

The only problem here is that my server is now messed up by all Paperwork files. And I really don't like that. Furthermore I now have an .htaccess in /var/www/html so every new app I will put in that folder will have to either have its own .htaccess or have AllowOverride None in apache config files otherwise it gets redirect to Paperwork. 

I'll keep on searching a workaround despite all works well at this point.

**Comment by joshlemer** [comment]
@FromBabylon This might be a stupid question, but did you remember to do this from the paperwork/frontend directory in terminal:
    php artisan serve  

If you don't do this, you'll have to add /index.html to everything and a lot of things won't work.

**Comment by FromBabylon** [comment]
No I didn't do that because it is not written anywhere in the doc ^^ 
What will this command do exactly ?

**Comment by joshlemer** [comment]
It starts a Laravel Development Server on Localhost:8000. Try doing that. I agree we should work on the setup instructions - I was thinking I might upload my Linux Mint virtual machine development environment so people can get it up and running in a VM right away actually.

**Comment by FromBabylon** [comment]
I don't understand why sould I do that ? ^^ 
Furthermore I won't be able to go at localhost:8000 on my remote machine which do not have any GUI. I think it's possible but I just don't see the point

**Comment by Whisprin** [comment]
Please have a look at:
https://github.com/Whisprin/paperwork/commit/8445d3197e3aaca66dca7a6ce5b0a50ff337b8c2

It fixed this problem for me.
Basically a few paths were changed to use relative paths instead of staring with a "/".

**Comment by Liongold** [comment]
I have updated the README with more details. Can you check if it's enough, please?

**Comment by Whisprin** [comment]
@Liongold The .htaccess you are suggesting would rewrite all requests to domain.com/* to paperwork. Therefore I could not use it because it would disable all other sites running on domain.com. Additionally I already have an .htaccess file in my document root.

The easiest way to run paperwork from a subfolder, e.g.: domain.com/paperwork:
Clone repo into some folder
Symlink frontend/public/ to <document_root>/paperwork
Set permissions of frontend/app/storage/ correctly

But for this to work some minor changes are required which I attempted in my fork.

**Comment by devilx** [comment]
@Whisprin will your changes work with both versions? (shared and standalone hosting)

**Comment by Whisprin** [comment]
@devilx Yes, I've tested my changes both ways:

domain.com pointing to /srv/http
-> domain.com/paperwork is functional
At the same time:
paperwork.domain.com pointing to /srv/http/paperwork
-> paperwork.domain.com is functional as well

**Comment by devilx** [comment]
@Whisprin well, then feel free to request a pull to develop! :+1:

**Comment by FromBabylon** [comment]
I still have images problem if I try to install paperwork like any other apps and access via IP/paperwork. I'm currently digging into nginx and perl to find a good solution. 
Did @Whisprin changes were applied to this repo ?

**Comment by Whisprin** [comment]
@FromBabylon Not yet. But feel free to clone my fork and report back.

**Comment by FromBabylon** [comment]
I have tried your fork. On its own no css and js are running so I can only get to login screen but with some nginx rewriting rules I am now able to run Paperwork in a subfolder. App runs well I can do all the tasks the only problem is that I don't have login page logo (nginx misconfiguration) and fonts like tags, notebooks, notes logos are not displayed. I have a 404 error for https://IP/paperwork/frontend/public/fonts/fontawesome-webfont.woff?v=4.1.0. 
I am still seeking for the "perfect" solution. My problem is really the fact that I have no domain name registered. It should be really easy to set up something like paperwork.domain.com if I had one.

**Comment by Liongold** [comment]
Did you try running gulp in the frontend folder? Any errors in the console
or anything interesting in the Network panel?

Sincerely,
Jean Spiteri.

**Comment by FromBabylon** [comment]
I forgot to run gulp but it seems that it didn't change anything (strange ?). When on login screen I still can see errors in the console : 
GET https://IP/paperwork/frontend/public/index.php/images/paperwork-logo.png 404 (Not Found) login:38
GET https://IP/paperwork/frontend/public/fonts/fontawesome-webfont.woff?v=4.1.0  login:74
GET https://IP/paperwork/frontend/public/fonts/fontawesome-webfont.ttf?v=4.1.0  login:74
HEAD https://IP/paperwork/frontend/public/index.php/images/paperwork-logo@2x.png 404 (Not Found) 

The first and last errors are due to a misconfiguration in NGINX because it seeks /index.php/images/... instead of /public/images/... This should be related to what is called "Pretty urls with Laravel" and my own config. However I don't understand why fonts are not found. Can it be related to the fact that there is "?v=4.1.0" in the url ?

**Comment by joshlemer** [comment]
Did you run 
php artisan serve
In the frontend directory?

**Comment by FromBabylon** [comment]
That's what you suggested to me earlier in the thread but I still don't understand what does it really do. It just says "Laravel development server started on http://localhost:8000" and nothing happens after. And nothing change.
I can get rid of error related to login logo if I set url to ip/paperwork/frontend/public/login but I can't login thereafter because I am redirected to ip/paperwork/frontend/public/. I can login correctly if I am on ip/paperwork/frontend/public/index.php/login but I won't see login logo.

**Comment by joshlemer** [comment]
Yeah I couldn't really tell you what exactly artisan is doing when you tell it to serve, but okay do that and now you should be able to access the site at localhost:8000, which should redirect you to the login page.

**Comment by FromBabylon** [comment]
Is there a difference between nginx or apache that serves the app and artisan ? I mean this for testing right ? The problem is that paperwork is on my server which do not have any GUI so I can't browse to localhost:8000.

**Comment by joshlemer** [comment]
@FromBabylon Sorry I can't be of more help - I'm really not the right guy at all to ask about these sorts of things though.

**Comment by FromBabylon** [comment]
After a lot of tries I think there really is something with paperwork that make it "impossible" to run it in a subfolder and use directive like alias or root or nginx rewrites to make it work properly. I have tried every Laravel nginx config available ^^ It appears lots of these config don't even follow Nginx basis rules/pitfalls. As its goal is simplicity I made my own starting from scratch. 
So far, as I said in a previous comment, running only Nginx and rwriting rules, I could make paperwork run nearly properly (missing login logo and fonts). Urls were like that "https://IP/paperwork/..." so exactly what I wanted but I couldn't make fonts work so it was not the right solution.
I finally found something that is really close to perfect. Using only nginx with "proxy_pass" directive. Therefore I am moving to #197 
Regarding Whisprin@8445d31, these changes are necessary for both cases.

**Comment by devilx** [comment]
Just my own humble opinion here: I simply can not understand, why people would actually run Paperwork within a subfolder, if they already have access to Nginx. I mean, I could partially understand, when someone says "Hey, I have this free-of-charge webspace from 1999 that I don't have root-access to and I want to run Paperwork inside a subfolder, so I can still keep my phpBb running." – but in any other case I just can't figure out, why people are so eager in running Paperwork from inside a subfolder. No offence, it's just that I really can't see any benefits from this. :-)

Regarding the proxy-ing: Please don't mix issue, there is a Nginx/proxying issue at #197. Thanks! :+1:

**Comment by FromBabylon** [comment]
To run it aside other webb apps. So all apps on the webserver are accessed with IP/app. It more more convenient and as I said I don't know whether it's a good idea to open one port per app. 
That's exactly what I said, I am moving to 197.

**Comment by Baldrs** [comment]
For locally hosted things I usually point nginx to a folder and use dnsmasq to host some local dns zone.

For example:

     /srv/paperwork
     /srv/mediawiki
     /srv/otherapp

And the domains:

     paperwork.app
     mediawiki.app
     otherapp.app

You can of course omit hosting your dns and just add them to your `hosts` file. You even can host many apps with the same config file by using regex inside server name.

**Comment by FromBabylon** [comment]
That seems to be an interesting idea. 
I would have to configure nginx using 'paperwork.app' domain pointing to the root folder of paperwork. I don't understand how my browser will know that 'paperwork.app' is the IP of my server. I could put this into hosts file as you said but that would force me to edit hosts file on each machine I use. And I won't be able to reach my apps on a random machine (Let's say I take a friend's computer because I don't have mine). To avoid that I have to use dnsmasq ? I have never try it. Or did I misunderstood your point ?

**Comment by jasondavis** [comment]
@devilx I curently run it only on my local machine where I have a HOST file entry for `paperwork.dev`.  In reply to your comments about why anyone would ever run Paperwork inside a subfolder.  Me personally I would probably set it up on a subdomain instead of a subfolder however I don't see anything wrong with using a subfolder.  If you have 1 domain name for a website then you might have other apps running as well in which case you don't want the root of your domain pointing to paperwork as it might be used for your website.  I don't see a reason to pay yearly for a new domain name just for paperwork however I do think a subdomain would be a good idea.  I just wanted to put my opinion on it out there...I guess I don't really see anything wrong with doing...   

    www.domain.com/crm
    www.domain.com/mailapp
    www.domain.com/otherapp
    www.domain.com/paperwork

Again I guess i'm defending the use of the subfolder however I don't actually use it myself!  Well I do actually sometimes use it for certain small apps.  With something running Laravel though I guess I could see your point!

**Comment by devilx** [comment]
Okay, so as I assumed, the only reason people would want to run Paperwork alongside other web apps is, because they think that this way it's easier, than messing around with vhosts and separate domains for each vhost. Unfortunately (as everyone can see) it's not.

@FromBabylon regarding your question: In order for your clients to know of paperwork.app, mediawiki.app, etc. you might either add these on your internal DNS server or add them manually to every client's /etc/hosts.

However, as this is very much offtopic, let me close this issue. Feel free to discuss further questions on gitter/irc. :-)

**Comment by Baldrs** [comment]
It's dead easy to run dnsmasq in local net, you just need to configure your clients to listen to it.

**Comment by FromBabylon** [comment]
@devilx I think you've misunderstood a little point (even if, as you said, this is off topic). "because they think that this way it's easier". It is indeed much more easier UNLESS you have a domain name. But not everybody has one. The only way for separate vhosts would be open new ports for each app which would not be recommended. That is why people run apps in subfolders. When you only got your IP adress you can't create what you want such as paperwork.IP or IP.paperwork or whatever or that would force you to modify hosts file on machine you use and therefore prevent you from using your app on a 'not previously' used machine. 
I have to say that most of apps can run in subfolders. So it's not easy because Paperwork was not made to work that way. However it seems to affect 'only' few people. 
I've just bought a domain name so now everything is working as expected. I'll investigate for reverse proxy on local host, should be easy now.

**Comment by nbbn** [comment]
@FromBabylon if you really want a domain, you can take free subdomain from [here](https://freedns.afraid.org/). As I remember, they give subdomains in http://chickenkiller.com/. For this purpose it's enough.

BTW: I think that instruction for installation in subfolder is matter of time, Paperwork is free (like in freedom) project, and still evolves.

**Comment by devilx** [comment]
@FromBabylon these days there are a huge variety of options if you need an additional domain but don't want to spend money on one: @nbbn mentioned one solution to this, but also you could simply use dyndns for, just as I mentioned before, provide the people that use your installation with a /etc/hosts entry, that points some pseudo-domain (e.g. "paperwork.frombabylon") to your hosts IP.

You are right, that many web-services provide shared hosting ability, but if you look at the "big players" like OwnCloud, they all don't provide 100% functionality on shared environments, as for certain features it's technically not possible to do so.

Regarding the reverse proxying: Check out #197.
