### ISSUE TITLE
paperwork broken with php7.2

### ISSUE THREAD

**Issue by stueja** [twostairs/paperwork#850]
After update to php7.2 on Arch Linux, opening paperwork in a browser errors out with "Mcrypt PHP extension required."
However, php-mcrypt is deprecated since php7.1.
How can I use paperwork with php7.2?

**Comment by Liongold** [comment]
Thank you for your interest in Paperwork. 

Unfortunately, the normal version of Paperwork is based on Laravel 4.1 which depended on the mcrypt extension. Thus you need to either enable that extension or switch to the Laravel 5.3 port of Paperwork. The code for this can be found by doing `git checkout feature/laravel5`. This version may however have some things missing. Obviously, if you decide to use this, issue reports are welcome. 

I'm closing this issue as a `wontfix`. Feel free to re-open if you feel you need any more information.

**Comment by TiMESPLiNTER** [comment]
@Liongold Where is this feature branch gone?

**Comment by Liongold** [comment]
Unfortunately, since most of the development has switched to the v2 version, most branches have been removed. The removed branches includes the laravel5 version.
