### ISSUE TITLE
docker packaging is completely broken

### ISSUE THREAD

**Issue by mgolisch** [twostairs/paperwork#852]
I tried building the docker image but it fails due to missing dependency jshint in the package.json file.
After fixing that it builds but the resulting image is still broken.
the compose file tries to run a nonexistent file /app/docker-runner.sh (the Dockerfile add its to /usr/local/bin/)
the docker-runner.sh file is broken too. it calls su-exec with invalid arguments ommiting the userspec.
Not sure what the intention there was, maybe running it as root?
i tried su-exec 991:991 /bin/s6-svscan /etc/s6.d but it doesnt work as the user cant write to /etc/s6.d/.
Also running it as root fails too because the nginx config file has some non replaced placeholder/example value in it.(i dont see any of those files in the source tree so that probably part of the used image)

**Comment by Liongold** [comment]
Can you do `git checkout 346bfb05613167225f1d18a2cb57c0e52333b6cf` and then reo the installation (except the clone part), please? Thank you for using Paperwork.

**Comment by mgolisch** [comment]
Yes that works it builds a working image.

**Comment by Liongold** [comment]
Thanks for you help. I'm closing this bug then. If you re-encounter this bug or any other one in Paperwork, feel free to open a new issue.

**Comment by romu70** [comment]
I've a Dockerfile  to run Paperwork with PHP 7:
[https://github.com/romu70/self-hosting-containers/tree/master/paperwork]

Enjoy!

**Comment by Liongold** [comment]
@romu70 Thank you for that work. Would you be interested in proposing it to this repository?

**Comment by romu70** [comment]
Yes of course, no problem. How to proceed? (I'm not a GH expert).

**Comment by Liongold** [comment]
@romu70 To do this you could fork the Paperwork repository, add the files you've done to that repository, push to Github and then open a pull request from the pull requests page. If you need more detailed instructions, just ask.
