### ISSUE TITLE
Congratulations :)

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#853]
This year I complained a little about paperwork.
But I have to admit that in the last 2-3 months the program has made a big step forward. Collections finally display and close correctly (only the tools for managing/editing collections are missing - it was in the program a long time ago), icons of the type of attached file have arrived. Added "sort notes by....".  Sorting is still a little bit weaker - never the notes have set me up as they should (even after the date sorting is not working properly), it has to be refined yet.
But, in general, congratulations for the fact that so much of the programme has moved forward.

**Comment by jacek-1210** [comment]
Small correction: "sort notes by.." works correct in notebooks but dont work on root "All notes"

**Comment by Liongold** [comment]
@jacek-1210 Sorry for the late reply. Thank you for keeping trust in Paperwork and for using it. Can you show the code shown in the Settings page's About tab? Also, can you clarify the issue a little more please?

**Comment by jacek-1210** [comment]
Thx for reply. 1 hour ago, I upgrade my paperwork to newer version and it's looking good
