### ISSUE TITLE
OAuth Multiuser login functionality

### ISSUE THREAD

**Issue by petrk94** [twostairs/paperwork#862]
Hello,
I would like to know, whether paperwork has a OAuth Multiuser functionality?

**Comment by Liongold** [comment]
At the moment, Paperwork does not support OAuth functionality. Multiple user accounts are supported but have to be saved in the Paperwork database. This functionality has already been suggested in #21 and progress (at the moment none) is tracked here. Thank you for your feedback. Do you have any other questions?

**Comment by petrk94** [comment]
@Liongold no thanks, I would like to use Paperwork for a community where OAuth is used to allow all people to use Paperwork without the need to register a new account by themself.
Im looking forward to see your next release of Paperworks.

**Comment by petrk94** [comment]
Is there still a active development?
As I just saw, the last release is from 2015

**Comment by Liongold** [comment]
Development is slow since contributors are lacking. Do not consider the releases - those were ad hoc and do not represent the latest code. To get the source code, please use `git clone`.

**Comment by Liongold** [comment]
However it isn't stopped completely. Feel free to submit pull requests if you want.

**Comment by petrk94** [comment]
@Liongold my problem is the lack of PHP knowledge^^

**Comment by Liongold** [comment]
@petrk94 I guess you'll need to wait until Paperwork v2 implements that feature then. Unfortunately, all work is currently going there and it is very difficult to have new features in v1.
