### ISSUE TITLE
Chrome and Firefox cannot display words.

### ISSUE THREAD

**Issue by lufy90** [twostairs/paperwork#865]
![paperwork-cannot-display-words](https://user-images.githubusercontent.com/22901336/35393005-8f8cb29e-0198-11e8-8f6f-eb8b34b1b95c.jpg)

Chrome and Firefox cannot display words, see attachment.

**Comment by lufy90** [comment]
It is solved after I update my windows 7

**Comment by Liongold** [comment]
Good to know. Since your issue is fixed, I'll close this issue. Thank you for using Paperwork. If you encounter any new issues, feel free to open a new issue.
