### ISSUE TITLE
Can click Edit > Edit Note.. even though it's grayed out

### ISSUE THREAD

**Issue by bw2** [twostairs/paperwork#88]
In the demo version today, even though I haven't created any notes, I can click on the grayed-out "Edit Note.." menu item and it will take to an edit view for an empty note.

![image](https://cloud.githubusercontent.com/assets/6240170/5891863/02ef365c-a478-11e4-93d7-4e6ee5c6d74f.png)

**Comment by bw2** [comment]
![image](https://cloud.githubusercontent.com/assets/6240170/5891868/3445a6f0-a478-11e4-9b65-ab230276d5fa.png)

**Comment by Liongold** [comment]
Can you show a full page screenshot?

**Comment by joshlemer** [comment]
Working on this
