### ISSUE TITLE
AngularJS Bindings show Before Page is Loaded

### ISSUE THREAD

**Issue by jylertones** [twostairs/paperwork#89]
When I reload the page, I see the Angular bindings {{ ... }} before the page has rendered.

![reload mov](https://cloud.githubusercontent.com/assets/1456156/5891922/627cc424-a462-11e4-9b1b-687fcc75bbe3.gif)

From my familiarity with AngularJS, you probably need to add an ng-cloak onto the html or body elements.

**Comment by Liongold** [comment]
Thanks for the report.

**Comment by devilx** [comment]
This was actually fixed in #51 by @joshlemer. @jylertones are you running the latest GIT version of Paperwork?

**Comment by jylertones** [comment]
I'm pulling code right now. I figured I could either verify it or submit a PR :). I will let you know tonight

**Comment by devanp92** [comment]
This should be a simple fix via ng-cloak

**Comment by jylertones** [comment]
Yep, @devilx is right. This was fixed in #51 . I've verified by pulling the latest code. (I tested on the demo site, my bad!) Sorry for the trouble!
