### ISSUE TITLE
Last tag in the form field is not added to the taglist.

### ISSUE THREAD

**Issue by scrapcode** [twostairs/paperwork#90]
When creating or editing a note if you press <tab> to change focus from the tag field to the field for the content of the note, the trailing tag is not added to the list as a tag.

**Expected behavior:** The last tag in the tag list should not require a comma to commit it as a tag.

**Screenshot:**
![Last tag does not add](http://i.imgur.com/44UGoRi.png)

**Tested on:**
Firefox 34.0.5
Chromium 41.0.2263.0 (64-bit)

**Comment by ponychicken** [comment]
Dupe of #50

**Comment by scrapcode** [comment]
Definitely overlooked that. My apologies!
