### ISSUE TITLE
OMG - how to pull & install old, v1 of Paperwork ???

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#902]
How to pull or get snapshot of Paperwork v.1 ? Where is some manual ? I want to upgrade my Paperwork, but still in v.1 version, how to do it ? 

git pull https://github.com/twostairs/paperwork.git

give me v2 Paperwork. I need v1 paperwork actually version

**Comment by JamborJan** [comment]
Hey @jacek-1210,

Use

https://github.com/twostairs/paperwork/tree/1

instead and it should be the latest v.1

Hope that works for you.

**Comment by jacek-1210** [comment]
THX, but 

git pull https://github.com/twostairs/paperwork/tree/1

didn't work.
And snapshot isn't
Is it possible to use git pull on v.1 Paperwork ?

**Comment by jacek-1210** [comment]
THX, works.
