### ISSUE TITLE
paperworkViewParent isn't full screen

### ISSUE THREAD

**Issue by kypdk** [twostairs/paperwork#905]
paperworkviewparent if you do class="main col-xs-12"is fixing but opens with class="main col-xs-12 ng-scope  col-sm-offset-7 col-sm-5 col-md-offset-5 col-md-7"

**Comment by Liongold** [comment]
This should be fixed in the latest pull request merged to the `1` branch. Please pull the latest code and try again. Thank you for your interest in Paperwork. This issue will be closed. If you encounter any new issues, feel free to open a new issue.
