### ISSUE TITLE
Problem loading packages with composer

### ISSUE THREAD

**Issue by danieldaeschle** [twostairs/paperwork#909]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for erusev/parsedown dev-master -> satisfiable by erusev/parsedown[dev-master].
    - erusev/parsedown dev-master requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 2
    - simplesoftwareio/simple-qrcode 1.1.1 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - simplesoftwareio/simple-qrcode 1.1.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - Installation request for simplesoftwareio/simple-qrcode 1.1.* -> satisfiable by simplesoftwareio/simple-qrcode[1.1.0, 1.1.1].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by danieldaeschle** [comment]
nope

**Comment by adamhorsburgh** [comment]
@myesn @danieldaeschle I have found a workaround for the issue, see the link below for more information:

https://www.techtrekking.net/getting-started-with-laravel-with-ubuntu-16-04/


Ran the following commands from the shell, and everything worked fine!

sudo apt-get install php-mbstring -y
sudo apt-get install php-xml -y
./scripts/composer_wrapper.php install --no-dev

**Comment by Liongold** [comment]
Can this issue be closed? It seems like there's a workaround for it.

**Comment by danieldaeschle** [comment]
I didn't tried it yet. Close it, i will tell you to reopen it if it doesn't work.
