### ISSUE TITLE
Wiki Rpm package link no longer exists.

### ISSUE THREAD

**Issue by IcedMango** [twostairs/paperwork#910]
Hi 

Page https://github.com/twostairs/paperwork/wiki/Installation-----CentOS-Fedora
`rpm -Uvh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm`

The link is no longer exists. The newest link is http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm

**Comment by IcedMango** [comment]
@Liongold Fixed

**Comment by Liongold** [comment]
Can you close the issue please?

**Comment by Liongold** [comment]
Thanks.
