### ISSUE TITLE
Tagging: late-inserted comma doesn't split tags

### ISSUE THREAD

**Issue by pedro605** [twostairs/paperwork#96]
When the user starts typing a new tag, like "first tag second tag", and he wants to go back and place the comma before the word "second", the tags won't split up. The new tag will be "first tag second tag" instead of two tags: "first tag" and "second tag".
Minor issue, with easy workaround ;) Found on the demo page.

**Comment by devilx** [comment]
@pedro605 thanks for the feature request!

Since Paperwork is using https://github.com/timschlechter/bootstrap-tagsinput for the tags input, this enhancement should be submitted to the bootstrap-tagsinput project and then pulled from the official version into Paperwork.

**Comment by mbenford** [comment]
@devilx Perhaps you'd be interested in checking out [ngTagsInput](http://mbenford.github.io/ngTagsInput/). It's 100% Angular code, has no external dependencies and comes with lots of features (including Bootstrap support). :)

**Comment by devilx** [comment]
@mbenford it was last authored over a month ago. Is it still in active development? And do you know whether it provides everything we currently have with bootstrap-tagsinput? I think, switching towards something new should always go along with a real benefit for the users.

**Comment by mbenford** [comment]
> Is it still in active development?

Not as active as I'd like it to be, but it's definitely not dead. ;)

> And do you know whether it provides everything we currently have with bootstrap-tagsinput?

I don't. :\

> I think, switching towards something new should always go along with a real benefit for the users.

I totally agree with you. My intention was just to let you know that there's an alternative built for AngularJS. And since this is an Angular project, I thought you'd be interested in checking it out. Perhaps I should have posted this message elsewhere. My apologies for that.

**Comment by devilx** [comment]
@mbenford don't get me wrong, I'm up for trying things that would fit Paperwork's technology stack better! So, thank you for pointing me towards your project. :-)

Anyway, I/someone need(s) to take a look at your AngularJS solution and find out, whether it allows us to do the same we're currently doing with the (quite inactive) bootstrap-tagsinput plugin first.

**Comment by mbenford** [comment]
@devilx I can do that. What's the best way to communicate my findings with you? I don't want to clutter this issue (more) with non-related stuff.

**Comment by devilx** [comment]
@mbenford cool! I'm on irc://irc.freenode.net/#paperwork - although I won't be available all the time. Besides of that, you could just shoot me an e-mail to marius@paperwork.rocks / paperwork-dev@googlegroups.com

**Comment by Liongold** [comment]
I've opened an issue in the official repo of bootstrap-tagsinput.

**Comment by Liongold** [comment]
The issue I opened in the official repo has been closed, so it's difficult to get a fix from them. @devilx any idea on what should be the next step?

**Comment by Liongold** [comment]
Thanks for your feedback. Since this issue has not been commented on and a fix is not likely to come soon, I'll close this issue. If you re-encounter this issue, please reopen a new issue. If you can encounter a new one, please open a new issue issue.
