### ISSUE TITLE
Can't use my last name :(

### ISSUE THREAD

**Issue by th3m4ri0** [twostairs/paperwork#98]
![image](https://cloud.githubusercontent.com/assets/2685884/5893659/bb72f230-a4ba-11e4-8d39-fbc0bdae2872.png)

**Comment by wmealing** [comment]
Looks like a dupe of https://github.com/twostairs/paperwork/issues/86 , Save the git repo owner sometime and add yourself on that CC if its not already solved.

**Comment by th3m4ri0** [comment]
Sure. Thanks.
